### ISSUE TITLE
Skipping: prompt at end of file

### ISSUE THREAD

**Issue by bas-t** [kodi-pvr/pvr.hts#102]
Now that #92 is resolved, as far as I'm concerned, I've got a feature request.

Case:
I'm watching a recording that has about 5 minutes left to go. I accidentally jump 7 minutes forward, so past the end. In livetv this does not have any consequences, but in a recording it has.
The effect whould be: stop watching the recording.
Or I'm watching a recording and reach the end of it without skipping forward.
I'd very much like to be prompted at this point. Like: end of recording, do you want to stop watching/delete this recording?

And then I'd have the choise of skipping back, just stop or in fact delete the recording.

I'm not sure this request is addressed right, could be a kodi thing, not a pvr addon thing. (or both)

**Comment by Jalle19** [comment]
I don't think it's necessary to add a dialog prompt for this, we should instead just not try to skip past the end. I don't know if this is an addon issue or a generic Kodi issue, @FernetMenta do you know?

**Comment by bas-t** [comment]
@Jalle19 You're right, not skipping past EOF is needed anyway. But reaching EOF, one way or the other, I'd still like a dialog prompt that allowes me to either just stop watching the recording or delete it.

Come to think of it, when reaching EOF while watching a recording via a nfs share, same thing happens. So I guess that if this request can be honoured, it should be done in kodi first. If afterwards you guys should need to address any related issues in pvr.hts... 

Your thoughts?

**Comment by Jalle19** [comment]
I'm very much against showing a dialog. If you want to stop playback, just press stop. Plus we don't show a dialog when skipping all the way forward in a live stream either.

**Comment by ksooo** [comment]
Same here. :-1: for a dialog - no matter whether this is pvr.hts or kodi "issue".

**Comment by bas-t** [comment]
I get that. What about not skipping past EOF?

**Comment by ksooo** [comment]
> could be a kodi thing, not a pvr addon thing

It is a "kodi thing".

**Comment by Jalle19** [comment]
I tested a patch that prohibits this but I can't make it stop playback even if I skip all the way to the end. What happens though is that Kodi's buffering mechanism fails and the playback is all blocky until you skip back 10 seconds or more.

**Comment by bas-t** [comment]
Thanks.
