### ISSUE TITLE
Adapt to latest descrambler info API changes

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.hts#106]
See https://tvheadend.org/issues/2616 for details

**Comment by ksooo** [comment]
Just a side note: THis was added in HTSP v24

**Comment by Jalle19** [comment]
It's an old Enigms thing so old it's from the time when cardsharing was so awesome you had to see it in action on every zap.

**Comment by ksooo** [comment]
hehe

**Comment by Jalle19** [comment]
Even thought all the fancy stuff about ECM times are unnecessary before Kodi has a way to display them in the UI we still need to implement this new method to be able to properly show which CAID is being used (since HTSP v24 the CAID is always set to 0x0000 in `subscriptionStart`, clients are supposed to listen for this new message instead).

I'll try to come up with something next week. Will have to set up a complete test environment because I'm not touching my main tvheadend build.

**Comment by belliash** [comment]
Any progress here?

**Comment by Jalle19** [comment]
Sorry not yet, haven't had time to code for a while.

**Comment by Jalle19** [comment]
@perexg I tried to start implementing this today but I can't get tvheadend to actually send any `descramblerInfo` HTSP messages. I'm trying the latest master in a virtual machine with a mux URL from my main tvheadend instance. Oscam is connected using DVBAPI and descrambling works. Please advice.

**Comment by perexg** [comment]
Do you see ECM info in the tvh subscriptions tab ?

**Comment by Jalle19** [comment]
I have oscam r10500 something so it should be new enough. I didn't check the subscription tab, will do later and report back.

**Comment by perexg** [comment]
I think that the network protocol v2 was added around 10700 or so.. You should upgrade oscam.

**Comment by Jalle19** [comment]
It said protocol version 2 when I connected, but I guess I'll upgrade then.

**Comment by Jalle19** [comment]
I finished the part of the code where the status is parsed and stored in the demuxer, but we have now hit a road block. Kodi needs a new API method for retrieving all this data during streaming instead of during channel import since the CAID is not available when fetching the list of channels. I'll have to think about the best way to add this to the API.

**Comment by belliash** [comment]
When you press "O" in Kodi, it displays information about channel priovider, frequency, etc... There is also information about CAID (actually it is FFFF). This information if fetched from TVH on channel playback, not during importing channel list. After changes made by perexg, I believe TVH should pass information about current CAID to clients.

**Comment by Jalle19** [comment]
That id incorrect, the CAID is only updated when the channel is updated. That's why this PR is not yet ready.

**Comment by Leatherface75** [comment]
Any news about tihs?

**Comment by Jalle19** [comment]
Not really, haven't had the motivation to work on it for a while.

**Comment by Leatherface75** [comment]
Would it be hard to change atleast for encryption so that works again?

**Comment by Jalle19** [comment]
@ksooo I'm thinking we could parse the descrambler data coming from tvheadend, then when we get the CAID we tell Kodi to update that channel. The only downside is that there would be one update per channel switch, which isn't exactly ideal.

**Comment by ckarrie** [comment]
+1

**Comment by belliash** [comment]
Whats the progress here?

**Comment by ksooo** [comment]
zero ;-)

**Comment by belliash** [comment]
Would be nice to get this finally working

**Comment by ksooo** [comment]
Sure, but as we are all 100% volunteers, this absolutely is a question of a dev being in the mood for this ... and currently I'm not. Mainly money work - boring. Actual value of this feature is nearly zero. What's the point in knowing a channel is FTA or Nagra or whatever encrypted?  :-/

**Comment by Leatherface75** [comment]
I would like this working too

**Comment by piotrasd** [comment]
like this ?

![screenshot078](https://user-images.githubusercontent.com/773012/26844339-fcf55d50-4aea-11e7-9c3e-78f1b803c0ba.png)

**Comment by belliash** [comment]
Looks perfect. I just wonder what it will show as source if dvbapi socket used instead of IP? Maybe some name would be a better idea instead of IP (if possible to get also card name)?

**Comment by ksooo** [comment]
Guys, please stay on topic of this issue. Skinning is nothing that belongs to here. Otherwise I will lock this conversion.

**Comment by piotrasd** [comment]
guys is other way make addon-service to got rest information from API of tvheadend and it works

![screenshot089](https://user-images.githubusercontent.com/773012/26930577-bf3b427e-4c55-11e7-89a8-6e19a82523e5.png)

**Comment by ksooo** [comment]
Problem is not that we don't know what or how to implement it. HTSP provides everything we need. No need to use the http API. The only "problem" is that none of the people with the required skills is currently in the mood to do it. End of discussion.

**Comment by ksooo** [comment]
Will be fixed with #315

**Comment by ksooo** [comment]
This can be closed as it is implemented meanwhile.
