### ISSUE TITLE
No user feedback when trying to use invalid credentials

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.hts#109]
Just noticed this now, it seems the code that triggers the GUI notifications on access error were (accidentally?) commented out way back when this code lived in the `pvr.tvh` fork. I think it definitely should be resurrected, but I don't like the current approach where `CHTSPConnection` is capable of triggering GUI notifications. In `pvr.vbox` I used an approach where `client.cpp` attaches event handlers as lambda functions and the notifications (and other stuff) is triggered there. This way `CHTSPConnection` would only have to call e.g. `OnAccessDenied()`.

**Comment by Jalle19** [comment]
I suggest we skip this for Jarvis and focus on a proper implementation once https://github.com/xbmc/xbmc/pull/8736 is in.

**Comment by ksooo** [comment]
:+1:

**Comment by Jalle19** [comment]
@ksooo did you implement this in some way in your PVR API bump PR or is this still on the todo list?

**Comment by ksooo** [comment]
I think it is in. ;-) => https://github.com/kodi-pvr/pvr.hts/blob/master/src/HTSPConnection.cpp#L536 triggers an access denied kai toast in kodi when login to tvh server fails.

**Comment by Jalle19** [comment]
Good stuff, let's close this then.
