### ISSUE TITLE
PVR manager not starting

### ISSUE THREAD

**Issue by Glenn-1990** [kodi-pvr/pvr.hts#112]
I'm not able to start kodi with the tvh client since some weeks, I already deleted the database, guisettings, etc..

17:04:25 T:139706989782784   DEBUG: CPVRRecordings - Update - updating recordings
17:04:25 T:139705857324800  NOTICE: Thread PVRGUIInfo start, auto delete: false
17:04:25 T:139706989782784   DEBUG: PVRManager - Process - entering main loop
17:04:25 T:139707535042304    INFO: PVRChannelGroupsContainer - SearchMissingChannelIcons - starting channel icon search
17:04:25 T:139705840539392  NOTICE: Thread EPGUpdater start, auto delete: false
17:04:25 T:139705874110208  NOTICE: Start - EPG thread started

This is the last PVR related log line, so it seems to hang somewhere, anyone with the same problem?

**Comment by Jalle19** [comment]
Do you get anything in the log from the addon itself?

**Comment by Glenn-1990** [comment]
Yes, so the addon is loaded correctly?

I also get a selectable update button in the addon settings, it seems that kodi thinks that there is an update available... 
I'm using 2.2.9

**Comment by Jalle19** [comment]
I can't seem to reproduce this. We pushed some major refactoring earlier which may be causing the issue. Can you remove your `build` directory and complete rebuild the addon?

**Comment by ksooo** [comment]
@Jalle19 I dont think that the refactoring is the cause as Glenn-1990 wrote that he has this issue "since some weeks".

**Comment by Jalle19** [comment]
Yeah you're right. @Glenn-1990 please do a complete rebuild and report back.

**Comment by Glenn-1990** [comment]
It seems that there was something wrong with the kodi build directory, not the addon one, closing this
