### ISSUE TITLE
Autorec entries when setting a recording

### ISSUE THREAD

**Issue by bluenote73** [kodi-pvr/pvr.hts#118]
There was a client modification that added a nice "Record Once / Record Every time / Every Week at this time / etc" option which was really nice.  This would be a great enhancement and the work was done and worked.  Here's a link to the details:

http://forum.kodi.tv/showthread.php?tid=217127

I hope this isn't a faux pas to ask for enhancements here, but it's a real shame not to be included.

Thanks.

**Comment by Jalle19** [comment]
This is already supported if you use Kodi 16 Jarvis.
