### ISSUE TITLE
System default values for duplicate detection and priority are not working

### ISSUE THREAD

**Issue by Glenn-1990** [kodi-pvr/pvr.hts#124]
@ksooo 

Don't know how this is supposed to work but it seems that the priority and duplicate settings inside kodi (settings->tv->recording) are not used when creating a repeating timer?

If this is not possible, we could maybe make an addon setting for this?

**Comment by ksooo** [comment]
This is indeed not trivial. As every addon might overwrite the values and the default for these settings differently, what to display in Kodi settings?

**Comment by Jalle19** [comment]
Maybe the settings should just be removed?

**Comment by ksooo** [comment]
Maybe. Need some more time to get a clear picture on this.

**Comment by Glenn-1990** [comment]
Default values are in addon settings now, closing...

**Comment by Jalle19** [comment]
Did you mean to close this issue? It's still open.

**Comment by Glenn-1990** [comment]
Oops, forgot to push the button :p
