### ISSUE TITLE
Settings rework v2

### ISSUE THREAD

**Issue by Glenn-1990** [kodi-pvr/pvr.hts#126]
As mentioned before, the advanced tab is getting to big.
So I have some suggestion which I'm happy to implement.

3 settings tabs:
tab 1) connection settings: leave it as it is now
tab 2) streaming settings: 
          ->a] predictive tuning
          ->b] streaming profile from https://github.com/kodi-pvr/pvr.hts/pull/119
          ->c] timeshift config (to be created) with the following options, 
                 ---->1) server config (default), 
                 ---->2) force off, 
                 ---->3) select  minutes. 
          ->d] enable subscription conflict managment https://github.com/kodi-pvr/pvr.hts/pull/79
tab 3) dvr:
         ->a] autorecording start window behavior
         ->b] default value for duplicate detection
         ->c] default value for priority https://github.com/kodi-pvr/pvr.hts/issues/124 
tab 4) advanced settings:
         ->a] epg async -> maybe it's time to set this on as default?
         ->b] debug trace

This should be the final settings refactor :p
So, what do you think?

**Comment by Jalle19** [comment]
Sounds good in general, feel free to work on it. Can you elaborate on the timeshift settings?

**Comment by Glenn-1990** [comment]
@Jalle19 
Well now, timeshift is enabled when it's enabled on the server, but a user might want to use timeshift on his main box, but not on the bedroom box, as multiple timeshift instances are stressing for the server..

If the user uses predictive tuning (till 10 subscriptions) with timeshift enabled, that will also stress the server quite a bit.. Allow him to disable timeshift

Additionally we can add also a period, so the master client can be configured with a big timeshift period and the bedroom client can be configured with a small timeshift period.

**Comment by Jalle19** [comment]
Is this controlable via HTSP?

**Comment by Glenn-1990** [comment]
Yes we can set the timeshift period on subsribe, 0 = force off, infinity = server config

**Comment by Jalle19** [comment]
The part about setting it to infinity is not mentioned in the HTSP spec, are you sure that's the case? If so someone should probably update the wiki.

**Comment by Jalle19** [comment]
I would keep it simple for now and only have a checkbox like "Disable timeshifting" which defaults to false. To me it sounds like being able to control the timeshift buffer size from the client is a very edge case.

@ksooo what do you think?

**Comment by Glenn-1990** [comment]
It's currently set to infinity https://github.com/kodi-pvr/pvr.hts/blob/master/src/tvheadend/Subscription.cpp#L120

wiki -> timeshiftPeriod    u32   optional   The number of seconds to keep in the timeshift buffer
Note: this may be bounded by server configuration settings

So infinity will bounded by the server config, i.e. if the server config is 10 minutes -> 10 minutes will be used instead of infinity -> so basically you are always using the server config in this case.

If the client period is smaller than the server one, this will be used, so basically the smallest config is used, server or client. If the client uses 0 as period, this will be used. Maybe this can be added to the config as this is indeed not clear.

You can check it here: https://github.com/tvheadend/tvheadend/blob/master/src/htsp_server.c#L2082

**Comment by ksooo** [comment]
> I would keep it simple for now and only have a checkbox like "Disable timeshifting" which defaults to false. To me it sounds like being able to control the timeshift buffer size from the client is a very edge case.

 Well, I do not really see the use case for the timeshift settings. I do get that the idea for this settings is "I have a server which is not powerful enough to feed all my clients and therefore I need some client-side settings to make it work". Why not just invest in a server that suits your needs. If a Raspy is not powerful enough, buy somthing more suitable. Honestly, I do not buy that one will have timeshifting in living room but not in bedroom? Why? I'm pretty sure my wife would tell me that the bedroom HTPC is broken if Live TV there behaves different from living room HTPC. ;-)

 Okay, just my 2 Ct, I don't want to block this.

**Comment by ksooo** [comment]
And for the rest - I like it. Thanks @Glenn-1990.

**Comment by Jalle19** [comment]
If we don't want the ability to control timeshifting from the client we can just skip that for now and still go through with the rest of the changes @Glenn-1990 has outlined.

**Comment by Jalle19** [comment]
@Glenn-1990 I just merged the selectable profile stuff so feel free to start working on this now :-)

**Comment by Glenn-1990** [comment]
Is it possible to get https://github.com/kodi-pvr/pvr.hts/pull/79 in first? 
Then we can pickup that setting also.

**Comment by Jalle19** [comment]
Probably a good idea, yeah.
