### ISSUE TITLE
Master fails to build on Win32

### ISSUE THREAD

**Issue by MartijnKaijser** [kodi-pvr/pvr.hts#128]
Jenkins is failing to build since several days

**Comment by Jalle19** [comment]
Crap, will take a look.

**Comment by ksooo** [comment]
<pre>
c:\jenkins\slave\workspace\win-32\project\cmake\addons\build\pvr.hts\src\tvheadend/Settings.h(105) : error C2797: 'tvheadend::Settings::m_strStreamingProfile': list initialization inside member initializer list or non-static data member initializer is not implemented
</pre>

**Comment by ksooo** [comment]
wtf?

**Comment by ksooo** [comment]
https://github.com/kodi-pvr/pvr.hts/blob/master/src/tvheadend/Settings.h#L105

@Jalle19 do you see the curly braces? Took me about 5 mins to spot this... Will come up with a PR to fx this today.
