### ISSUE TITLE
Kodi shows disabled recordings as upcoming, when they're never going to happen

### ISSUE THREAD

**Issue by ProfYaffle** [kodi-pvr/pvr.hts#131]
As discussed with @Jalle19 on #hts...

Since https://github.com/tvheadend/tvheadend/commit/fa5795379980546c76c5686633215a56d72365b4, tvh gives the user the ability to disable an unwanted recording event rather than deleting it. This was to prevent the repeated dance of unwanted-delete-EPG match-reschedule-back in the list-unwanted-delete...

However, Kodi still shows the event as upcoming (e.g. "next recording" on the main TV screen) even if it's disabled, as there's no way for the addon to filter out these disabled events.

It appears that @ksooo has already updated the HTSP spec and bumped to v23 to accommodate the enabled flag.

**Comment by Jalle19** [comment]
@ksooo this sounds like your area of expertise

**Comment by ksooo** [comment]
IMO two steps are needed for this

1. https://github.com/ksooo/pvr.hts/commit/742cefcda4ba5f1ee1c49a1aa3c3785b23694e05 which I've created almost immediately after this feature was introduced in tvh but IIRC my tests ended up with the result that it was still buggy in tvh (at that time). I commented on the related tvh commits (https://github.com/tvheadend/tvheadend/commit/c05a4788149dfe80fb6e4023f00087684308bdcd#commitcomment-13537005) but never got feedback. Thus, I postponed this commit and did not PR it.

2. Change Kodi core to handle disabled timers correctly, for instance here https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/timers/PVRTimerInfoTag.h#L127

**Comment by ksooo** [comment]
On second thought, to solve the problem mentioned by @ProfYaffle only step 1 should be enough. Maybe step 2 is not needed at all.

@ProfYaffle maybe you can cherry-pick https://github.com/ksooo/pvr.hts/commit/742cefcda4ba5f1ee1c49a1aa3c3785b23694e05 and do some tests?

**Comment by ProfYaffle** [comment]
@ksooo No promises, but I can take a look when I get a chance, sure. I've not built the addons from source before, but I'm sure I can cope.

I think the issue you mention is the same as I raised here, btw:

https://tvheadend.org/issues/3196

... apparently fixed (although I haven't tested) in https://github.com/tvheadend/tvheadend/commit/868e64825fc3c89d2151938dcf30ebf5c1ce4144

**Comment by ProfYaffle** [comment]
_wrong button, mutter, mutter_

**Comment by ProfYaffle** [comment]
Okay, I had a look... and have simply dug myself into a hole! 

It seems that I can't just clone/build your *add-oneshot-timer-enable-support* branch because that only builds against Kodi versions since the merge of the Series Recording Support (https://github.com/xbmc/xbmc/commit/36ad0067aeaef360d7bab4df981549996fd68d0) - which Isengard doesn't have. So I'd need to rebuild and install Kodi to a later master version as well, which is likely to break something...

Backporting this to Isengard doesn't look trivial either given the number of changes and later code refactoring (e.g. to src/HTSPTypes.h).

Thoughts? I may have the wrong end of the stick or be missing something trivial, of course...

**Comment by ksooo** [comment]
You need a recent Kodi nightly build (Jarvis) and pvr.hts master. Backporting to Isengard is way to much effort.

**Comment by ProfYaffle** [comment]
... which is what I feared.

<time passes> 

Damn, that was harder than I expected...

Jarvis master built. pvr.hts cloned from *add-oneshot-timer-enable-support*, built and installed. Main Isengard installation not broken...

It would seem that it does indeed fix the issue... the recording events are now listed as 'inactive', and they don't show up on the main Confluence screen as the next recording(s) any more.

Thanks.

---

An aside... it's probably something I'm missing, however, and here probably isn't the right place anyway, but... 

It's really hard to get a simple list of upcoming recordings with this Kodi/PVR combination, as you have to look through each individual rule to see if it's matched anything. Deselecting 'group timers' at least lists the events, but still lists all the enabled rules as well - even if they're not matching anything. 

I'd have thought a flag or indicator on the 'group timers' view would be useful - to show that a rule has matched some events and thus is worth drilling into. And when the events aren't grouped by timer, then the timers (rules) themselves shouldn't really be shown, or should be shown separately (i.e. not on the same list). If you like, a "rules view" (with flags to say something's matched) vs an "events view".

Anyway, perhaps still a work in progress on master, or perhaps I've missed something entirely!

Cheers...

**Comment by ksooo** [comment]
> It would seem that it does indeed fix the issue... the recording events are now listed as 'inactive', and they don't show up on the main Confluence screen as the next recording(s) any more.

Cool. Thanks for testing. I will PR the code later today.
