### ISSUE TITLE
Feature: Improvements to Display of Rules/Events

### ISSUE THREAD

**Issue by ProfYaffle** [kodi-pvr/pvr.hts#134]
Picking this up from my comment in issue https://github.com/kodi-pvr/pvr.hts/issues/131...

This could be user error. It could be a work in progress. It could just be me. Feel free to close if it's any of those.

I recently tested Kodi master and a particular pvr.hts (_add-oneshot-timer-enable-support_) branch in ksooo's fork (this is relevant if it's been worked on since).

I noticed that the TV -> Timer view no longer just lists the upcoming events; now, it lists the active recording rules (which you have to drill into to see any upcoming scheduled recordings) plus any one-time (non-rule) events. I can also see that you can deselect "Group timers" and then you'll see the list of timers plus the list of events.

A couple of comments...

1. If you have a lot of rules that aren't currently active, or aren't currently matching anything, they simply get in the way. There's no apparent way to say "only show me active rules that are actually going to record something" vs "show me every rule I've ever defined and not got round to deleting".

2. If you're going to display rules that aren't currently matching an event (either inactive or just not matching), it would be helpful if the ones that *are* matching were flagged in some way. That way, you at least know which ones are worth drilling into to see the underlying events.

3. Deselecting "Group timers" then gives a mixed list. So, while you do now get a decent list of all upcoming events (like the old view), it's still cluttered by rules that might be active, might be inactive, might be matching something, might not be. I'd have thought that the rules should really be on a different screen as you manage them differently to events; if they're going to be here, then they're just headings, and they either need to be seen as such (so sorted as _rule - matching event 1- matching event 2 - rule -(no matching events) - rule - matching event..._) or not displayed at this point.

I'm not sure how clear that is, or even if it's still a current observation - happy to expand if needed (or if I've just missed a config option somewhere...).

Cheers...

**Comment by ksooo** [comment]
This is nothing that can be implemented in pvr.hts. Please use Trac for Kodi core feature requests.

**Comment by ProfYaffle** [comment]
Will do - I assumed it was an addon layout, but obviously wasn't thinking hard enough.

That said, I just read your Series Recording PR (https://github.com/xbmc/xbmc/pull/7079) so I suspect you've absolutely had enough of people telling you what's right or wrong here and am happy to go away if you'd prefer... apologies if I've accidentally wandered into a minefield... :wink:

It looks like the preferred route is for users to log stuff in the forum and then someone else will port over to trac if it's a valid FR.. It seems that I have authority to raise bugs on Trac, but not new Features. I'll take it to the forum.

**Comment by ProfYaffle** [comment]
http://forum.kodi.tv/showthread.php?tid=246980

Closing here...
