### ISSUE TITLE
Reconnect after tvh failure/restart

### ISSUE THREAD

**Issue by dkonerma** [kodi-pvr/pvr.hts#135]
Hi,,

I'm quite sure that pvr.hts has beed quite reliable in re-connection after a tvh failure or restart in the past. Currently (pvr.hts 2.2.9 with tvh 4.1-909~g0a73d7f) this no loinger works.

How to reproduce:
- play a channel with kodi
- stop tvh
- playback stops (paused)
- start tvh
- keeps being paused, tvh UI shows the connection, but no subscription)

On the next channel switch all is working fine again. I would expect that playback resumes automatically.

Thanks in advance
Dietmar.

**Comment by Jalle19** [comment]
Do you remember when this last used to work?

**Comment by dkonerma** [comment]
Unfortunately not... I'm close to bleeding edge for some months now and noticed yesterday by accident. ;-) Do you see the same issue.. wondering if it's just me?

**Comment by Jalle19** [comment]
I'll have to test, I don't normally restart tvheadend or have connection issues so I wouldn't know.

**Comment by stan86** [comment]
Same problem here

**Comment by ksooo** [comment]
Sould be fixed in latest pvr.hts master
