### ISSUE TITLE
Kodi 16 (Jarvis) extra timers appear in EPG

### ISSUE THREAD

**Issue by carpa5** [kodi-pvr/pvr.hts#140]
Using latest (master) of tvheadend. If I use Kodi 15 problem does not appear. If I use Kodi 16 extra timers appear in the EPG that are not in the Kodi timer list. Here is the problem reported by someone else in the kodi forum.

http://forum.kodi.tv/showthread.php?tid=250899

**Comment by Jalle19** [comment]
Can you try an earlier beta/alpha of Kodi and see if it worked back then?

**Comment by carpa5** [comment]
I am running on linux, so I am compiling the addon. The furthest back I could go before running into compile or prerequisite problems was https://github.com/kodi-pvr/pvr.hts/commit/c552a2009aa5450cf763799ed343665372a4cb8a . The problem still persists there.

**Comment by ksooo** [comment]
@carpa5: I don't think that this a problem with the addon. I fear it is a problem with latest tvheadend. Could you please try 4.0.7 and report back the result?

Also, to really understand the problem, relevant screenshots of both tvh web ui and Kodi windows would really be helpful. For mw, it is currently not 100% clear what the actual problem should be.

**Comment by carpa5** [comment]
![kodi16](https://cloud.githubusercontent.com/assets/15996260/11655852/eec3fa86-9d7e-11e5-8c66-13796d3dd884.png)
![tvh-web](https://cloud.githubusercontent.com/assets/15996260/11655853/eec838a8-9d7e-11e5-999d-318c171dcbce.png)

Attached are the pictures. As you can see  in Kodi on CBC from 8:00 to 8:30 three timers are set. These are not being recorded. The first recording on CBC "22 Minutes" which is later in the evening.

As I stated this works fine if I use Kodi 15. I'm not sure I want to revert to 4.07 since I'm not sure if this will screw up my 4.1 settings.

**Comment by ksooo** [comment]
4.1 is unstable software and known to introduce random regressions. So, if you cannot go back to 4.0.7 to check whetehr it is what i suspect, I cannot help you, I'm afraid.

**Comment by ksooo** [comment]
Could you please show me the autorec tab of your tvh web ui?

**Comment by carpa5** [comment]
OK, that's fair. I will do a backup and try 4.0.7.  Thanks for you hard work.

**Comment by carpa5** [comment]
![autorec](https://cloud.githubusercontent.com/assets/15996260/11656712/f09d1c10-9d84-11e5-8d8f-2b9c0654f97e.png)

As requested

**Comment by ksooo** [comment]
Okay, can you find a relation between your CBC autorecs and the three CBC timers diplayed wrong in Kodi?

**Comment by carpa5** [comment]
So are you saying it has to do with the start before/after ?

**Comment by ksooo** [comment]
No, atm trying to find "something" to start with.

So, are there autorec rules for the bogus timers displayed in Kodi?

**Comment by ksooo** [comment]
Unfortunately I cannot see the titles of the events in question in the timer window, thus cannot look for matching autorecs myself. ;-)

**Comment by carpa5** [comment]
No the bogus timers do not appear in Kodi timer table. They are only in the EPG

**Comment by ksooo** [comment]
Sorry, ment the screen shot of your EPG window where I cannot see the titles of the events in question. Argh.

**Comment by carpa5** [comment]
None of those bogus timers are in the TVH autorec tab. Here is one more with more bogus entries I just took now,
![epg2](https://cloud.githubusercontent.com/assets/15996260/11657118/32f07b0e-9d88-11e5-9a39-554e02eeace2.png)

**Comment by ksooo** [comment]
OK, I think I found it. Could be a problem in Kodi core not dealing correct with autorecs with "start" set to "any". 

What happens if you delete "The Romeo Section" CBC autorec entry in tvh web ui (maybe disabling it also is enough? Try delete if disable has no effect, please.)? Do the bogus CBC timers vanish, then?

**Comment by carpa5** [comment]
Yup, that did the trick. If I disable "The Romeo Section", the bogus timers disappear on CBC. If I enable the come back again. Great Detective work !

**Comment by carpa5** [comment]
With the "The Romeo Section" disabled we still get bogus timers between 19:00 and 23:00 on CBC

![epg3](https://cloud.githubusercontent.com/assets/15996260/11657731/a51a53a4-9d8c-11e5-8b81-38e9acd8160c.png)
![tvh-autorec2](https://cloud.githubusercontent.com/assets/15996260/11657730/a519c1a0-9d8c-11e5-9cde-9a4b733e86a8.png)

**Comment by ksooo** [comment]
Cool. Then we can close this issue as it is not related to the addon (and also not to tvh 4.0.7/4.1, btw). I will come up with a PR for kodi core the next days and notify you, then.

Thanks for helping me to find out what's wrong.

**Comment by ksooo** [comment]
Just saw your last comment. Those "bogus" timers are a completely different story, not related to the first bug we digged out. According to your screen shot, the cause of the "problem" for CBC is the "22 Minutes" autorec rule.

Could you please show me the content of the Kodi timer settings dialog for the "22 Minutes" autorec timer?

**Comment by carpa5** [comment]
The last field is "Lifetime = 2000 days"
![22minutes](https://cloud.githubusercontent.com/assets/15996260/11659746/cbb3396c-9d97-11e5-9ac1-877a09a5df8f.png)

**Comment by ksooo** [comment]
lifetime is unrelated.

Not that settings dialog, please. This is the one for a particular recording. You need to find the autorec rule for "22 Minutes" in the timer window. ;-) In the Type column, this one must say "Repeating (Guide-based", not "One-time (...)".

**Comment by ksooo** [comment]
And again, do these "bogus" timers also appear in tvh web ui, tab "upcoming recordings"?

**Comment by carpa5** [comment]
The bogus timers do not appear in upcoming recordings:

![22minutestimer](https://cloud.githubusercontent.com/assets/15996260/11660244/4b22e146-9d9a-11e5-8869-959e6171e62c.png)
![upcommingrecordings](https://cloud.githubusercontent.com/assets/15996260/11660245/4b23f69e-9d9a-11e5-9710-c1e1331e0c23.png)

**Comment by ksooo** [comment]
Argh. Still the wrong timer settings dialog. Close that dialog. Go up using "..". Press "i" (or use the context menu" on the 22 Minutes entry there to open the right timer settings dialog.

**Comment by carpa5** [comment]
Sorry, hope this is what you want:

![22-1](https://cloud.githubusercontent.com/assets/15996260/11660474/44e2f9fa-9d9b-11e5-9104-7122e55a6966.png)
![22-2](https://cloud.githubusercontent.com/assets/15996260/11660475/44e43c2a-9d9b-11e5-910d-9c05054937bc.png)

**Comment by ksooo** [comment]
Thanks, settings looking good. Still no real clue what's going wrong, but I'm pretty sure we will find out. ;-)

**Comment by carpa5** [comment]
If you look at the start/end time it corresponds to the bogus timers between 19:00 and 23:00

**Comment by carpa5** [comment]
Actually after 19:50 does not correspond with 19:00 winch is the first bogus one. Just thinking out loud I guess.

**Comment by carpa5** [comment]
Just a quick note, the TV view always shows the correct next recording and does not display any of the bogus timers.

![nextrecording](https://cloud.githubusercontent.com/assets/15996260/11660917/57c91192-9d9d-11e5-8379-398a924fb218.png)

**Comment by ksooo** [comment]
Yeah, I actually fixed the "next recording widget" some days ago. Was basically the same problem we figured out earlier today, but obviously in the first place I did not find all places where this needs to be fixed.

**Comment by ksooo** [comment]
OK, I think I know what's going on. Do the bogus timers around CBC "22 Minutes" go away if you disable autorec CBC "Murdoch Mysteries"?

**Comment by ksooo** [comment]
More precisely: Do the bogus timers before CBC "22 Minutes" go away if you disable autorec CBC "Murdoch Mysteries" and "Dragon's Den"?

**Comment by carpa5** [comment]
For CBC on Dec 8 between 19:00 and 23:00

If I disable Murdoch Mysteries then all the timers go away  (including 22 minutes), but TVH still has correct up coming recording of 22 minutes
![p1](https://cloud.githubusercontent.com/assets/15996260/11662280/c5893bc0-9da3-11e5-8a91-6696f6ab7aa4.png)


Disabling/Enabling Dragon's Den , Nothing happens

**Comment by ksooo** [comment]
Just doing brain debugging, maybe the one or the other "calculation" was wrong on my end. ;-)

Anyway, I think I now understand what's causing the ghost timers and have an idea how to fix thud in Kodi core.

Do you know how to use git to cherry pick from another ones repo and how to build your own Kodi?

**Comment by carpa5** [comment]
I am currently building Kodi from "Jarvis" branch, but I have not done cherry pick. Maybe if you send me some brief instructions I can try.

**Comment by ksooo** [comment]
Could you please apply this patch http://paste.ubuntu.com/13832093/ to your "Jarvis" branch and report back? I was able to reproduce the problems and for me this patch fixes things.

**Comment by carpa5** [comment]
Just applied the patch and everything looks good ! I do not see any more bogus timers.

**Comment by ksooo** [comment]
@carpa5 cool. Thanks for your cooperation. Please close this issue.

**Comment by carpa5** [comment]
@ksooo , no problem glad to help. I am impressed with you quick resolve.
