### ISSUE TITLE
Gui bump missing 

### ISSUE THREAD

**Issue by MartijnKaijser** [kodi-pvr/pvr.hts#141]

**Comment by ksooo** [comment]
Not hundred percent sure, but I think a simple recompile of pvr.hts (and all other addons not having explicit \<import addon="kodi.guilib" version="x.y.z"/> tag in addon.xm.in) will do the trick. AT least that fixed the incompatbilty for me. And as there was a transifex update including addon version bump yesterday this will even be fixed without any further action.

**Comment by MilhouseVH** [comment]
> And as there was a transifex update including addon version bump yesterday this will even be fixed without any further action.

Yep, this now seems to be fixed ([forum post](http://forum.kodi.tv/showthread.php?tid=238393&pid=2182251#pid2182251)). Kinda feels a bit random, though - shouldn't the add-on be explicit about the version of `kodi.guilib` it requires?

**Comment by ksooo** [comment]
TBH, I don't get how this is supposed to work.

On the one hand, the version can be defined in addon.xml.in, on the other hand it must be (hard)coded into addon functions like GetGUIAPIVersion.

pvr.hts does not even depend on kodi.guilib, therefore not putting a dependency into addon.xml.in seems okay, but according to https://github.com/kodi-pvr/pvr.hts/commit/254b4e29b246ee9896d3673e7dd350f7a5e411f4, one must supply an implementation for GetGUIAPIVersion and the docs do not specify a "no guilib needed" return value...

**Comment by MartijnKaijser** [comment]
confusing......
