### ISSUE TITLE
Add support for updating autorecs/timerecs (htsp api v25)

### ISSUE THREAD

**Issue by Glenn-1990** [kodi-pvr/pvr.hts#143]
Htsp api 25 adds support for updating timerecs and autorecs.

Currently pvr.hts will delete the autorec and recreate a new one on update.
In this way, all fields that are not available through the htsp interface are reset back to it's default, that's not desired ofc. We should support real updating now.

**Comment by ksooo** [comment]
+1 for this

**Comment by Glenn-1990** [comment]
support for htspv25 is in master now
