### ISSUE TITLE
kodi-pvr (latest git master) doesn't compile because of renaming of namespace PLATFORM to P8PLATFORM

### ISSUE THREAD

**Issue by PhobosK** [kodi-pvr/pvr.hts#149]
[libplatform] (http://www.github.com/Pulse-Eight/platform) changed their namespace from POLATFORM to P8PLATFORM ( Pulse-Eight/platform@cce6a497d63c436d770e5099f338e2bfb7aa369f ), so now kodi-pvr doesn't compile and needs update on that...

**Comment by MartijnKaijser** [comment]
it does compile. Just don' t use latest libplatform

**Comment by PhobosK** [comment]
Hmmm...
Thanks Martijn :)
And yeah, I know how kodi-pvr will compile..... ;)

But that was not my point... My point is that because this is kodi-pvr git master... maybe there are a lot of users that test/use/etc all latest code from git master of kodi, kodi-platform, platform, kodi-pvr etc... at some point the transition to the new namespace P8PLATFORM should happen....

Right now the kodi-pvr code is stuck with libplatform up to Pulse-Eight/platform@2c8d36effd44b0fee717112c5f62a479a6f3a897

Anyway... maybe it is my fault that I expect this git master to be in sync with all the changes of the other gits... but I'm just trying to be helpful here... Disregard this issue if you should...

Thanks

**Comment by Jalle19** [comment]
Another addon got a fix for the Debian packaging part of this, but have the header names changed too?

**Comment by Jalle19** [comment]
Master compiles again

**Comment by boospy** [comment]
Hello, 

think i have the same problem. I have installed kodi 15.2 on Gentoo. The vnsi-clientplugin's api is to old, so i would like to compile it myself.  I get this error:

`[ 72%] Completed 'kodi-platform'
[ 72%] Built target kodi-platform
Scanning dependencies of target pvr.vdr.vnsi
[ 75%] Creating directories for 'pvr.vdr.vnsi'
[ 78%] No download step for 'pvr.vdr.vnsi'
[ 84%] No patch step for 'pvr.vdr.vnsi'
[ 84%] No update step for 'pvr.vdr.vnsi'
[ 87%] Performing configure step for 'pvr.vdr.vnsi'
CMake Error at CMakeLists.txt:11 (find_package):
  By not providing "Findp8-platform.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "p8-platform", but CMake did not find one.

  Could not find a package configuration file provided by "p8-platform" with
  any of the following names:

    p8-platformConfig.cmake
    p8-platform-config.cmake

  Add the installation prefix of "p8-platform" to CMAKE_PREFIX_PATH or set
  "p8-platform_DIR" to a directory containing one of the above files.  If
  "p8-platform" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "/root/vnsiclient-kodi.15/pvr.vdr.vnsi/CMakeFiles/CMakeOutput.log".
CMakeFiles/pvr.vdr.vnsi.dir/build.make:106: die Regel für Ziel „pvr.vdr.vnsi-prefix/src/pvr.vdr.vnsi-stamp/pvr.vdr.vnsi-configure“ scheiterte
make[2]: *** [pvr.vdr.vnsi-prefix/src/pvr.vdr.vnsi-stamp/pvr.vdr.vnsi-configure] Fehler 1
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/pvr.vdr.vnsi.dir/all“ scheiterte
make[1]: *** [CMakeFiles/pvr.vdr.vnsi.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
`
So what i have to do to fix this. 

Thanks a lot

**Comment by Jalle19** [comment]
Make sure you compile the master branch for both Kodi and the addon.

**Comment by boospy** [comment]
oh... my fault sorry. I had the wrong branch. Installed kodi 15.2 in Gentoo from Portage. I loaded the Isengard branch and vor the vnsi-client it compiles fine :+1:
