### ISSUE TITLE
Read only timers

### ISSUE THREAD

**Issue by Glenn-1990** [kodi-pvr/pvr.hts#150]
Is it needed to use read only timers? 
User example 1) I added a repeating rule for a show running every evening. 
I'm able to watch this show today, so I want to cancel the timer for this evening, but... this is not possible, I can only delete the complete schedule?
I have to use the tvh webui to handle this case.

User example 2) I have one tuner and am watching live tv, a repeating timer starts recording and interrupts the live stream, so I want to cancel that active recording to allow me watching live tv, this is not possible... Even more, the stop recording button is listed, but doesn't work.

I think canceling a read only timer is possible for tvh 4.1, but maybe we have to handle tvh 4.0 not as read only?

stop recording listed, but not working
![schermafdruk van 2015-12-21 15 14 29](https://cloud.githubusercontent.com/assets/2036512/11932592/e8fe19ec-a7f6-11e5-9640-3fbd1e518ece.png)

unable to cancel a timer which I'll watch in prime time
![schermafdruk van 2015-12-21 15 15 26](https://cloud.githubusercontent.com/assets/2036512/11932737/d3c298d6-a7f7-11e5-8f6e-7563d734eddc.png)

I didn't investigate yet where the problem lies (kodi or pvr.hts), but we should fix this for Jarvis is out.
@ksooo @Jalle19

**Comment by ksooo** [comment]
Case 1 is tricky. IIRC tvh 4.0 does not handle deleting of a timer scheduled by an autorec correctly, although it is possible using the webui. Former or later (latest on tvh restart), the formerly deleted child of the autorec gets automatically recreated by tvh. Not sure whether this was fixed for 4.1.

Fix for case 2 (stop recording not working) is trivial. Will come up with a PR for kodi core. Not a pvr.hts problem.

**Comment by ksooo** [comment]
Just discovered that for case 2 a pvr.hts fix is needed, in addition to a kodi core fix. Will PR both fixes soon. :-(

**Comment by Glenn-1990** [comment]
![schermafdruk van 2015-12-22 12 20 22](https://cloud.githubusercontent.com/assets/2036512/11954153/84b3b144-a8a6-11e5-9e66-fa6b4ebe1146.png)

Updating the active flag is not possible for tvh 4.1, we need the same fix here?

**Comment by Glenn-1990** [comment]
It's not possible to disable a read only timer in the guide window, not button is showed, maybe we can add a "disable timer" button or just the "delete timer"?
When using "delete timer" for read only timers, the client should detect this and do a disable instead of delete.
![schermafdruk van 2015-12-22 12 25 48](https://cloud.githubusercontent.com/assets/2036512/11954279/7e3959d0-a8a7-11e5-99b7-66162f27864e.png)

**Comment by ksooo** [comment]
> Updating the active flag is not possible for tvh 4.1, we need the same fix here?

 Yes, seems to be the case. UpdateTimer needs to be able to handle this case. I will PR this asap.

**Comment by Glenn-1990** [comment]
thanks @ksooo for fixing this, closing
