### ISSUE TITLE
Suggestion for manual timers

### ISSUE THREAD

**Issue by Glenn-1990** [kodi-pvr/pvr.hts#160]
Currently when a user adds an advanced timer through an epg event (tv guide for example), there are 4 options.
1) one time
2) one time (guide-based)
3) repeating 
4) repeating (guide-based)

Would it make sense to remove option 1) and 3) here as this might confuse the user?
Also (guide-based) could be renamed to (epg-match), what do you guys think? It's just a suggestion ;-)

@Jalle19 @ksooo

**Comment by Jalle19** [comment]
What does option 1) and 3) do?

**Comment by Glenn-1990** [comment]
Option 1) and 3) are just manual timers created from the epg start and stop times, so they will still record even if the show was cancelled, moved from time, etc. So it's safer to use epg based timers when epg is available.

**Comment by ksooo** [comment]
"EPG" in the UI is not an option (any more). There was decided that "EPG" is to technical for everage Joe. "Guide" or "TV Guide" (where context is not clear enaough) has to be used. 

Removing 1) and 3) is not an option, as "Add timer" is supposed to always provide all user-creatable timer types to the user. User might want to start with an epg event, but for whatever reason then decides to make a manual timer (or manual timer rule) based on the data prefilled by the underlying epg event.

**Comment by Jalle19** [comment]
> "EPG" in the UI is not an option (any more). There was decided that "EPG" is to technical for everage Joe. "Guide" or "TV Guide" (where context is not clear enaough) has to be used.

Agreed

**Comment by Glenn-1990** [comment]
@ksooo Good point, but maybe it's possible to make clear that the other timers are manual? 
Or maybe it's possible to sort the list, so the preferred (epg based when created from epg event) types listed on place 1 and 2 followed by the manual ones?
