### ISSUE TITLE
PVR Addon API 4.2.0

### ISSUE THREAD

**Issue by ksooo** [kodi-pvr/pvr.hts#173]
Now, that https://github.com/xbmc/xbmc/pull/8896 got merged, we need to implement changes for PVR Addon API 4.2.0. Currently pvr.hts master addon is broken, due to API version mismatch.

@FernetMenta How to implement the new API function for pvr.hts? pvr.hts has its own demuxer as you know... So, is it just <code>return true</code> in all cases, even if there is no "current stream"?

**Comment by FernetMenta** [comment]
@ksooo I don't know how tvh handles recordings. vnsi will return true for IsRealTimeStream if:

- live tv and timeshift is not active
- live tv with timeshift and playing pos is closer than 10sec to the end of buffer

**Comment by ksooo** [comment]
@FernetMenta thanks for the info

@Jalle19 you are much more familiar with our demuxer than I. Would be great if you could take over this task?!

**Comment by Jalle19** [comment]
@FernetMenta recordings are served using the VFS, they could be considered real-time if the playback position is close to the actual live position. I'll have to look into how we can determine this.

@ksooo I'm quite busy the whole week but I'll try to take a look. Having broken addons in master pre-alpha isn't the end of the world IMO (obviously we should fix this ASAP though).

**Comment by vindicatorr** [comment]
Is this why I'm getting
```
ERROR: Unable to load /home/user/.kodi/addons/pvr.hts/pvr.hts.so.3.0.0, reason: /home/user/.kodi/addons/pvr.hts/pvr.hts.so.3.0.0: undefined symbol: IsRealTimeStream
```
I was just trying to update kodi and pvr.hts (and everything in-between) and just got this error.
Should a stub be put in or should I just revert to a commit before 3 days ago?

**Comment by Jalle19** [comment]
The latter for now.

**Comment by Jalle19** [comment]
Recently implemented, closing this
