### ISSUE TITLE
HTTP 401 when using credentials not defined in backend.

### ISSUE THREAD

**Issue by mpmc** [kodi-pvr/pvr.hts#176]
+Description+

Catch all account enabled to allow any user/pass access to all features set in Tvheadend.
Dummy user and pass set in pvr.hts kodi addon.

+Issue+

Using the above configuration the imagecache results in a 401 error when pvr.hts requests icons using the dummy account not defined in Tvheadend. If you add the dummy account to Tvheadend and reconnect the icons are served correctly.

See: https://tvheadend.org/issues/3519

**Comment by Jalle19** [comment]
Never thought of this possibility, I'll look into it.

**Comment by Jalle19** [comment]
Does it work if you leave username/password empty in the addon settings?

**Comment by Jalle19** [comment]
As discussed on IRC, users should leave username and password empty if they have configured tvheadend with a "catch all" account. Changing the behavior would require changes in Kodi itself.
