### ISSUE TITLE
Unable to start addon

### ISSUE THREAD

**Issue by lwis** [kodi-pvr/pvr.hts#18]
I'm running the latest nightlies, my logs look like;

```
11:43:00 T:140327486932736  NOTICE: Thread JobWorker start, auto delete: true
11:43:10 T:140327226689280  NOTICE: Autoconfigure - auto-configured Tvheadend using host 'IP:9799' and port '9982'
11:43:13 T:140327226689280   ERROR: Unable to load /usr/lib/kodi/addons/pvr.hts/pvr.hts.so, reason: /usr/lib/kodi/addons/pvr.hts/pvr.hts.so: undefined symbol: hts_sha1_size
11:43:13 T:140327226689280 WARNING: UpdateAndInitialiseClients - failed to create add-on Tvheadend HTSP Client, status = 6
11:43:13 T:140327226689280 WARNING: UpdateAndInitialiseClients - failed to load the dll for add-on Tvheadend HTSP Client, disabling it
11:43:13 T:140328626710272  NOTICE: Thread AddonStatus pvr.hts start, auto delete: true
11:43:18 T:140326782072576  NOTICE: Thread JobWorker start, auto delete: true
11:45:09 T:140327486932736  NOTICE: Previous line repeats 1 times.
```

**Comment by hudokkow** [comment]
Thanks for the report but this is a dev only space.

Please post at http://forum.kodi.tv/forumdisplay.php?fid=168

**Comment by Jalle19** [comment]
Might as well use this issue tracker, it's a PITA to follow bug reports on the forum.

**Comment by hudokkow** [comment]
Guess it makes sense. Wrongly assumed things would work as kodi-core.

**Comment by EricV** [comment]
Opened a bug via kodi trac and were said that it has been decided to use bug tracking here????
I'm confused

**Comment by Jalle19** [comment]
That's right, bugs in this addon should be reported here from now on.

**Comment by Jalle19** [comment]
@lwis your hostname is at least incorrect, can you fix that and get a new debug log if you still have problems?

**Comment by lwis** [comment]
@Jalle19 Hostname was purposely redacted. If I can provide any further information, please let me know. Looking at the forums it seems like I'm not alone with this problem.

Also it's probably worth noting that I'm running xbmcbuntu.

**Comment by ksooo** [comment]
<code>/usr/lib/kodi/addons/pvr.hts/pvr.hts.so: undefined symbol: hts_sha1_size</code>

Looks, your addon is linked dynamically against libhts and that the sahred lib is present on your system, but does not provide the required symbol. This is strange, as libhts is supposed to be linked statically. https://github.com/kodi-pvr/pvr.hts/blob/master/lib/libhts/CMakeLists.txt#L24 Did you build the addon that produced the above error by yourself and if so, how? If not, where do you got it from?

Could you give us the output of "ldd -r /usr/lib/kodi/addons/pvr.hts/pvr.hts.so", please.

**Comment by lwis** [comment]
Add-on was always obtained from the launchpad PPA.

```       linux-vdso.so.1 =>  (0x00007ffff0d57000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
(0x00007f2a3a3ce000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(0x00007f2a3a0bf000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
(0x00007f2a39ea7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2a39ae3000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2a3a832000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2a397dd000)
undefined symbol: hts_sha1_size (/usr/lib/kodi/addons/pvr.hts/pvr.hts.so)
undefined symbol: htsmsg_get_map        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: hts_sha1_init (/usr/lib/kodi/addons/pvr.hts/pvr.hts.so)
undefined symbol: htsmsg_binary_serialize
(/usr/lib/kodi/addons/pvr.hts/pvr.hts.so)
undefined symbol: htsmsg_get_s64        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: htsmsg_binary_deserialize
(/usr/lib/kodi/addons/pvr.hts/pvr.hts.so)
undefined symbol: htsmsg_get_str        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: htsmsg_add_u32        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: htsmsg_get_list       (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: hts_sha1_update       (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: htsmsg_add_str        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: dlsym (/usr/lib/kodi/addons/pvr.hts/pvr.hts.so)
undefined symbol: htsmsg_add_bin        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: hts_sha1_final        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: htsmsg_add_s32        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: dlerror       (/usr/lib/kodi/addons/pvr.hts/pvr.hts.so)
undefined symbol: htsmsg_destroy        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: htsmsg_get_u32_or_default
(/usr/lib/kodi/addons/pvr.hts/pvr.hts.so)
undefined symbol: htsmsg_create_map     (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: htsmsg_get_u32        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: htsmsg_add_s64        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: dlopen        (/usr/lib/kodi/addons/pvr.hts/pvr.hts.so)
undefined symbol: htsmsg_get_bin        (/usr/lib/kodi/addons/pvr.hts/
pvr.hts.so)
undefined symbol: dlclose       (/usr/lib/kodi/addons/pvr.hts/pvr.hts.so)```
On 20 Mar 2015 3:40 pm, "Kai Sommerfeld" <notifications@github.com> wrote:

> /usr/lib/kodi/addons/pvr.hts/pvr.hts.so: undefined symbol: hts_sha1_size
>
> Looks, your addon is linked dynamically against libhts and that the sahred
> lib is present on your system, but does not provide the required symbol.
> This is strange, as libhts is supposed to be linked statically.
> https://github.com/kodi-pvr/pvr.hts/blob/master/lib/libhts/CMakeLists.txt#L24
> Did you build the addon that produced the above error by yourself and if
> so, how? If not, where do you got it from?
>
> Could you give us the output of "ldd -r /usr/lib/kodi/addons/pvr.hts/
> pvr.hts.so", please.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kodi-pvr/pvr.hts/issues/18#issuecomment-84051775>.
>

**Comment by ksooo** [comment]
Yeah, it's what I thought. Blame the packagers. 

They have to either link pvr.hts.so statically against libhts (like the always did in the past, I think) or to build and deliver libhts.so together with pvr.hts.so

Please file a bug against those guys. Whoever they are... :-/

Btw: the problem reported in the forum was different.

**Comment by lwis** [comment]
@ksooo ah, okay. Thanks for taking a look for me, where would be the best place for me to raise an issue? (I don't even know where to start)

**Comment by wsnipex** [comment]
"those guys" are you ;) https://github.com/kodi-pvr/pvr.hts/tree/master/debian

**Comment by wsnipex** [comment]
ok, just checked our ubuntu package and its fine:
/usr/lib/kodi/addons/pvr.hts$ ldd pvr.hts.so.2.1.6 
	linux-vdso.so.1 =>  (0x00007ffe21ff6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3ef81d8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3ef7ec9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3ef7cb1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3ef78ec000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3ef864c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3ef75e6000)

**Comment by ksooo** [comment]
Then we have  the thing that cannot be?  @Iwis uses our packages, which are okay, but obviously the packages he uses are not okay? Clueless...

**Comment by lwis** [comment]
I just tried purging the package in fear that something had broken on install, but it's still borked.

**Comment by ksooo** [comment]
@wsnipex hehe, did not known about the Deboan packaging we are doing, sorry. Thanks for pointing that out.

**Comment by wsnipex** [comment]
@lwis, please:
apt-cache policy kodi-pvr-hts

Note that the only package I tried is current master from the nightly ppa: https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly

**Comment by lwis** [comment]
@wsnipex 

```
kodi-pvr-hts:
  Installed: 2.1.6-1~utopic
  Candidate: 2.1.6-1~utopic
  Version table:
 *** 2.1.6-1~utopic 0
        500 http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu/ utopic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by wsnipex** [comment]
no idea..
wuff@uboook:~$ readelf -a /usr/lib/kodi/addons/pvr.hts/pvr.hts.so | grep hts
 0x000000000000000e (SONAME)             Library soname: [pvr.hts.so.15.0]
   112: 000000000001ba00    45 FUNC    GLOBAL DEFAULT   11 htsmsg_create_map
   149: 000000000001ba80   110 FUNC    GLOBAL DEFAULT   11 htsmsg_delete_field
   153: 0000000000026ff4     4 OBJECT  GLOBAL DEFAULT   13 hts_sha1_size
   176: 000000000001c740   120 FUNC    GLOBAL DEFAULT   11 htsmsg_get_bin
   177: 0000000000021730    25 FUNC    GLOBAL DEFAULT   11 htsmsg_add_s32
   209: 000000000001e4d0   174 FUNC    GLOBAL DEFAULT   11 htsmsg_get_float
   217: 0000000000021440    60 FUNC    GLOBAL DEFAULT   11 htsmsg_add_msg_extname
   220: 000000000001e4a0    43 FUNC    GLOBAL DEFAULT   11 hts_sha1_init
   236: 000000000001e280   210 FUNC    GLOBAL DEFAULT   11 hts_sha1_update
   238: 000000000001bb60   131 FUNC    GLOBAL DEFAULT   11 htsmsg_binary_serialize
   239: 000000000001a4c0    85 FUNC    GLOBAL DEFAULT   11 htsmsg_get_list
   243: 000000000001a580   234 FUNC    GLOBAL DEFAULT   11 htsmsg_get_map_multi
   244: 000000000001eaa0    63 FUNC    GLOBAL DEFAULT   11 htsmsg_detach_submsg
   245: 00000000000214c0    42 FUNC    GLOBAL DEFAULT   11 htsmsg_add_binptr
   246: 000000000001b9d0    45 FUNC    GLOBAL DEFAULT   11 htsmsg_create_list
   267: 0000000000021770    26 FUNC    GLOBAL DEFAULT   11 htsmsg_add_u32
   268: 000000000001eae0    41 FUNC    GLOBAL DEFAULT   11 htsmsg_add_float
   279: 000000000001c6d0   102 FUNC    GLOBAL DEFAULT   11 htsmsg_field_get_string
   280: 000000000001eb10    58 FUNC    GLOBAL DEFAULT   11 htsmsg_copy
   302: 0000000000021750    25 FUNC    GLOBAL DEFAULT   11 htsmsg_add_s64
   303: 000000000001d470    63 FUNC    GLOBAL DEFAULT   11 htsmsg_get_s32
   304: 0000000000021480    63 FUNC    GLOBAL DEFAULT   11 htsmsg_add_msg
   305: 000000000001baf0   110 FUNC    GLOBAL DEFAULT   11 htsmsg_field_add
   312: 0000000000021530    46 FUNC    GLOBAL DEFAULT   11 htsmsg_add_str
   335: 000000000001e360   319 FUNC    GLOBAL DEFAULT   11 hts_sha1_final
   340: 000000000001e580   368 FUNC    GLOBAL DEFAULT   11 htsmsg_print
   357: 000000000001a520    85 FUNC    GLOBAL DEFAULT   11 htsmsg_get_map
   362: 000000000001c7c0    40 FUNC    GLOBAL DEFAULT   11 htsmsg_get_u32_or_default
   375: 00000000000214f0    62 FUNC    GLOBAL DEFAULT   11 htsmsg_add_bin
   393: 00000000000207d0    55 FUNC    GLOBAL DEFAULT   11 htsmsg_get_u32
   395: 000000000001b530    87 FUNC    GLOBAL DEFAULT   11 htsmsg_destroy
   413: 000000000001ba30    76 FUNC    GLOBAL DEFAULT   11 htsmsg_binary_deserialize
   424: 0000000000020710   178 FUNC    GLOBAL DEFAULT   11 htsmsg_get_s64
   429: 0000000000022f40    78 FUNC    GLOBAL DEFAULT   11 htsmsg_get_str

**Comment by lwis** [comment]
0x000000000000000e (SONAME)             Library soname: [pvr.hts.so.15.0]
00000022cf30  002100000006 R_X86_64_GLOB_DAT 0000000000000000 hts_sha1_size + 0
00000022d018  000200000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_get_map + 0
00000022d020  000300000007 R_X86_64_JUMP_SLO 0000000000000000 hts_sha1_init + 0
00000022d030  000500000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_binary_serializ + 0
00000022d058  000b00000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_get_s64 + 0
00000022d078  000f00000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_binary_deserial + 0
00000022d0b0  001700000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_get_str + 0
00000022d0c0  001900000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_add_u32 + 0
00000022d100  002200000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_get_list + 0
00000022d110  002400000007 R_X86_64_JUMP_SLO 0000000000000000 hts_sha1_update + 0
00000022d128  002700000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_add_str + 0
00000022d160  002f00000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_add_bin + 0
00000022d178  003300000007 R_X86_64_JUMP_SLO 0000000000000000 hts_sha1_final + 0
00000022d190  003600000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_add_s32 + 0
00000022d1d0  004000000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_destroy + 0
00000022d230  004c00000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_get_u32_or_defa + 0
00000022d240  004f00000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_create_map + 0
00000022d290  005a00000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_get_u32 + 0
00000022d298  005b00000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_add_s64 + 0
00000022d368  007900000007 R_X86_64_JUMP_SLO 0000000000000000 htsmsg_get_bin + 0
     2: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_get_map
     3: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND hts_sha1_init
     5: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_binary_serialize
    11: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_get_s64
    15: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_binary_deserialize
    23: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_get_str
    25: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_add_u32
    33: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND hts_sha1_size
    34: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_get_list
    36: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND hts_sha1_update
    39: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_add_str
    47: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_add_bin
    51: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND hts_sha1_final
    54: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_add_s32
    64: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_destroy
    76: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_get_u32_or_default
    79: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_create_map
    90: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_get_u32
    91: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_add_s64
   121: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND htsmsg_get_bin

**Comment by xhaggi** [comment]
@lwis please use pastebin for logs etc.

**Comment by wsnipex** [comment]
mind showing what command you use exactly to produce that?

**Comment by lwis** [comment]
`readelf -a /usr/lib/kodi/addons/pvr.hts/pvr.hts.so | grep hts` same as what you executed.

**Comment by wsnipex** [comment]
well, I just purged and redownloaded kodi-pvr-hts and readelf still shows all symbols just fine.
I can't runtime test it though. Can anyone else try the ppa package?

**Comment by hudokkow** [comment]
Fresh install, can't runtime test it.

http://pastebin.com/ffTBCnVJ

**Comment by lwis** [comment]
So my readelf output looks like @hudokkow's, but he's unable to test.

**Comment by ksooo** [comment]
Did a runtime check with latest nightly build on Ubuntu 14.04 (x86_64). No problem. Works just fine.

readelf output ksooo, wsnipex:
153: 0000000000026ff4     4 OBJECT  GLOBAL DEFAULT   13 hts_sha1_size
readelf output Iwis, huddokow:
33: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND hts_sha1_size

I'm not an expert on this, but there is a difference, right?

4 vs. 0 => size of the symbol
OBJECT vs. NOTYPE => symbol type
13 vs. UND =>  The section number the symbol is in.

There is something wrong with the shared lib of Iwis and huddokow... bus as I said I'm not an expert an elf and linker stuff, sorry.

**Comment by EricV** [comment]
I just finished rebuilding everything from scratch, using external tree build for kodiplatform and pvr.hts and it does not load for a diffrenet reason whereas using the fernetmenta provided script to install inside kodi and make it installed when installed via kodi install it works. The reason being that when specifying no install dir to kodiplatform cmake, it install the library in /usr/local/lib/x86_64-linux-gnu/libkodiplatform.so.15.0 but that the dynamic linker only search in /usr/local/lib on debian NOT /usr/local/lib/x86_64-linux-gnu. kinker does search in /usr/lib/x86_64-linux-gnu.

SECTION:LoadDLL(/usr/local/lib/kodi/addons/pvr.hts/pvr.hts.so)
18:36:47 T:140289175963392   DEBUG: Loading: /usr/local/lib/kodi/addons/pvr.hts/pvr.hts.so
18:36:47 T:140289175963392   ERROR: Unable to load /usr/local/lib/kodi/addons/pvr.hts/pvr.hts.so, reason: libkodiplatform.so.15.0: cannot open shared object file: No such file or directory
18:36:47 T:140289175963392    INFO: Called Add-on status handler for '4' of clientName:Tvheadend HTSP Client, clientID:pvr.hts (same Thread=no)
18:36:47 T:140289175963392 WARNING: UpdateAndInitialiseClients - failed to create add-on Tvheadend HTSP Client, status = 6
18:36:47 T:140289175963392 WARNING: UpdateAndInitialiseClients - failed to load the dll for add-on Tvheadend HTSP Client, disabling it
18:36:47 T:140289895589632  NOTICE: Thread AddonStatus pvr.hts start, auto delete: true

/usr/local$ find . -name libkodiplatform.so.15.0
find: "./lost+found": Permission non accordée
./lib/x86_64-linux-gnu/libkodiplatform.so.15.0

**Comment by ksooo** [comment]
@EricV the problem you describe is unrelated to the problem @Iwis has, although the effect is the same.

@Iwis seems to have a broken pvr.hts.so. (somehow not built correctly)

Your problem is a broken installation => reason: libkodiplatform.so.15.0: cannot open shared object file: No such file or directory. I do not understand what exactly you did (build ans install) but the result is a broken insatllation as a shared library cannot be found.

**Comment by EricV** [comment]
@ksooo . I know the problem is not the same I even write it myself. Result is indeed the same and the installation is broken because the kodiplatorm installation is broken because of wrong installation place by default. But it does affect your plugin. ANd please read the post entirely. The reason and the solution is mentionned.

**Comment by ksooo** [comment]
@EricV Well, sure pvr.hts is affected, and yes, I red your entire post.  But as you wrote it is a problem with kodiplatform build/installation. My point was that I cannot help here because I simply have no knowledge about that area of kodi. Maybe @FernetMenta can help?

**Comment by wsnipex** [comment]
@EricV its up to you to pass the correct CMAKE_INSTALL_PREFIX when building.
cmake -DCMAKE_INSTALL_PREFIX=/usr

**Comment by EricV** [comment]
@wsnipex Wrong. By default all the rest in installed in /usr/local. I install in /usr only packages... ANd passing /usr/local would result in same error.

**Comment by ksooo** [comment]
@EricV https://github.com/xbmc/kodi-platform/commit/48bdd985b843353eec5804e4dbab2dc8f2b4b13e should fix this, right?

**Comment by EricV** [comment]
No time to test it just yet but reading the diff, it indeed fixes the root cause: multiarch install should only be used if prefix=/usr

**Comment by lwis** [comment]
I can test when the next nightly is built.

**Comment by ksooo** [comment]
@Iwis sure, but I think this will not fix your issue as it has a different root cause, I'm afraid.

**Comment by ksooo** [comment]
@EricV you're welcome.

**Comment by EricV2** [comment]
@ksooo NB: the fix is correct but  incomplete because install script also lacks a call to ldconfig after library install (this is done when installing via packages by package installation scripts). Even if installed at the correct location pwr.hts still fails to load. Running ldconfig corrects the problem.

**Comment by wsnipex** [comment]
feel free to build a package, we even ship proper debian packaging. We're not going to add ldconfig to our code.

**Comment by EricV2** [comment]
@wsnipex I will use packaging when it will be proposed by debian itself that is not tomorrow as you surely know ffmpeg being not even back in. For my understanding what is the problem of adding a ldconfig at install time for kodiplatform  (yes the ldconfig suggestion is not for this package why should it be?)

**Comment by lwis** [comment]
What would be the best course of action for me to get the nightlies working again? As I'm under the impression this is an edge case.

**Comment by wsnipex** [comment]
mind giving http://members.a1.net/wsnipex/kodi-pvr-hts_2.1.6-2~utopic_amd64.deb a try?
It seems there is a bug in binutils in utopic that breaks LTO linking.

**Comment by lwis** [comment]
That seems to have fixed it, thanks!
