### ISSUE TITLE
Branch / Tag information in README.md

### ISSUE THREAD

**Issue by feddischson** [kodi-pvr/pvr.hts#187]
It would be nice if the README.md provides some information about the release management. 

At least the fact, that `branches/Isengard` shall be used for Kodi's Isengard release and that there are no dedicated tags.

**Comment by Jalle19** [comment]
Okay, I guess we can add that. I've started tagging releases but don't know if I pushed the tags yet or not.

**Comment by feddischson** [comment]
Yes, having the tags might be the most intuitive solution.

**Comment by Jalle19** [comment]
Just added a paragraph to the README and I've tagged the latest Krypton releases (will tag `2.2.13` once the most recent fix has been merged).
