### ISSUE TITLE
New problems with timeshift in latest master/Jarvis

### ISSUE THREAD

**Issue by ksooo** [kodi-pvr/pvr.hts#188]
Using pvr.hts Jarvis with latest timeshift fixes from @perexg and unpatched tvh 4.0.8. Running now in several new trouble when seeking (timeshifting) while watching Live TV. Always getting log entries like:
 
11:35:25 T:140537336149760   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to get subscriptionSeek response
11:35:25 T:140537336149760 WARNING: error while seeking

 and picture freezes. Have to stop and restart the channel to fix.

 Most of the bugs are difficult to reproduce. But one is 100% reproducable. While watching Live TV change audio track (which in fact does a seek). 

@perexg would be great if you could investigate into this.

**Comment by ksooo** [comment]
... or is the cause https://github.com/kodi-pvr/pvr.hts/pull/180/files#diff-fc67c1aab2e0d4a225199143a1d4be69R170 ? Just guessing, because it is around the failing htsp method call.

**Comment by ksooo** [comment]
No, removing the mutex before "subscriptionseek" call does not help.

**Comment by ksooo** [comment]
... but reverting #155 fixes my problems. :-/

**Comment by Jalle19** [comment]
How long does it take after you trigger the seek until you get the "subscriptionSeek failed" message? Does it look like the `Wait()` call returns immediately?

**Comment by Jalle19** [comment]
Think I see the problem, must be a merge issue when I did the Jarvis PR. Stand by...

**Comment by Jalle19** [comment]
@ksooo please try https://github.com/kodi-pvr/pvr.hts/pull/189

**Comment by ksooo** [comment]
Nope. As I said I tried with ad without that mutex. Makes no difference. Problem is definitely caused by by @perexg timeshift PR. If I completely revert #155 my problems are solved.

**Comment by ksooo** [comment]
Here are two log snippets (in one file), first for working audio track switch with perexg changes reverted, second for failing track switch (freeze) with perexg changes applied. http://paste.ubuntu.com/14800426/

**Comment by perexg** [comment]
@ksoo : could you provide debug for pvr.hts for both working / non-working code. But I guess that 4.0.8 has wrong replies to the seek request - it was ignored before.

**Comment by Jalle19** [comment]
I think I'm still on 4.0.7, I'll try again later. Wasn't able to reproduce this with #189 though.

**Comment by ksooo** [comment]
@Jalle19 so do you have absolutely no timeshifting problems with Jarvis RC + latest pvr.hts Jarvis + tvh 4.0.7?

For me, things really got worse with #155 applied. I have definitely more problems than before with no changes in tvh (always 4.0.8) or Kodi (always Jarvis RC). Large periods of freezes on seeking but with no real pattern (at least I see none), sometimes suddenly things go on more or less then, or they don't at all.

**Comment by ksooo** [comment]
@perexg  

11:35:25 T:140537336149760 ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to get subscriptionSeek response

https://github.com/kodi-pvr/pvr.hts/blob/master/src/HTSPDemuxer.cpp#L174

Doesn't this mean that there is no response at all, at least not before response timeout?

**Comment by perexg** [comment]
@ksoo : the timeshift is 4.x is broken .... you just hit more or less bugs.. and no - I'm not able to backport changes from 4.1 because almost everything was changed.. let see if I can provide a little fix only

**Comment by ksooo** [comment]
> I'm not able to backport changes from 4.1

 yeah I understand that

> let see if I can provide a little fix only

 that would be great

**Comment by perexg** [comment]
> 11:35:25 T:140537336149760 ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to get subscriptionSeek response

provide logs I asked, but it seems that there's no seek response from tvh or the response is invalid.. as I said - the older timeshift code behaves incorrectly and appearently it's incompatible with pvr.hts fixes for 4.1

**Comment by Jalle19** [comment]
Don't know why it works for me, I skipped back and forth many times without a hitch.

**Comment by ksooo** [comment]
@perexg here are the pvr.hts logs:
okay: http://paste.ubuntu.com/14801192/
not okay: http://paste.ubuntu.com/14801208/

**Comment by Jalle19** [comment]
@ksooo I'm able to reproduce now with 4.0.8. Reverting to 4.0.7 makes everything perfect.

**Comment by ksooo** [comment]
So, this one https://github.com/tvheadend/tvheadend/commit/e97fc0706dbe00035361e1d4f06deb42db69d9a5 or this one https://github.com/tvheadend/tvheadend/commit/871f25e4b3b0bb38cc3e0d7302b162acb90ece94 ? No other obviously timeshift-related commits after 4.0.7...

**Comment by Jalle19** [comment]
By .deb file is `4.0.7-21~g406d086`

**Comment by ksooo** [comment]
Okay, reverted https://github.com/tvheadend/tvheadend/commit/871f25e4b3b0bb38cc3e0d7302b162acb90ece94 and no more problems with switching audio track. Will do some more testing and report back how timeshifting in general behaves now.

**Comment by perexg** [comment]
It would be good to know what happens in pvr.hts:

<pre>
14:51:21 T:140147400111872   DEBUG: demuxer seek to: 5810
14:51:21 T:140147400111872   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - demux send seek 5810
14:51:21 T:140147400111872   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - sending message [subscriptionSeek : 7]
14:51:21 T:140148297672448   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - received response [7]
14:51:21 T:140148297672448   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - receive message [subscriptionSkip]
14:51:21 T:140148297672448   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - demux flush
..... time gap ....
14:51:51 T:140147400111872   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to get subscriptionSeek response
14:51:51 T:140147400111872   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - demux flush
</pre>

So, it looks like m_seekCond issue, but "receive message [subscriptionSkip]" and "demux flush" indicates that CHTSPDemuxer::ParseSubscriptionSkip() is called, thus m_seekCond.Broadcast() should be called too to wakeup the seek caller. Could you dig into this ?

**Comment by perexg** [comment]
I think that I got it - there's race in CHTSPDemuxer::Seek, could you try:

<pre>
diff --git a/src/HTSPDemuxer.cpp b/src/HTSPDemuxer.cpp
index 65226c3..296b9ce 100644
--- a/src/HTSPDemuxer.cpp
+++ b/src/HTSPDemuxer.cpp
@@ -162,6 +162,7 @@ bool CHTSPDemuxer::Seek
   if (!m_subscription.IsActive())
     return false;
 
+  m_seekTime = 0;
   m_seeking = true;
   if (!m_subscription.SendSeek(time)) {
     m_seeking = false;
@@ -169,7 +170,6 @@ bool CHTSPDemuxer::Seek
   }
 
   /* Wait for time */
-  m_seekTime = 0;
   if (!m_seekCond.Wait(m_conn.Mutex(), m_seekTime, Settings::GetInstance().GetResponseTimeout()))
   {
     Logger::Log(LogLevel::LEVEL_ERROR, "failed to get subscriptionSeek response");
</pre>

**Comment by ksooo** [comment]
@perexg confirming that your patch fixes the audio stream switch problem. Thanks, Jaroslav. Will you come up with a PR or shall I do?

**Comment by perexg** [comment]
Created PR#190 .

**Comment by ksooo** [comment]
Thx.

@Jalle19 we need this as well for Jarvis

**Comment by Jalle19** [comment]
Thanks all, I'll merge and cherry-pick etc. later tonight.
