### ISSUE TITLE
IPv4 seems to be preferred to IPv6 for the HTSP connection

### ISSUE THREAD

**Issue by mamarley** [kodi-pvr/pvr.hts#197]
I am running TVHeadend with the "-6" option to enable IPv6 support and all the computers in my local network have IPv6 ULA addresses and hostnames pointing to those addresses from the local DNS server.  When I try to use pvr.hts to connect to the TVHeadend box by hostname, I would expect it to try IPv6 first.  However, it always connects using IPv4 only.  (I can tell by looking at the list of connections in the TVHeaded web interface.)  The one exception is that on the TVHeadend box itself if I tell pvr.hts that the hostname is "localhost", it will connect by IPv6.

**Comment by Jalle19** [comment]
I use a hostname too and it correctly uses IPv6. Check advancedsettings.xml if you've accidentally disabled IPv6 in Kodi. Also which platform do you run the client on?

**Comment by mamarley** [comment]
I tried it again and this time it is connecting with IPv6.  Sorry for wasting your time.
