### ISSUE TITLE
how to compile not into xbmc source?

### ISSUE THREAD

**Issue by pauledd** [kodi-pvr/pvr.hts#198]
In your README.MD you described how to build "the addon will be available as a system addon". Is there a way to build it as an seperate file somewhere else outside the xbmc directory that I can load it later in xbmc. Are the cmake options explained somewhere?

**Comment by Jalle19** [comment]
Not really, but you can just ZIP the directory that gets created and use the standard Install from ZIP file option in Kodi. Or you can just copy the addon to your own installation.

**Comment by pauledd** [comment]
Ok, thank you.
