### ISSUE TITLE
Use PVR_STREAM_PROPERTIES directly

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.hts#204]
Now that consecutive order if streams is no longer mandatory we should stop using the wrapper for it and just push the streams directly to Kodi.

Related: https://github.com/kodi-pvr/pvr.vdr.vnsi/pull/60

**Comment by bas-t** [comment]
As @FernetMenta said: you'll notice when it breaks anyway :)

It 's broken!

Scanning dependencies of target pvr.hts
[ 32%] Building CXX object CMakeFiles/pvr.hts.dir/src/client.cpp.o
In file included from /data/kodi-addons/pvr.hts/src/client.cpp:26:0:
/data/kodi-addons/pvr.hts/src/Tvheadend.h:30:38: fatal error: kodi/xbmc_stream_utils.hpp: Bestand of map bestaat niet
compilation terminated.

**Comment by ksooo** [comment]
Sure. #206 

Maybe you should scan the PRs for pvr.hts next time before posting things we already know. Please keep in mind that every post here sends an email to all kodi-pvr members. Thanks.

**Comment by Jalle19** [comment]
This will need an API change if we want to use `std::vector<PVR_STREAM>` internally and just convert that to the C type `PVR_STREAM_PROPERTIES` in when interfacing with Kodi. The `PVR_STREAM` struct is currently "hidden" inside `PVR_STREAM_PROPERTIES`, no idea why it was done like that.
