### ISSUE TITLE
avahi not working

### ISSUE THREAD

**Issue by Glenn-1990** [kodi-pvr/pvr.hts#207]
When connecting to tvh with avahi, an ipv6 ip will be set as server address. 
Somehow this doesn't work (no connection made), don't know why, but we shouldn't forget this.

**Comment by ksooo** [comment]
yeah have seen this as well.

**Comment by Jalle19** [comment]
What does a debug log look like? Is the addon actually starting etc.? I haven't personally used this feature myself since it requires you to use no credentials for the auto-configuration to actually work (there is obviously no way for Avahi to announce valid credentials).

**Comment by Jalle19** [comment]
@Glenn-1990 have you started tvheadend with IPv6 enabled?

**Comment by dreamcat4** [comment]
So does avahi detection work on ipv4? Just wondering.

**Comment by Jalle19** [comment]
It's supposed to, I've seen it work when running tvheadend in a local virtual machine.

**Comment by Jalle19** [comment]
@ksooo what should we do about this? Regardless of whether IPv6 or IPv4 is used it should work, I use IPv6 to connect to my tvheadend server all the time.

Furthermore the Avahi functionality isn't in the addon, it's in Kodi itself. I had a quick look with `avahi-discover` and tvheadend announces on both IPv6 and IPv4. I think we should close this one.

**Comment by ksooo** [comment]
yeah. imo there is nothing we can do about this in pvr.hts. if here is an issue this must be fixed in kodi core. = > close this issue, file an issue on trac
