### ISSUE TITLE
tvheadend no longer works with Kodi on Amazon FireTV upgraded to FireOS 5.0.5

### ISSUE THREAD

**Issue by ullix** [kodi-pvr/pvr.hts#208]
I used the Amazon FireTV (1stgen) to watch LiveTV and videos via the pvr-tvheadend (and a tvh server in the back). Worked quite well.

Now FireTV is on FireOS 5.0.5 and access to the tvheadend backend is no longer possible. I can watch Amazon videos, and (after some struggle) have adbFire access to the FireTV. I re-installed Kodi (16.0) but to no avail.

Strangely, after the reinstall tvh-HTSP client 2.2.13 is active, properly configured, no error message, but no TV option in the kodi menu, therefore neither access to LiveTV nor to the recordings. However, recordings do play fine via NFS.

After deinstall of the tvh-HTSP-client, it is no longer available for an install. By searching in Kodi I find tvh-HTSP client 2.1.7. But attempts to install this one fails; the installer seems to crash, but no error message.

Is this a problem of the tvh-HTSP-client, or Kodi, or else? How can I narrow the problem?

**Comment by Jalle19** [comment]
Can you post a full debug log?

**Comment by ullix** [comment]
Full debug? I can offer the Kodi.log
[kodi.log.zip](https://github.com/kodi-pvr/pvr.hts/files/182859/kodi.log.zip)

These were my steps:
- end Kodi of FireTV
-reinstall Kodi 16.0 per adbFire
- start Kodi from Firestarter (no error message, no TV menu, 
- under user --> addons-->PVRClient I see Tvheadend HTSP client 2.2.13 ist installed, active, and properly configured
- I deactivate, then reactivate. no error, but also still no TV menu
- I deinstall this client
- try to reinstall , but it is NOT available under user-->addon-->pvr clients
- search for tvh addons
- it finds version 2.1.7
- installation fails, but again no error message

**Comment by Jalle19** [comment]
So you've somehow had two different addon versions installed?

**Comment by ullix** [comment]
No.

By the fresh default installation the pvr tvh addon 2.2.13 had been installed and was properly configured. However, it did NOT provide access to the tvh backend, nor did it complain that it could not access the backend.

Attempts to de-install and then re-install failed, because the tvh-pvr addon was not in the list offered by Kodi, when looking under Settings-addons-useraddons-pvrclients.

Using the search function of kodi under settings-addons-search only produced the 2.1.7 version, and that one could not even be installed. So, at most there was one single version installed (2.2.13), and now there is none installed, and none can be installed (unless I do a fresh install of Kodi).

**Comment by Jalle19** [comment]
Judging by the log your database is messed up so you'll have to delete the TVXX.db file (XX are numbers) from your user data. After that you need to reinstall Kodi or something so you can actually enable the adon again. Then provide a new log.

**Comment by ullix** [comment]
Nope; problems unchanged.
The only TVXX.db existing was TV26.db. I deleted that and reinstalled kodi 16 from *.apk. Then TV29.db existed as only TVXX*.* file.

Starting Kodi and the exact same results as described above, i.e. no TV despite 2.2.13 active (and Kodi/tvh working on all other systems in the house). After de-install it disappeard, and only the old 2.1.7 was found, which could not be installed.

new Kodi.log attached
[kodi.log.zip](https://github.com/kodi-pvr/pvr.hts/files/186281/kodi.log.zip)

**Comment by Jalle19** [comment]
Can you pastebin the log instead of zipping it so I can read it on my phone more easily?

**Comment by Jalle19** [comment]
And why do you keep uninstalling the addon? Clearly it just makes matters worse.

**Comment by ullix** [comment]
;-) it also does not help to keep it, as it simply does NOT WORK!

It is the old idea that a reinstallation might help things, going back to the old days of shutting down windows in order to fix it. 

Tell me what to do when a fresh install is not working, and I'll do it. A fresh install is only one minute.

What puzzles me is the fact, that the deinstalled PVR addon is not listed as being available. It should be sitting there, just waiting for a reinstall. Am I wrong in assuming that?

**Comment by Jalle19** [comment]
Yes, you are assuming wrong. If you uninstall system addons you have to reinstall Kodi to get them back. Post a debug log after you've reinstalled and enabled the addon that is bundled. Also enable PVR from the settings in case you haven't done that.

**Comment by ullix** [comment]
Aha. Well, then the existing logs do show exactly that case! 
As I said, after installation the tvh pvr addon 2.2.13 IS already installed, and IS activated, and IS properly configured and the TV option IS enabled. 

That had been the working configuration and that is what failed after the FireOS upgrade to 5.0.5

**Comment by ullix** [comment]
I have now de-installed from FireTV everything seemingly related to Kodi, and then reinstalled Kodi 16.
Tvheadend was found by default, and Live TV and TV recordings via tvh-pvr all worked. 
Whatever the cause, it is back to normal. Thanks for the help.

**Comment by Jalle19** [comment]
Good to hear, closing this then.
