### ISSUE TITLE
Playing back a tv-recording-in-progress and reaching the end-of-file stops playback in Kodi and TVHClients' player

### ISSUE THREAD

**Issue by wkl001** [kodi-pvr/pvr.hts#211]
On my windows 7 laptop I have Kodi 16.1, pvr.hts 2.2.14 and tvheadend_4.1-1723~g465f64c_armhf (so latest of everything).

This is what I do in Kodi: I watch a channel and press "record". Then I press stop.
Then I playback the recording and FF (or skip) to the end of the buffer.
Then Kodi STOPS playback. It would be awesome if Kodi (of TVHClients' player) would start playing livetv.

(This is different from watching livetv, pausing and FF to end of buffer!!! That works although also here I would like to have Kodi and TVHClients' player start playing livetv in stead of trying to keep FF-ing).

In the Kodi logs I see that Kodi stops receiving data and therefore stops playback.
I have tried logging in tvheadend but probably I'm doing it wrong because I can't see any info about the file being sent to Kodi. So I don't know what tvheadend is doing.
(I see logging in webif by clicking "enable debug output" but I don't see logging of the streaming of the data).

Backend: Pi2, debian jessie. Frontends: w7 laptop, android 4.4 tronsmart s89-H, android 4.4 samsung tablets.

**Comment by Jalle19** [comment]
This is not something the addon has control over. The same thing happens when you fast-forward in a file - once you reach the end playback stops. Live TV is special because you never reach the end, that's why it doesn't stop.

Going from a recording to live TV isn't as simple as it sounds, but if you want to you can make a feature request on the forums.

Furthermore, TVHClient is completely unrelated to Kodi or this addon.

**Comment by wkl001** [comment]
I understand.
If you permit me, just 1 question: is it not possible that pvr.hts interprets playing back a recording-in-progress as a request to watch livetv? Because that's what it is and in that way it wouldn't stop.

**Comment by wkl001** [comment]
Oh yes, forgot to mention, I was directed here from TVHeadend:
https://tvheadend.org/issues/2744#note-65

**Comment by Jalle19** [comment]
I guess it could be possible but it would need to be done in Kodi itself.

**Comment by wkl001** [comment]
Thank you, I will post a feature request on the forum.
