### ISSUE TITLE
seem to have lost the on-screen signal meter

### ISSUE THREAD

**Issue by iamgreenbag** [kodi-pvr/pvr.hts#221]
Just noticed the signal meter's missing in the newest releases.

**Comment by Jalle19** [comment]
Do you mean the one in the debug OSD?

**Comment by iamgreenbag** [comment]
System - TV - Playback - Show signal quality. I thought that was controlled by pvr.hts. Unless I'm wrong. It used to show signal strength, mux datas, etc, etc. Now it's just bitrates.

**Comment by Jalle19** [comment]
What skin do you use?

**Comment by iamgreenbag** [comment]
Confluence. I was just thinking that might have been an issue. The text itself is even bigger. I'm having to do a re-install of my os, so I'll test it out tonight with the default Estuary.

**Comment by Jalle19** [comment]
Either way this can't really be an addon issue, if the problem remains you should open an issue on trac.kodi.tv.
