### ISSUE TITLE
kodi-pvr-hts and ubuntu 16.04

### ISSUE THREAD

**Issue by xraynorm** [kodi-pvr/pvr.hts#222]
Hi,

After upgrading to ubuntu 16.04 the pvr plugin is not working in kodi. Just get "Scanning for PVR services" but finds nothing. Other clients running old version of kodiubuntu work fine.

Ubuntu 16.04
Kodi 16.1
kodi-pvr-hts 2.1.18-1
HTS Tvheadend 4.0.9-4~gac9e47d~trusty (on separate sever)

Thanks

**Comment by xraynorm** [comment]
21:21:42 T:139827441800960  NOTICE: PVRManager - starting up
21:21:42 T:139827466979072   DEBUG: Thread PVRManager start, auto delete: false
21:21:42 T:139827475371776   DEBUG: Thread PVRClient start, auto delete: false
21:21:42 T:139827475371776   DEBUG: RegisterClient - registering add-on 'Tvheadend HTSP Client'
21:21:42 T:139827475371776   DEBUG: Previous line repeats 1 times.
21:21:42 T:139827475371776   DEBUG: PVR - Create - creating PVR add-on instance 'Tvheadend HTSP Client'
21:21:42 T:139827475371776   DEBUG: ADDON: Dll Initializing - Tvheadend HTSP Client
21:21:42 T:139827475371776   ERROR: ADDON: Could not locate pvr.hts.so

**Comment by Jalle19** [comment]
I missed this apparently. Did you solve it?

**Comment by Jalle19** [comment]
Closing as obsolete.
