### ISSUE TITLE
Signal/Quality bar not working on Kodi 16.1 / Windows 10 x64 / TvHeadEnd 4.1

### ISSUE THREAD

**Issue by julianxhokaxhiu** [kodi-pvr/pvr.hts#227]
Kodi always displays 0% for both `Quality` and `Signal`.

Any clue?

Thanks in advance

**Comment by Jalle19** [comment]
Does the tvheadend web interface show quality stats?

**Comment by julianxhokaxhiu** [comment]
Yes it does, as numbers although, not as progress bars

**Comment by Jalle19** [comment]
What exact numbers does it show? There are different scales for signal strength and Kodi/tvheadend only handle some of them correctly.

**Comment by julianxhokaxhiu** [comment]
I don't have them right now, although they are just numbers like -40.0db and 10.1 db or something like that.

I'm gonna provide you a screenshot later this evening :)

**Comment by Jalle19** [comment]
Thanks, please do that.

**Comment by ksooo** [comment]
AFAIK currently Kodi is not able to display the db-Values correctly. There is neither an api nor an implemention. This holds for kodi core, skins and pvr addons. :-/

**Comment by ksooo** [comment]
To get this working, pvr addon api and gui info api must be extended and of course kodi core, skins and pvr.hts implementation must be adjusted to support the new api.

**Comment by Jalle19** [comment]
@ksooo not necessarily, the addon just needs to translate the values received from the backend to a 0-100 scale. This is currently done with some weird logic originating from the old pvr.hts addon and it only works in some cases. Since Digital Devices don't appear to support signal strength in their drivers I've never been able to test it reliably.

**Comment by ksooo** [comment]
There are many discussions on the internet on how to translate signal strength db -> % and although it's long ago I dealt with this I remember that there is no clean formula for this. Only clean solution is to design an api that supports both metrics. So, no wild guessing and voodoo formulas needed, but it's more effort, yes.

**Comment by julianxhokaxhiu** [comment]
Here it is!

![snr](https://cloud.githubusercontent.com/assets/1237070/15655213/439aecd6-269b-11e6-80eb-01decee81adf.png)

**Comment by L-S-D** [comment]
at the end it's only SNR what really counts in a digital transmission, but if we currently can only display integers between 0 and 100 its nothing which can be used for aligning eg a dish, but the question is if kodi is the right "tool" in this case anyway.

**Comment by Jalle19** [comment]
There are some complicated methods of calculating SNR and signal strength into a percentage, but I've only found official reference methods for DVB-T and DVB-C, not for DVB-S. `pvr.vbox` uses a hacked together method which kinda works: https://github.com/kodi-pvr/pvr.vbox/blob/master/src/vbox/ChannelStreamingStatus.cpp#L74

**Comment by L-S-D** [comment]
signal strength is nice to have, but as long as your SNR is high enough (which depends on modulation type, SR and FEC) it should not change your quality. If you insert an amplifier which would just increase your signal strength (and lower your SNR slightly) it would just make a difference if you have to compensate your cable losses. So a valid percentage interpretation should calculate the C/N needed and compare it to the actual value.

**Comment by julianxhokaxhiu** [comment]
So basically it's impossible to obtain a value in a range to show it on Kodi? Unless we do some hacks, or we wait for the new API to appear on Kodi, right?

**Comment by Jalle19** [comment]
Pretty much, yes.

**Comment by julianxhokaxhiu** [comment]
Thank you very much :) I'll try to open an issue and to refer this one, on the Kodi repo

**Comment by kowalmisiek** [comment]
Hello. Has something moved about the% kodi progress bar? There is still no code 17 or 18.
