### ISSUE TITLE
build instructions unclear

### ISSUE THREAD

**Issue by tmelin** [kodi-pvr/pvr.hts#228]
I think there is an issue with the build instructions. If one tries to build according to them, it doesn't work.
It will give:

CMake Error: The source directory "xbmc/xbmc/project/xbmc/project/cmake/addons" does not exist.

When building according to paths given in the instructions, the pvr.hts repo needs to be cloned inside the xbmc repo into folder xbmc/project.

Could the build instructions please be clarified on this point, or otherwise changed?

Also, I could never find any generated zip file after building, assuming the -DPACKAGE_ZIP=1 refers to that being requested.

Thanks,
Tomas

**Comment by Jalle19** [comment]
I just copy-pasted the exact commands from the README and it built just fine. There's a missing `make install` in the end though, I'll make a PR for that.

Make sure your `pvr.hts` and `xbmc` directories are in the same directory.

**Comment by tmelin** [comment]
It seems to work if doing the commands from the README, but not if checking out the version branch first. So e.g. in my case I first check out branch Jarvis and then run the commands. cmake fails on error.

**Comment by Jalle19** [comment]
You need to build against the Jarvis branch of the addon if you're building against a Jarvis Kodi. Also check the README for that branch, it could be that the instructions have changed since then.

**Comment by tmelin** [comment]
That is exactly what doesn't work for me if following the README instructions 

Following README without any checkout - build works
Following README and checking out Jarvis in both Kodi and addon repo - build fails.

**Comment by Jalle19** [comment]
I guess I'll have to try building the Jarvis branch.

**Comment by jiphex** [comment]
I had a similar problem building the Jarvis branch of this addon, cmake was complaining about a missing addon source directory of `xbmc/project/pvr.hts`. I solved it by doing:

    cd xbmc/project/
    ln -s ../../pvr.hts

After doing that I could build the Jarvis branch

**Comment by Jalle19** [comment]
I tried the build instructions recently when building for master and they're still correct. A slight change is needed if you're building Kodi with CMake, that will be fixed by #239
