### ISSUE TITLE
DVBSky S950 Linux 

### ISSUE THREAD

**Issue by ToneStrife** [kodi-pvr/pvr.hts#229]
Hi everyone

I'm running Kodi under Ubuntu 16.04. I have TVHeadEnd 4.1 and a DVBSky950.

When I open LiveTV  on Kodi the 75% of times it returns the image on black, with squares or something like that, it looks like the post-processing or something goes wrong. After maybe 5 minutes it gets perfect until you change channel.

If I connect in other or the same computer at the same time through the internet to tvheadend I can watch the channel perfectly so I think that it is a problem with the pvr addon.

Is there something I can try? Where can I find a log ?

**Comment by Jalle19** [comment]
The log is in ~/.kodi/temp/kodi.log` on Linux systems, check kodi.wiki for other platforms. I doubt it's related to the addon though, more likely an issue with either the TV card of the video acceleration.

**Comment by ToneStrife** [comment]
I don't know because in the same computer but without Kodi, through Chrome and tvheadend it works like a charm. 

I will try to send a log.

**Comment by Jalle19** [comment]
Then it's probably the video acceleration.

**Comment by Jalle19** [comment]
Closing as invalid, it's not possible that this has anything to with the addon.
