### ISSUE TITLE
pvr.hts v2.2.15 - win10 - kodi 16.1 - finished recordings dissapear from the 'Recordings' page

### ISSUE THREAD

**Issue by dreamcat4** [kodi-pvr/pvr.hts#236]
Hi there,

I noticed this has been happening for maybe a few days / or a couple of weeks now. While the program is currently recording all is normal. But once a recording is finished recording, the entry dissapears from Live TV --> Recordings Page. And it does not re-appear again. Physically the file remains persistent on the hard disk. And can still be accessed through alternative methods (eg samba share).

I had believe until today its something screwed up on my windows PC. However with a brand new windows 10 PC (same Kodi 16.1). The same problem is seen of 2 different PCs (same tvheadend server). With the 2nd PC having its kodi settings folder populated by an ansible playbook. (1st PC was setup manually). And it does not seem that theres much in the pvr.hts settings.xml file to begin with.

Has anybody else experienced the same issue recently? Is this issue specific only to windows clients? Or is there something going on at the tvheadend server side instead?

My tvheadend version is 4.0.9 (release), and has not been changed / upgraded for a relatively long time. Since before the issue started happening. Wheras my kodi addons are set to auto-upgrade.

Haven't looked any further yet or taken logs. Since was hoping you already knew about this one.

**Comment by ksooo** [comment]
As there were no changes in Kodi 16 and pvr.hts for Kodi 16 for months I tend to think that you screwed up things on your end.

**Comment by ksooo** [comment]
Maybe some Windows 10 shit? Just guessing, because you mentioned it.

**Comment by ksooo** [comment]
Samba problems in conjunction with win 10 I mean...

**Comment by dreamcat4** [comment]
Yeah maybe something like that. And especially if nobody else is seeing it.

Not sure what you mean by samba being screwed up though. I'm only talking about whats shown in the pvr.hts Recordings page Kai. Those are all done over the tvheadend API / protocol aren't they?

Or do you mean that maybe if samba interferes with the file permissions / ownerships, then that could cause tvheadend to 'not see' the recordings anymore and assume they were deleted? I guess thats also a possibility.

Anyway I'm due to refresh / rescan all my tvheadend server side config soon anyways. So maybe if I'm lucky and its server side issue it might just go away without having to worry / dig deeper.

Not in any hurry but I'll post more feedback about this issue later on. When can get round to investigating it further & more thouroughly.

**Comment by Glenn-1990** [comment]
@dreamcat4 are the recordings still visible in the tvheadend webui? Also a kodi logfile (enable trace in tvh addon settings) would be handy to have :-)

**Comment by dreamcat4** [comment]
Thanks Glenn.

Ah no, they are not visible in the "Finished Recordings" tab of tvheadend Web UI. Interesting! Currently recording shows are visible while they are recording... As are future recordings.

So it seems much more likely to be a server side issue. And as are other clues already mentioned which also suggest it isn't pvr.hts. Not unless pvr.hts is interferring at the end of the recording time, which is far less likely.

**Comment by Glenn-1990** [comment]
@dreamcat4 Yes this sounds like a tvheadend issue then. Are the recordings still listed in the failed recordings list? If they are not there either, I suspect an invalid or small retention setting in tvheadend (or lifetime setting in kodi).

**Comment by dreamcat4** [comment]
Yeah thats a correct guess Glenn, the finished recordings are not appearing in the failed recordings tab on tvheadend WebGUI.

Not sure about retention but did not actually ever go to change any of the tvheadend's Recording Profile settings.

![tvh dvr profile](http://i.imgur.com/fd0ILIF.png)

**Comment by Glenn-1990** [comment]
Your tvheadend settings look fine at first sight. It is clearly no pvr.hts issue, you can submit an bug report here https://tvheadend.org/projects/tvheadend/issues. This issue can be closed.

**Comment by dreamcat4** [comment]
Yeah sure. I just dont know which subsystems to turn on for the logging. ATM only thing showun up in the logfiles is:

```
2016-09-03 20:00:00.006 [   INFO] subscription: 2021: "DVR: Grand Designs" unsubscribing from "More4"
2016-09-03 20:00:00.007 [ INFO] dvr: "Grand Designs" on "More4": End of program: Completed OK
```

https://gist.github.com/dreamcat4/5297bd6a9800ad2b84b15c28eff5eaab#file-gistfile1-txt-L37

Will ask on #hts Freenode IRC
