### ISSUE TITLE
Problems with (some) hevc UltraHD channels

### ISSUE THREAD

**Issue by anthonytex** [kodi-pvr/pvr.hts#237]
Hi all, first thanks for your great work. 
I want to point out a strange issue that i get with some hevc channels. These channels are all playable with direct mux/channel links both in kodi (exporting them in an m3u file for example) and also with a browser, but i can't play them with htsp client.
I have also open a ticket [here](https://tvheadend.org/issues/3853) and in kodi's forum there are [some users](http://forum.kodi.tv/showthread.php?tid=278293) with same problem. 
This is a debug with fastest kodi 17 nightly 
[kodi.txt](https://github.com/kodi-pvr/pvr.hts/files/469244/kodi.txt)

EDIT: for example if someone can test: i have a problem with Funbox 4k on Eutelsat Hotbird 13E, this channel worked until more or less a week a go, the only thing that i've noticed is that Service ID has been changed to 0x19 from 0x01

**Comment by Jalle19** [comment]
Based on https://tvheadend.org/issues/3853 it seems like a tvheadend issue. When you stream over HTSP tvheadend has to able to parse the video/audio streams, which is why some things only work when played over HTTP (in which case tvheadend leaves the stream processing to the client).

Have you tried the latest tvheadend builds?

**Comment by anthonytex** [comment]
Thanks for your answer, i agree with you but it seems nobody has investigated there. Now i'm using the latest git revision, so it appears the problem is still there.To be clear: I had this problem on a test channel some months ago, but well, it was broadcasted  only for one week, not a big deal. Now the problem is suddenly reappeared and the strange thing is that funbox 4k was working good until a week ago: never touched tvheadend config in that period. I noticed that they have changed channel's logo (of course this is not the issue ;) ) but maybe they have changed also something else. By they way they are not respecting DVB standards as they are broadcasting an hevc UHD channel with a service id of 0x19... I don't think is related because also the other channels uses a service id of 0x01 and not 0x1F and they works well... Other Uhd channel are: HotBird 4k1 (hevc main10) and Hotbird 4k1 (hevc main10 with colorspace of bt2010 and hdr hlg)

**Comment by Jalle19** [comment]
Some guy in one of those threads you linked said the format changed slightly on one channel, after which it stopped working.

@perexg do you think you could help us out?

**Comment by anthonytex** [comment]
Some more information: deleting hts "home" and so recreate completely tvheadend configuration doesn't work, same issue. Record and play that channel with kodi works. and these are some codec information:
[channelinfo.txt](https://github.com/kodi-pvr/pvr.hts/files/470394/channelinfo.txt)

**Comment by Jalle19** [comment]
Closing this on the same grounds as https://github.com/kodi-pvr/pvr.hts/issues/233. I've pinged @perexg on IRC to ask him to take a look at it from the tvheadend side.

**Comment by Jalle19** [comment]
https://github.com/tvheadend/tvheadend/commit/95e20e27c8f44f3d1471332c6034a1358f5b7469 reported to fix other HEVC channels too

**Comment by anthonytex** [comment]
Yes, i can confirm that all is fine now! thanks ;)
