### ISSUE TITLE
Addon won't load on aarch64 platform

### ISSUE THREAD

**Issue by arny91** [kodi-pvr/pvr.hts#238]
Hi, i'm having troubles in getting this addon working in kodi on an aarch64 platform, specifically an Odroid C2 (Amlogic S905), but i have the feeling that the problem affects the whole platform generally (and so the rpi3) . This is the content of the log file:

`14:15:30 T:547523043328  NOTICE: PVRManager - stopping
14:15:31 T:546945626352  NOTICE: PVRManager - starting up
14:15:31 T:546400366832   ERROR: ADDON: Dll Tvheadend HTSP Client - Client returned bad status (6) from Create and is not usable
14:15:31 T:546400366832 WARNING: UpdateAndInitialiseClients - failed to create add-on Tvheadend HTSP Client, status = 6
14:15:31 T:546400366832 WARNING: UpdateAndInitialiseClients - failed to load the dll for add-on Tvheadend HTSP Client, disabling it
14:15:46 T:547523043328   ERROR: GetDirectory - Error getting addons://disabled/xbmc.pvrclient
14:15:46 T:547523043328   ERROR: CGUIMediaWindow::GetDirectory(addons://disabled/xbmc.pvrclient) failed`

**Comment by Jalle19** [comment]
How did you install Kodi and the addon? Did you compile it yourself?

**Comment by arny91** [comment]
I compiled it from the AUR (i'm using arch linux) and installed it with pacman. It works well on rpi2,  but it isn't working at all on odroid c2 (and i think rpi3 as well.) I also tried to use pre-compiled versions of this addon for kodi, installed them from the addon manager, but none of these are working.

**Comment by bkuhls** [comment]
According to https://aur.archlinux.org/packages/kodi-addon-pvr-hts/ and https://aur.archlinux.org/packages/kodi-addon-pvr-hts-git/ the package is not available for armv8h aka aarch64. Did you already ask on the forum https://archlinuxarm.org/forum/viewforum.php?f=65 for support?

**Comment by arny91** [comment]
Already asked here:
[](https://archlinuxarm.org/forum/viewtopic.php?f=30&t=10370&sid=f04e250d3d7cd43e602bea1136fa8a0f&start=10)
The fact that a target is not included inside the PKGBUILD file doesn't mean that the software isn't available for that platform. It compiles well indeed. It just crashes (won't load) when you enable it from kodi. There are some packages with missing targets for arm platforms inside the PKGBUILD file, by adding the target names in the right place you can build such packages also for those platforms.

The question is: does this addon works on aarch64 platform? From these replies, it seems it doesn't.
[](http://forum.odroid.com/viewtopic.php?f=95&t=22411&start=50)
The error seems to be the same.
And they're not using arch like me.

**Comment by Jalle19** [comment]
Have you tried using any other PVR addons on that platform? pvr.iptvsimple is probably the easiest to test since you just need an M3U file to make it load correctly. We don't officially support Aarch64 as far as I know (we don't even build for it on our Jenkins) so it's hard to help.

**Comment by Jalle19** [comment]
Is this still an issue?

**Comment by arny91** [comment]
Yes, it is, at least i think so. I just tried iptvsimple and it crashes the same way. I think this is a very annoying bug, the pvr is a very important part of kodi, and many people uses it. Can something be done?

**Comment by stefansaraev** [comment]
pvr.hts runs fine on aarch64 with kodi v17.

for v16.x you need kodi patched with this: https://github.com/LibreELEC/LibreELEC.tv/blob/libreelec-7.0/packages/mediacenter/kodi/patches/kodi-999.10-aarch64-support.patch - no binary addons would work otherwise.

**Comment by arny91** [comment]
Ok, i noticed today that the problem is another, and it doesn't depend from pvr.hts itself. I'm closing this.

**Comment by ip4368** [comment]
Hi @arny91 
I am having the same issue on odroid c2, you said the problem is not from the pvr.hts itself, would you mind stating what did you do to make it works? thanks

is it like what @stefansaraev said, we need to patch the kodi?

**Comment by arny91** [comment]
Hi, the problem should be fixed with Kodi 17 as the patches have been merged. Would you try it? I currently don't have a linux distro installed on the c2, i removed arch because i wanted to try android, regretting about this. While pvr.hts works in the android play store version of kodi, that board with android is useless, and it also runs out of memory. I'm going to install back again arch linux soon.
