### ISSUE TITLE
Connect to multiple TVHeadend servers

### ISSUE THREAD

**Issue by NotCommonUser** [kodi-pvr/pvr.hts#246]
The request like that pops in and out on various self-help web sites. The typical suggestions include duplicating the hts.pvr plugin together with settings and poinint the 'copied' plugin to other tvheadend server.

This however does not work as: 
1. It is unpredictable whether channels from both servers will appear
2. Even if these appear it is rare that TV Guide data is imported
3. Even when it is imported it is usually wrong (like shifted by a channel)

So all in all I am (very kindly) asking to have capability to connect to multiple TVHeadend servers and have these available through single Kodi TV view. The channel numbers deconfliction could be potentially left to the server operator.

Thank you!

**Comment by Jalle19** [comment]
It is highly unlikely that this will happen, it's simply too much effort.

**Comment by NotCommonUser** [comment]
Jalle,
Do you think it would be more likely to provide support in a way, that at least copied plugin would work? That is two hts.pvr plugins working at the same time connecting to differend TVHeadEnd servers?

**Comment by Jalle19** [comment]
I think that issue has been reported, it is supposes to work.

**Comment by NotCommonUser** [comment]
Jalle,
I went (briefly) through all closed reported issues but there was nothing like it.
I have seen on the web sites telling to copy the plugin and be happy about it but apparently there must be regression with latest KODI/hts.pvr/TVH.

The issue is that the behaviour is totally unpredictable, exactly as I have described in the original post above.

So all in all I am kindly asking whether you could reopen this issue as 'to be fixed' or at least 'to be further investigated'.

Thank you.

**Comment by Jalle19** [comment]
The issue I was thinking about was that Kodi crashed immediately if one tried to use two addons. If you get Kodi to start but it works unreliably then that's another issue which is not likely to be fixed any time soon.
