### ISSUE TITLE
Missing information in the Playerprogressbar

### ISSUE THREAD

**Issue by pacoma** [kodi-pvr/pvr.hts#248]
Kodi with Sat-IP (Octopus Net), the local system does not show all the information where Kodi and TVHeadend are running. Screenshot PVR01

On a client without TVHeadend only with the TVH PVR Addon the information is better. Screenshot PVR02
![pvr01](https://cloud.githubusercontent.com/assets/11475427/20528981/a72e6184-b0ce-11e6-91b1-cde74ebd6a0b.png)
![pvr02](https://cloud.githubusercontent.com/assets/11475427/20528982/a738c8cc-b0ce-11e6-8dc4-20d607d6134f.png)

**Comment by ksooo** [comment]
Are both clients accessing the same tvheadend server?
Are both clients using the same credentials (tvh user/pw)?

**Comment by pacoma** [comment]
@ksooo 

Yes both are using the same TVH Server (running on Libreelec Krypton newest Build 192.168.1.50), and Yes both habe the same User and PW. Under Jarvis the same config have no problems.

**Comment by ksooo** [comment]
Okay, and the only thing that is not working is the pvr info? watching tv, epg etc. works for both clients, right?

**Comment by pacoma** [comment]
Yes everything else runs on all my systems, no matter which OS as the basis.

**Comment by ksooo** [comment]
If you say Jarvis is working fine, does this mean Jarvis clients are working fine with the same tvheadend installation (esp. version) which is not working with Kryptoni? Or do you use Jarvis with an older tvh version?

**Comment by ksooo** [comment]
Do you have a chance to test your Krypton clients with TVH Server (4.1.1708)? 

As there were no changes in Kodi and pvr.hts in this area from Jarvis to Krypton, I'm afraid we're facing a tvheadend problem here.

**Comment by pacoma** [comment]
Yes i can do this, wait 10 Minutes Please

**Comment by pacoma** [comment]
First Screenshot ist Libreelec Jarvis 16.1 with TVH 4.1.1945
Second is Windows Client with Krypton Beta 5 anTVH PVR Addon

You see there works on both machines ...

![screenshot 1](https://cloud.githubusercontent.com/assets/11475427/20538312/edc9cd5a-b0f0-11e6-9d63-0ad211205c4e.png)
![screenshot2](https://cloud.githubusercontent.com/assets/11475427/20538313/edcdb820-b0f0-11e6-8748-4a7a1bea34b5.png)

**Comment by ksooo** [comment]
Thanks. This is evidence that tvh server bundled with latest libreelec 8 alpha is buggy. Please file a bug here https://tvheadend.org/projects/tvheadend/issues and close this issue.

**Comment by pacoma** [comment]
Jupp Thanks

**Comment by MilhouseVH** [comment]
This is often reported even when using latest tvheadend (which is just to say the latest tvheadend is also buggy): http://forum.kodi.tv/showthread.php?tid=269814&pid=2418927#pid2418927

**Comment by pacoma** [comment]
So I have a little further tested, since I do not think it is a TVH problem but a Kodi problem is. I have now the last TVH version 4.1.2330 also installed on Jarvis and as you can see as the information in the Playerprogress correctly displayed

![screenshot3](https://cloud.githubusercontent.com/assets/11475427/20544033/6eb12956-b108-11e6-90ee-5bc962e1bd26.png)

**Comment by Jalle19** [comment]
Are you sure you have the "display signal data" setting in Kodi enabled? It's somewhere in the settings.

**Comment by pacoma** [comment]
@Jalle19 

Yes im sure

**Comment by ksooo** [comment]
Okay. Krypton client on macOS +Krypton client on Ubuntu 16.10 + tvh 4.1.2309 works just fine here. So I can confirm that 4.1.2309 is not unconditionally broken wrt multiple client's signal info handling. 

OTOH, I'm still pretty sure this is neither a Kodi nor a pvr.hts problem.

Can this problem be reproduced in other environments than LibreELEC 8?

**Comment by pacoma** [comment]
If I read it so and it only with me the error indicates, I suspected that my hardware caused the error. I'll make a completely new system tomorrow and then report the result.

**Comment by ksooo** [comment]
Another test result: Latest LibreELEC 8 alpha (Vanilla, no Milhouse build), running both krypton + tvh 4.1.??? on same raspi2, no problems with signal status display, works just fine.

**Comment by pacoma** [comment]
Ok, there remains nothing else than with other hardware tomorrow times to make a new system based on Ubuntu / Lubuntu and then see what happens.

See the error must be on my side, somewhere.

Thanks @ all for Time and Help

**Comment by pacoma** [comment]
With a complete reinstall on another Nuc, everything works as desired. Tested with Libreelec Milhouse Build # 1122, Lubuntu 16.04 Nightly Build from 23.11.

Thanks to all for the support and testing

**Comment by ksooo** [comment]
Thanks for reporting back that it works.
