### ISSUE TITLE
EPG does not accept Named entities

### ISSUE THREAD

**Issue by Schmell** [kodi-pvr/pvr.hts#250]
When importing EPG it throws an error on characters encoded with named entities like `&ecirc;, &Egrave; `etc. but it is fine with numbered (`&#262;`) or hex (`&#xc4;`) type characters. There is also no issue with special characters.  like `&amp;, &lt;`  etc..

**Comment by Jalle19** [comment]
Where are you getting your EPG data from? And what kind of error are you getting?

**Comment by Schmell** [comment]
`htsmsg_xml_deserialize error Unknown label referense: "&ecirc;"`

We are currently working on [script.module.zap2xml](https://github.com/edit4ever/script.module.zap2xml) it is a scraper adapted from zap2xml which scrapes guides from the zap2it.com and tvguide.com sites.
So because it uses a combination of screen scraping and JSON data we get mixed symbols in final xml. 
I have a solution for the problem, but i am curios why it rejects these symbols when the xml file is valid.

**Comment by Schmell** [comment]
Sorry this is probably a backend issue

**Comment by Jalle19** [comment]
Yes, it sounds very much like a backend issue. This addon just takes whatever tvheadend gives us and feeds it to Kodi.
