### ISSUE TITLE
Kodi - LiveTV doesn't recognize tvheadend RTSP Client

### ISSUE THREAD

**Issue by jan-kowalski** [kodi-pvr/pvr.hts#253]
Kodi 16.1 Git:c327c53
Raspberry Pi2
Openelec 5.0.8 or LibreELEC 7.0.2

Hi, is unable to run LiveTV on main tab in Kodi when tvheadend RTSP Client is activated as PVR Client. Tvheadend 4.2 is set as PVR server and working fine, channels are avaiable via webbrowser on other computer.

**Comment by Jalle19** [comment]
Did you configure the addon, enable it and also enable live TV from Kodi's settings? If not try the forums instead, this is not really a support channel.
