### ISSUE TITLE
No HW acceleration on HD-channels, Tvheadend Addon. 

### ISSUE THREAD

**Issue by Vispen74** [kodi-pvr/pvr.hts#254]
On Android devices HD channels skips frames and overloads the CPU due to error in hardware acceleration. It works nice and smooth with accelerated Live-TV on SD-channels with a CPU load of 5 to 10%. 

It looks that this problem still exist in Kodi 17.

Running Kodi 16.4 with latest Tvheadend Addon on Nexbox A1 and Samsung Galaxy tab. 

Please help!

**Comment by Jalle19** [comment]
It's a Kodi bug, not an addon bug. It has also been reported already.

**Comment by Vispen74** [comment]
Ok, do you have a link for this reported case?

**Comment by Vispen74** [comment]
Must be this one:
http://trac.kodi.tv/ticket/16578

**Comment by Jalle19** [comment]
@Vispen74 actually http://trac.kodi.tv/ticket/17069 was the one I was thinking about.

**Comment by Vispen74** [comment]
I see. Yes they are there talking about that the issue could be in the back end.

**Comment by Jalle19** [comment]
I'm gonna go ahead and close this since it's definitely not an addon issue, it's either in Kodi or tvheadend (or both).

**Comment by Vispen74** [comment]
The issue is solved in this build:
http://mirrors.kodi.tv/test-builds/android/arm/kodi-20170103-c404ee1-mediacodec-armeabi-v7a.apk

A new issue with thus bud is no sound on HD channels, but that's another bug.
