### ISSUE TITLE
Switching paused channels issue

### ISSUE THREAD

**Issue by Glenn-1990** [kodi-pvr/pvr.hts#255]
Not sure if this is Kodi or pvr.hts.

Steps to reproduce:
1) play channel
2) pause channel (OSD shows "paused")
3) switch to another channel, new channel starts playing at x1 speed
4) OSD is still showing "paused", player controls are wrong too

**Comment by Jalle19** [comment]
Ancient Kodi bug, I reported it at some point and it was partly fixed (the new channel used to stay paused). Please open a ticket on Trac for it instead.
