### ISSUE TITLE
Slow start of TV Section with Krypton Alpha

### ISSUE THREAD

**Issue by pacoma** [kodi-pvr/pvr.hts#256]
My Hardware Config:

Intel Nuc 5PYYH (Intel N3700)
Sat-IP Ocotpus Net DVB-S2

When I start Kodi, it takes up to 45 - 60 seconds until the data (sender and EPG) are read from the TVHeadend server (TVHeadend and TVH PVR Addon are on the same device). Under Jarvis with the same configuration, these were 4 - 5 seconds. It also takes the reading on a Kodi client with only the TVH PVR Addon seconds 3 - 4 seconds.

On the Log i see this:

`20:10:27.393 T:140502867371776  NOTICE: [service.tvh.manager]: Settings loaded, starting service with id 148
20:10:30.879 T:140501525194496   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command hello failed: No response received
20:10:30.879 T:140501525194496   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to send hello
20:10:32.398 T:140502867371776  NOTICE: [service.tvh.manager]: Connection to http://127.0.0.1 established (Basic Authentication)
20:10:47.479 T:140502867371776  NOTICE: [service.tvh.manager]: Service polling Net/Post/Rec/EPG: 0010
20:10:55.813 T:140502984804096 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/tv/Alle Kanäle/pvr.hts_370568843.tbn
20:10:56.662 T:140503986128640  NOTICE: Start - EPG thread started
20:11:02.571 T:140502867371776  NOTICE: [service.tvh.manager]: Service polling Net/Post/Rec/EPG: 1010
20:12:30.075 T:140502968018688  NOTICE: Previous line repeats 5 times.
`20:12:30.075 T:140502968018688 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/tv/Alle Kanäle/pvr.hts_370568843.tbn

Is this an alpha problem, or a TVH problem

greetings pacoma

**Comment by Jalle19** [comment]
Do you use LibreELEC? If so please check "wait for network" in the addon settings for the tvheadend service itself.

**Comment by Jalle19** [comment]
Scratch that, I meant in the "LibreELEC settings" section (Network tab).

**Comment by ksooo** [comment]
What's this service.tvh.manager thingy i see in the log? An addon? If so, please disable it and report back whether the problem persists.

**Comment by pacoma** [comment]
@ksooo 
Disabling the Addon TVH Power Management Service does not make any difference in behavior

PVR-manager is started will remain very long, until the channels are read in.

@Jalle19 
If I activate in the TVH service Addon "wait for DVB adapter", I get the error message "no connection to TVHeadend"

**Comment by ksooo** [comment]
> Disabling the Addon TVH Power Management Service does not make any difference in behavior

 okay, good to know.

> If I activate in the TVH service Addon "wait for DVB adapter

 this is not what @Jalle19 meant. Please go to LibreELEC settings -> Network -> Wait for network

![screenshot007](https://cloud.githubusercontent.com/assets/3226626/21076322/a7e00994-bf28-11e6-99aa-36889072b27e.png)

**Comment by pacoma** [comment]
Sorry, only the first of @Jalle read, have thought he thinks in the TVH service. Yes wait for network I have, always. When I do this I have no mediafiles anymore, since my access to a Win Server is done with MySQL

**Comment by ksooo** [comment]
> 0:10:30.879 T:140501525194496 ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command hello failed: No response received

Sorry to say this, bit it seems you have a f****d up system setup. Network seems not to work or tvheadend is screwed up. The addon is unable to talk to the tvheadend server.

BTW: I'm using almost the same setup like you do: LibreELEC latest Alpha + latest tvheadend * Octopus NET S8 - and i have absolute no trouble.

**Comment by CvH** [comment]
@pacoma you can delay the start of Tvh (at the Tvh addon settings) for 1-2sec maybe it does some difference
![image](https://cloud.githubusercontent.com/assets/1355173/21076386/439a2184-bf2a-11e6-8a75-e8d5ff85bf0c.png)

**Comment by pacoma** [comment]
I have no problem with it if you say, I just do not know where I am to fix the.TVHedend on the Nuc and the Octipus Net depend on the same switch and this is directly connected to the router. Both get a fixed IP assigned by the router.

**Comment by pacoma** [comment]
@CvH 
I have just tested this with 2 and once with 5 seconds

no change

22:47:12.705 T:140459020105472   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command hello failed: No response received
22:47:12.706 T:140459020105472   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to send hello

**Comment by pacoma** [comment]
In the log of the TVH service I have found the following, this has an influence on the misconduct in my system

2016-12-10 23:03:25.040 [   INFO]:main: Log started
2016-12-10 23:03:25.042 [   INFO]:http: Starting HTTP server 0.0.0.0:9981
2016-12-10 23:03:25.042 [   INFO]:htsp: Starting HTSP server 0.0.0.0:9982
2016-12-10 23:03:25.042 [  ERROR]:satips: use --satip_bindaddr parameter to select the local IP for SAT>IP
2016-12-10 23:03:25.042 [  ERROR]:satips: using Google lookup (might block the task until timeout)
2016-12-10 23:03:25.432 [   INFO]:satips: Starting SAT>IP RTSP server 192.168.1.50:554
2016-12-10 23:03:25.432 [   INFO]:satips: SAT>IP Server initialized
2016-12-10 23:03:25.432 [   INFO]:satips:   HTTP 192.168.1.50:9981, RTSP 192.168.1.50:554
2016-12-10 23:03:25.432 [   INFO]:satips:   descramble 2, muxcnf 0
2016-12-10 23:03:25.850 [   INFO]:config: loaded
2016-12-10 23:03:25.851 [   INFO]:config: scanfile (re)initialization with path <none>
2016-12-10 23:03:33.844 [  ERROR]:uuid: wrong uuid size
2016-12-10 23:03:33.844 [  ERROR]:channel: invalid uuid 'config.tmp'
2016-12-10 23:03:34.085 [  ERROR]:uuid: wrong uuid size
2016-12-10 23:03:34.085 [  ERROR]:channel: invalid uuid 'tag.tmp'

2016-12-10 23:03:39.214 [WARNING]:satips: SAT>IP server announces an empty tuner list to a client 192.168.1.140 (missing tuner settings - global config)
2016-12-10 23:03:39.736 [WARNING]:satips: SAT>IP server announces an empty tuner list to a client 192.168.1.50 (missing tuner settings - global config)
2016-12-10 23:03:39.762 [  ERROR]:http: 192.168.1.30: HTTP/1.1 HEAD /imagecache/409 -- 404

**Comment by ksooo** [comment]
> 2016-12-10 23:03:39.214 [WARNING]:satips: SAT>IP server announces an empty tuner list to a client 192.168.1.140

This does not sound good, but no idea what this actually means. Never seen this before. You should ask in the tvheadeend support forum.

**Comment by pacoma** [comment]
This IP address is from my Sony TV, which has lost in the log of the TVH
2016-12-11 01:25:22.330 [WARNING] satips: SAT>IP server announces an empty tuner list to a client 192.168.1.140 (missing tuner settings - global config) 

an also

2016-12-11 01:25:22.771 [WARNING] satips: SAT>IP server announces an empty tuner list to a client 192.168.1.50 (missing tuner settings - global config)

Also, every tuner is properly configured, I can play on every tuner everything, which is to be wrong?

**Comment by ksooo** [comment]
No clue, sorry. I can only say that my setup is very similar to yours and i have no problem with pvr startup time.

**Comment by pacoma** [comment]
@ksooo 

It ist possible to send me your Config?

**Comment by ksooo** [comment]
> It ist possible to send me your Config?

 which "config" at do you mean exactly?

**Comment by pacoma** [comment]
The "input" Folder, the "config file" and the "settings.xml"

**Comment by Jalle19** [comment]
@pacoma I don't think someone else's config is going to help. I'm gonna close this because I doubt it's actually an addon issue. If the OS doesn't let you do network connections properly during startup there's nothing the addon can do about it.
