### ISSUE TITLE
Allow accessing multiple instances of TVH servers

### ISSUE THREAD

**Issue by doe1097** [kodi-pvr/pvr.hts#258]
Hello devs,
I'm currently searching for a solution on how to access multiple instances of TVH servers via Kodi. There are some workarounds by duplicating the Addon, but this seems nasty. So, long story short: Is it possible to extend the configuration panel to access more than just one server?

Best,
doe

**Comment by Jalle19** [comment]
Not really, and I don't think it's on the roadmap for now.

**Comment by doe1097** [comment]
Thanks for your reply @Jalle19! You do great work on this Addon.
Is there any way to put it on the roadmap? Feels like there are some users out there who are facing the same issue and struggling with workarounds. This could be a handy solution..

**Comment by AlwinEsch** [comment]
I still working on a way to add multiple instances of a add-on like PVR, but still need a bit time. Sorry!

**Comment by ksooo** [comment]
> I still working on a way to add multiple instances of a add-on like PVR, but still need a bit time. Sorry!

 nice, but there are also issues in the kodi core that need to be fixed to get more than one pvr addon (regardless if same type or not) working. So, still some way to go...

**Comment by Jalle19** [comment]
I'm going to go ahead and close this one since while it's a legitimate issue, support for it needs to be done in Kodi before we could possibly adapt the addon to work in that way.

**Comment by doe1097** [comment]
Sorry for asking in a closed thread, but are there any news on this @AlwinEsch? And just out of curiosity, will your approach enable _us_ to see both servers in one Channel list?

**Comment by AlwinEsch** [comment]
Started now to bring in the first steps to Kodi. Due to the very big rework takes it a bit time.
