### ISSUE TITLE
Fix Travis, at least for the Krypton branch

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.hts#265]

**Comment by FernetMenta** [comment]
I posted the solution on slack some time ago:
https://github.com/kodi-pvr/pvr.vdr.vnsi/commit/90aa7f0c6787ab9e2c2a04dd023907b391dd732d

**Comment by Jalle19** [comment]
Thanks!

**Comment by Jalle19** [comment]
Seems like a path change is needed for master too
