### ISSUE TITLE
Default aspect ratio

### ISSUE THREAD

**Issue by scottgrobinson** [kodi-pvr/pvr.hts#273]
Apologies if this is a Kodi issue but I can't work it out from the code...

When I switch to a new channel, it starts off in 4:3, and then after a few seconds switches to 16:9 (Although, where the channel is already in 4:3 you don't really notice any difference). 

I want to say that either Kodi or the PVR addon is providing a 'default' aspect ratio, then switching once its managed to read it from the stream. BUT... That's a bit of a guess.

If it is a case of the PVR addon switching, is there a way we can add the ability to set the 'default'?

**Comment by Jalle19** [comment]
This is a Kodi bug and it only affects some platforms. Have you tried the latest RC release since this should have been fixed already?

**Comment by scottgrobinson** [comment]
Thanks and in that case apologies for raising it here!

I'm running rc2 on libreelec with no such luck. Do you happen to have a link or any info on said bug? I've not come across that on my searches...

**Comment by Jalle19** [comment]
E.g. http://trac.kodi.tv/ticket/16085
