### ISSUE TITLE
Allowing https access to TVHeadend 

### ISSUE THREAD

**Issue by Dom1n1c** [kodi-pvr/pvr.hts#281]
It is a similar question, I recently asked the developer from TVH Client for Android. 
What if my UI is served via https, for example by reverse proxying it. 
It is possible to proxy it with nginx via http, but as soon as I move forward to https, the default http:// parameter does not match the parameter from nginx. 
Https streaming is possible, when using the m3u from the IF for instance.

**Comment by Jalle19** [comment]
I haven't bothered adding this since it's not natively supported by tvheadend. If tvheadend ever starts supporting HTTPS then sure, thid would definitely be added.

**Comment by Dom1n1c** [comment]
You're absolutely right. TVHeadend has no native https support (yet) , but I use a central reverse proxy, which can offer the http://tvh:9981 via https. 
Maybe you can add a https checkbox under the advanced settings of this addon. It's not really urgent, but I would love to see this in a future release. 
(currently I serve it via http, but as soon as possible, I do not want to serve anything via https) 

Thanks for your support.

**Comment by Jalle19** [comment]
For now your best option is probably to redirect requests to HTTPS in your reverse proxy. It will not prevent your credentials from leaking though.
