### ISSUE TITLE
PVT HTS causes Kodi restart

### ISSUE THREAD

**Issue by elgatito** [kodi-pvr/pvr.hts#288]
Currently facing problems with starting LiveTV in Kodi. When selecting a channel Kodi restarts. Not 100% to happen, sometimes channel starts, then switching works fine. So problem appear only to first-time channel (so same channel can cause restarts like 5 times in a row, then load fine).

No changes in settings were made, it was working fine, then just started to cause issues.
Tried to update Libreelec to latest version, no changes, problem happen from time to time.

Environment:
OS: Libreelec 7.95beta6 (From kszaq - https://forum.libreelec.tv/thread-2156.html )
Kodi: 17
Tvheadend: HTS Tvheadend 4.1.2415 ~ LibreELEC Tvh-addon v8.1.109
PVR.HTS: 3.4.17

Sample crash logs:
http://sprunge.us/RNKh
http://sprunge.us/EVLj

**Comment by elgatito** [comment]
One more log with PVR.HTS debug=true in settings.xml

http://sprunge.us/LaBG

**Comment by ksooo** [comment]
What kind of build is this? LibreELEC 8 beta 6 does not contain Kodi 17.1 (which is not released yet).  If it is something self compiled, you will not get support here.

**Comment by elgatito** [comment]
Build for amlogic devices. Kodi is added latest from git.

**Comment by ksooo** [comment]
Sorry, you are on your own, then. We simply don't have the resources to supported home built stuff because we have no idea what it actually is what we are facing here. Stack traces look broken, seems you compiled something shitty?

**Comment by elgatito** [comment]
I have placed a link to builds of Libreelec.  It's now on libreelec download page. It's not my build!

**Comment by ksooo** [comment]
> It's not my build!

 This does not change a thing. It's a build from "somebody else" than Team Kodi. Please understand that we cannot support this. If the problem also occurs with a vanilly kodi build downloaded from kodi.tv you are welcome back here. LibreELEC != Kodi.

**Comment by elgatito** [comment]
If anyone will search for same issue. 

Disabling All Groups from tvheadend helps to not meet this bug.
