### ISSUE TITLE
Unable to start addon Debian/SteamOS Kodi 17

### ISSUE THREAD

**Issue by mdeguzis** [kodi-pvr/pvr.hts#291]
I updated the PVR addons for my repository recently. I made sure to use the Krypton branch for them (if available). I have one particular user who is trying to use the HTS addon, but the addon seems to be requesting a lib version higher than what the package provides. Is this a matter of incorrect versioning in my build script, user error, or am I using the wrong branch of source code? 

Please see: https://github.com/mdeguzis/SteamOS-Tools/issues/162
Build script: [build-kodi-pvr-hts.sh](https://github.com/mdeguzis/LibreGeek-Packaging/blob/steamos/kodi/pvr-addons/build-pvr-hts.sh)

**Comment by Jalle19** [comment]
The issue you referenced seems to have been closed? Does that mean this is no longer an issue as well?

**Comment by mdeguzis** [comment]
This can be closed when PR#290 is closed. I fixed on my end (via my forks).

**Comment by Jalle19** [comment]
It's merged now
