### ISSUE TITLE
Support audio passthrough in Recordings on Kodi 17

### ISSUE THREAD

**Issue by bconway** [kodi-pvr/pvr.hts#292]
Background: [Audio Passthrough on LiveTV](http://forum.kodi.tv/showthread.php?tid=284580)

On Kodi 17, it looks like the intention is that Live TV will now always decode to PCM, but that Recordings should support audio passthrough. Currently (LibreElec 8.0.1), the tvheadend add-on is decoding to PCM for both Live TV and Recordings. I have no knowledge of the Kodi PVR API, but the above thread indicates an update may be required. Thanks!

**Comment by Jalle19** [comment]
I'm not really sure what we need to change to make that happen. @FernetMenta can you explain? I'm assuming the `IsRealTimeStream` method needs to be changed.

**Comment by FernetMenta** [comment]
@Jalle19 if you return true for IsRealTimeStream, passthrough audio ges disabled.

**Comment by Jalle19** [comment]
@FernetMenta why does that get called when playing recordings? They don't go through the demuxer methods AFAIK.

**Comment by FernetMenta** [comment]
VideoPlayer just plays a stream. It treats realtime differently but it does not care if recording or why type ever.

**Comment by Jalle19** [comment]
Okay. I guess we can assume that real time is `false` if no demuxer is currently active (which is the case for recordings). Dealing with recordings that are near the EOF will be tricky.

@ksooo do you have an opinion on this?

**Comment by ksooo** [comment]
>  I guess we can assume that real time is false if no demuxer is currently active

 sounds reasonable.

**Comment by ksooo** [comment]
@Jalle19 just noticed that we're not resetting demuxer's timeshift status when closing a subscription. Doing this should solve the problem discussed here and another one I discovered yesterday: When watching timedhifted tv, stopping the channel playback then and watching a recording directly after, the recording will be displayed in info osd as "timeshifted".

**Comment by Jalle19** [comment]
@ksooo I think some work toward fixing that was done in https://github.com/kodi-pvr/pvr.hts/commit/b54af841b8c62cf08a75ae8101e69383c9102aee, but it probably has to be done in a different way.

**Comment by ksooo** [comment]
> @ksooo I think some work toward fixing that was done in b54af84, but it probably has to be done in a different way.

 That's imo another story.

What additionally is missing (at least I think so, will test later tonight) is resetting <code>m_timeshiftStatus</code> in <code>CHTSPDemuxer::Abort0</code> (https://github.com/kodi-pvr/pvr.hts/blob/master/src/HTSPDemuxer.cpp#L74).

**Comment by bconway** [comment]
Thanks!
