### ISSUE TITLE
KODI PVR for TVHEADEND installed but won't run

### ISSUE THREAD

**Issue by richardtempleman** [kodi-pvr/pvr.hts#296]
My setup is: Ubuntu 16.04 on desktop
 KODI 17.1 installed from the Ubuntu software within the last month,.
Backend is  tvheadend 4.0.8
PVR is  kodi-pvr-tvheadend-hts 3.4.17   This was pre-installed in KODI 17.1

The problem is the PVR wont run.  (It has an "X" against it in the PVR addons List)

The PVR is in the pvr-addons list but after configuring it won't run.
The 

I can view TV channels OK in tvheadend using VLC and can view videos OK. So its just the TV which wont work.

I have looked in the KODI log but couldn't see any relevant error messages.

I Have KODI 17.1 running on windows 8.1 on the same PC (Dual boot) so the hardware is all OK.

Any help would be much appreciated.

**Comment by Jalle19** [comment]
Addons are not preinstalled on Ubuntu. The package name for the addon changed a few years ago too, so try `sudo apt-get install kodi-pvr-hts` then restart Kodi.

**Comment by Jalle19** [comment]
Also please use the forum in the future for support tickets, we only use GitHub issues for bugs.

**Comment by richardtempleman** [comment]
OK, I'll use the forum.
Thanks

**Comment by richardtempleman** [comment]
which forum are you referring to, please.

**Comment by CvH** [comment]
@richardtempleman http://forum.kodi.tv/forumdisplay.php?fid=168
