### ISSUE TITLE
Aborted vs. Stopped recording

### ISSUE THREAD

**Issue by rndmerle** [kodi-pvr/pvr.hts#299]
With Tvheadend 4.2 there are now both a Stop and an Abort actions on a current recording.
"Stop" action ends the recording and keeps it, while "Abort" ditches the recording.
It seems the TVH client still issues the legacy stop action when, in Kodi, I stop a recording, but I guess it should issue the new Stop action.

There is a side effect to it : the client issues a stop action but the 4.2 server gets it as an Abort action so the server trashes the recording to the Failed Recordings section. It seems it confuses the client because on the Kodi UI still shows the program being recorded, and the entry shoes up in the Recordings list but can't be read. When I restart Kodi it eventually says the recording ended.

Not sure I made the problem clear enough.

**Comment by Jalle19** [comment]
So essentially you're saying we should send the "Stop" action, not the "Abort" action when a recording is stopped from Kodi?

**Comment by rndmerle** [comment]
Yes, beucase as I understand it, the new Stop action is like the old and unique Abort one.
The new Abort action is removing the recording and imo it's not what you want to achieve when you stop a recording on Kodi, you want to keep it.

**Comment by Jalle19** [comment]
I'm using 4.0 myself so I've never thought of this. Is this a new thing in 4.2 or has it been like this all along?

**Comment by rndmerle** [comment]
Yes it's new to 4.2.
For instance in src/webui/static/app/dvr.js code there is, along abortButton, a new stopButton.

But I spent an hour to track down the issue and it's not related to those buttons.
Actually it's a rights issue. There is a new "Failed view" flag in the Video recorder access rights (ae_failed_dvr in the sources), and it's unchecked by default. So the aborted recordings can't be read by the client.

That's an issue for TVH server indeed so I'll head over there.
Thanks for your time.

**Comment by Jalle19** [comment]
Okay, but are you saying recordings still get deleted if they are stopped from Kodi and tvheadend 4.2 is used, regardless of access rights?

**Comment by rndmerle** [comment]
Nope they're not deleted. Just moved to the failed recordings and still readable.

The only concern for the client imo is whereas stopping a recording should issue an Abort command (like before) or the new Stop command.

**Comment by Jalle19** [comment]
Oh yeah, I think I remember the discussion about this when it was implemented. Kodi doesn't have a concept of failed recordings (they are either in progress or done) so it's perhaps not that big of a deal, although it sounds like the new stop command is what should be issued since it's not technically a "failure" if you press stop.

**Comment by Glenn-1990** [comment]
Using "stop" can be dangerous, a stopped recording will be listed as "succeeded". This will prevent duplicate detection code from kicking in. 

It just depends on what the user finds the correct behaviour.
1) abort in kodi = abort in tvheadend, and rerecord later on (if settings are on)
2) abort in kodi = stop and never rerecord the full show. You will be left with an incomplete show.

**Comment by ailin-nemui** [comment]
> It seems it confuses the client because on the Kodi UI still shows the program being recorded, and the entry shoes up in the Recordings list but can't be read.

this is the biggest problem :( whether we mark it as failed or succeeded would seem less important to me

**Comment by FernetMenta** [comment]
If you stop an instant recording in Kodi, Kodi still displays the recording icon. In the log this error appears:
ERROR: GetRecording: Unsupported item type!

**Comment by ksooo** [comment]
> If you stop an instant recording in Kodi, Kodi still displays the recording icon. 

 Could you please explain a bit more in details how you schedule the instant recording, how you stop it and where exactly it is still displayed as "recording" after stop. There are so many ways to start/stop recordings and many places with recording indicators...

**Comment by ksooo** [comment]
Hmm, just tried exactly what you described several times. Cannot reproduce. Works just fine here. Which tvh, pvr.hts and kodi version are you using (a debug log might be helpful)?

**Comment by FernetMenta** [comment]
I run Kodi master branch, pvr.hts v4.4.12, tvh 4.3 (unstable repo). A friend of mine has brought this to my attention. He runs a Kodi version v18 RC? and I think tvh 4.2 from stable repo.

**Comment by Glenn-1990** [comment]
Don't know if this is the cause, but in any case "failed view" acces should be enabled for kodi usage.
![screenshot_20190204_204117](https://user-images.githubusercontent.com/2036512/52232784-b4dfb300-28bd-11e9-8229-008b140929d2.png)
Some tvheadend versions are defaulting to checked and some to unchecked.

**Comment by ksooo** [comment]
> I run Kodi master branch, pvr.hts v4.4.12, tvh 4.3 (unstable repo). A friend of mine has brought this to my attention. He runs a Kodi version v18 RC? and I think tvh 4.2 from stable repo.

 So, the problems occurs with 4.2 and 4.3 ?

**Comment by Glenn-1990** [comment]
From tvheadends point of view, failed recordings will be rerecorded if possible (and setting is enabled), successful recordings of course not. However the naming 'failed' should better be 'aborted' of something similar.

**Comment by FernetMenta** [comment]
IMO a stopped instant recording is neither aborted nor failed. It is finished as desired. User hits the button when he wants it to start and again when he wants it to stop.

**Comment by ksooo** [comment]
@FernetMenta never thought about that, because it was always like that, but I fully agree with you.

And I just discovered that tvheadend htsp API not only provides "canceldvrentry" but also "stopdvtentry". 

I will test whether this method does what we want and change pvr.hts in case.

**Comment by Glenn-1990** [comment]
I also agree that "stop" fits better in this case. But "cancel" is historical, it was the only method in older tvheadend versions, so we might need a setting and/or version check here.

**Comment by ksooo** [comment]
Do you now since when "stop" is available?

**Comment by ksooo** [comment]
To answer my own question: It was added with this commit: https://github.com/tvheadend/tvheadend/commit/b1e89e6f36fe75104cb9785cfab7e7e0f347e13c#diff-bb110a0c4c00627cea894e60917a86e8

unfortunately without bumping htsp version, which stood at 25. :-/ 

So, best we can do is check that htsp version > 25 and if it is we can use stopDvrEntry.

**Comment by ksooo** [comment]
The real question is how we decide in the addon when to call stop and when cancel without having these different options in Kodi... Any thoughts?

**Comment by felix-wo** [comment]
I’m coming from here, maybe my error report is of any help, although the point seems to be clear …

What about offering the user a toggle to switch the plugin manually to the right behaviour (which is to stop and to keep a recording when the record button is pressed the second time)?

**Comment by ksooo** [comment]
The log in your forum post clearly tells you that you have to fix your tvheadend access rights like written earlier in this PR.

**Comment by timpatt** [comment]
I've got exactly the same issue as @FernetMenta outlines above:
> Any further attempt to stop/deactivate this recoding results in error messages.

I'm running tvheadend 4.2.8 and kodi tvh plugin 4.4.18.

> The real question is how we decide in the addon when to call stop and when cancel without having these different options in Kodi... Any thoughts?

I suspect that we can't automatically determine success or failure without user input - and I'm pretty sure we don't want to ask the user every-time you stop a recording if it failed or not (and I suspect this is not something that can be added by the plugin itself, in any case?)...   Also - if you're stopping recordings all the time because they're failing, you've probably got bigger problems - so I'd suggest that the default should be "success", although perhaps the default could be set in the plugin configuration page?

Solving the larger problem of managing success/failure state of recordings probably involves more Kodi-PVR-level work, which I'm guessing it outside of the scope of this plugin.

**Comment by danryu** [comment]
> The real question is how we decide in the addon when to call stop and when cancel without having these different options in Kodi... Any thoughts?

Just run into this problem now with a new setup:
tvheadend 4.2.4
kodi 18.2
kodi tvh plugin 4.4.18

In (late) response to your question @ksooo , I would think that the default behaviour should simply be to Stop any current Instant Recording. If the user wishes to remove that recording afterwards it's a simple process to delete from Tvh.
In other words I agree with @FernetMenta - I think this is most users' expected behaviour.

**Comment by ksooo** [comment]
What about recordings started via a timer or timer rule (autorec/timerec) and not manually by the user from inside Kodi ? Should we tell tvh to abort or stop if the user "stops" this kind of recording from the Kodi UI (context menu etc.)?

**Comment by danryu** [comment]
If a recording has not manually been initiated in Kodi, I would say that sensible behaviour is just to flag up a notification of "Not Possible" when the user attempts to stop it from Kodi. The user can just go to wherever they scheduled the recording in the first place to cancel it, if that's what they want.
Maybe in the future, pressing Record stop could give an option:
- just stop this recording?
- cancel the timer that set the recording?

But for Instant Recordings, I think it makes good sense to just Stop the recording there, as @FernetMenta said.

(Without looking at the code I'm just presuming it's possible to differentiate these scenarios logically.)

**Comment by ksooo** [comment]
All kind of timers can be scheduled from inside. Kodi. So, "not possible" to stop is imo a no go.

**Comment by danryu** [comment]
Right. I haven't even looked at the relevant code so was just speculating that it was possible to "introspect" on the current recording type and to send an appropriate action as a result.

Is it really not possible to send an alternative action for Instant Recordings? If not, it seems we should find a more sensible default than to error out and leave us with stale recording files that need to be picked out and removed/handled manually ...
The add-on in general is working great, by the way.

**Comment by ksooo** [comment]
We will always use "stop" when available (tvh server htsp version >= 26), "cancel" otherwise"
