### ISSUE TITLE
Segfault when playing recording

### ISSUE THREAD

**Issue by map7** [kodi-pvr/pvr.hts#301]
I'm using kodi-pvr-hts 3.4.24-dmo1 on kodi 17.1-dmo1 through Debian Testing. Since this update every time I try to play a recording through Kodi it segfaults.

I've included the logfile and an strace from a fresh profile where I go an try and play a Dr Phil episode.
[kodi_log_files.zip](https://github.com/kodi-pvr/pvr.hts/files/1000025/kodi_log_files.zip)

**Comment by Jalle19** [comment]
Unfortunately we don't support the versions of Kodi that Debian Multimedia ships (apparent from the `17.1-dmo1` package name) since they make a lot of modifications to it, especially the video playback parts.

Please re-open this issue if you can reproduce with an official version of Kodi.
