### ISSUE TITLE
Error when trying to schedule recording from EPG

### ISSUE THREAD

**Issue by pikim** [kodi-pvr/pvr.hts#306]
Hello,

most of the time I get the following error messages when I try to schedule a new recording in the EPG view on specific channels:
```
22:25:24.050 T:140076002109824   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command addDvrEntry failed: Channel does not exist
22:25:24.050 T:140076002109824   ERROR: PVR - AddTimer - addon 'HTS Tvheadend:127.0.0.1:9982' returned an error: server error
22:25:24.050 T:140076002109824   ERROR: PVR - AddTimer - cannot add timer to client '2025648334': server error
```
Most often this happens when I try to record something on 'ProSieben'. While I get the above message on one entry, the next/ previous entry may cause no problem.

Maybe some consecutive entries work without any problem, sometimes some consecutive entries lead to the error.

I wasn't able to identify any pattern, yet - it seems to be completely random.

**Comment by Glenn-1990** [comment]
Can you try with "async epg" enabled in addon settings?

EPG data can be outdated/invalid without this setting on, causing such issues.

**Comment by pikim** [comment]
Thanks very much for that suggestion. I changed the setting and had no problems since then. I'll observe this for a while and reopen this issue if the problem occurs again.
