### ISSUE TITLE
pvr.hts 3.4.23.1 addon freezes complete libreelec/kodi

### ISSUE THREAD

**Issue by tuxedo0801** [kodi-pvr/pvr.hts#307]
Hi there,
I'm using kodi mostly for watching live-tv, provided via tvheadend.
Works like a charm so far on both boxes (Wetek Play 2 + MXQ Pro 4k).
BUT ... If I leave the boxes with TV playing over night (kodi box is running, pvr.hts addon is playing tv, BUT Display/TV-Screen is switched off) kodi freezes on both boxes (but not at the exactly same time)

What I have found out so far:

* Box is not responding to the remote anymore 
* SSH server is no longer reachable
* Image on the screen is frozen and rarely (over several minutes) gets updated, but only sometimes.
* Pinging the box is still possible. That's all. I have to unplug/replug the power to get it back to working state.
* If I enable kodi debug logging upfront, I can see that kodi consumes about 180% cpu when freeze happens (box is a 4-core system)
* There's no difference between SD, HD and/or paytv-channels (Astra HD+). All freeze the box the same way.
* If I stop playing live TV before going to bed (press the stop-button on the remote to stop live TV and go back to kodi main menu) both boxes survives the night.

My consumption: hts.pvr addon is causing this issue

Both boxes are using libreelec 8.0.1k
Both boxes are using hts.pvr addon version 3.4.23.1.
Both boxes are connected via wired LAN to the 1000mbit network.
The thveadend server (debian linux running tvheadend 4.2.2-1~g82c8872) is not affected so far. Runs just fine.

I wil try latest release (3.4.24). Beside that: Are the any hints that I can try to solve the problem?
Is this problem already known? Someone else having the same issue?

**Comment by Leatherface75** [comment]
You could try upgrade to libreelec 8.0.2 with Kodi 17.3 in it.

**Comment by tuxedo0801** [comment]
I updated my mxq pro box to 8.0.2 (http://kszaq.libreelec.tv/s905/8.0.2a/)

We will see if this changes anything. the pvr.hts addon is still the same version 3.4.23.1 :-(

I also have a kodi debug log, which now should contain pvr.hts debug information. I will check this and provide the file for further analysis.

**Comment by Leatherface75** [comment]
Only difference i can see in 3.4.24 is translations so nothing will change in that version.

https://github.com/kodi-pvr/pvr.hts/commit/4e2a8334d4e62e63720a33a18c3e3c7ff4b4ad0b

**Comment by tuxedo0801** [comment]
libreelec 8.0.2 did not solve the issue. Not on the MXQ Pro, not on the Wetek Play 2. 

I capture in the wetek play2 a debug log with additional debug information from the pvr.hts addon. It's 1,8GB big. Have to check if there#s something relevant in it. 
Compressed it's still about 113MB. So I will see if I can filter something out to reduze the size and post it here.

**Comment by Jalle19** [comment]
Chances are something unrelated to this addon is broken if the log file is that big.

**Comment by tuxedo0801** [comment]
The timestamps in the log stopps at about the time the freeze happend. 

And again:
The freeze only happens when live-tv is played over long time via this addon. If I simply stop the live-stream (stop-button on remote), the addon/kodi survive the night without any issues.

I checked the log: Nothing special that indicates a problem that "just happened". Maybe a kind of memory/handle/whatever leak?

I installed Kodi on my desktop computer as well and started live-tv ... and guess what:  
It does als not survive the night. No matter which channel is playing.
The only difference is: the console/shell in which I started Kodi manually shows "killed", nothing more. 

As this issue is more or less reproducible on three (!) different hardware, I assume this is not related to my setup.

I would be glad if anyone out there could try the same and tell if the issie is reproducible.

**Comment by Jalle19** [comment]
"Killed" means the kernel killed Kodi because it was using too much memory. The fact remains that if your log file becomes 1,8 GB in size over night there's something else going on. You said there's nothing special but surely there must be some repeating pattern in it?

**Comment by tuxedo0801** [comment]
As I wrote: It's a "kodi debug enabled" log file and I also enabled "debug" in the addon-config.
So of course there's a lot of data. 
I hereby attach the last 100 lines of the 1,8GB log file. 
This has been captured with both (kodi and addon) in debug, with kodi 17.3/libreelec 8.0.2, installed on wetek play 2"

--> [last100.txt](https://github.com/kodi-pvr/pvr.hts/files/1044924/last100.txt)

**Comment by tuxedo0801** [comment]
The last 10.000 look a bit different:

[last10000.txt](https://github.com/kodi-pvr/pvr.hts/files/1044950/last10000.txt)

**Comment by tuxedo0801** [comment]
The "kill" just happens on my desktop machine. The other ARM-based boxes just freeze as described.

**Comment by Jalle19** [comment]
Does it also crash if you disable trace debugging in the addon settings?

**Comment by Jalle19** [comment]
Also do you have a crash log somewhere on your computer? They're usually generated in your home directory, i.e. `/storage` on LibreELEC.

**Comment by tuxedo0801** [comment]
Yes, it does also crash. I just enabled logging to hopefully see what's causing this crash or freeze.


log from desktop, showing last 100 lines:
[last100desktop.txt](https://github.com/kodi-pvr/pvr.hts/files/1047659/last100desktop.txt)

**Comment by Jalle19** [comment]
Did you find any crash logs?

**Comment by tuxedo0801** [comment]
Found the crash-log on my debian desktop machine:

[kodi_crashlog-20170518_191020.log.txt](https://github.com/kodi-pvr/pvr.hts/files/1051524/kodi_crashlog-20170518_191020.log.txt)

I'm not sure if this is the same reason/issue as on my ARM-based boxes. 
There's still the question open: Is anybody facing the same hang/freeze issues on mxqpro/wetek play 2/.... boxes with latest kodi/libreelec.

**Comment by MilhouseVH** [comment]
If the ARM boxes are frozen (and not in the process of crashing and creating a core dump which can take a few minutes on ARM) then use `kill -SIGSEGV $(pidof kodi.bin)` to force a crashlog to be generated. Once Kodi has restarted (GUI has reappeared), the crash log will be will be available and called `/storage/.kodi/temp/kodi_crash.log`.

Disable whatever debug logging is creating such a huge log file size in order that you are able to upload the whole crashlog rather than a snippet.

**Comment by tuxedo0801** [comment]
Both ARM boxes are not useable at all if they freeze (no matter what kind of log-setting you use). You can't login via SSH (takes ages). Even if you have the patience and manage to get logged in, you can't type anything. System is frozen like the arctic (I used to write "hell", but hell is far to hot ;-) ).

So, what else could I do?

**Comment by MilhouseVH** [comment]
> So, what else could I do?

If the entire box is frozen it could be the system is out of memory in which case wait for Kodi to be killed by the OOM process killer (it can take a while - leave overnight if necessary, just to be sure).

**Comment by MilhouseVH** [comment]
Also see edit in my first comment about the OOM process killer.

**Comment by tuxedo0801** [comment]
@MilhouseVH 
It would help if you read the whole thread....

System requires an "over night" to become frozen. There's nothing killed at all, it just keeps frozen.

I'll try to write a kind of "monitoring script" that hopefully is able to kill kodi like you mentioned if PCU load is "too high" (=frozen). 
Hopefully there are enough cpu cycles to get things killed.

**Comment by MilhouseVH** [comment]
Ok good luck.

**Comment by tuxedo0801** [comment]
I found a crash log on my MXQ Pro box, but I have no idea if it's freeze-related:
[kodi_crashlog_20170518185450.log._mxq_pro.txt](https://github.com/kodi-pvr/pvr.hts/files/1051893/kodi_crashlog_20170518185450.log._mxq_pro.txt)

Can someone with some knowledge about that kind of stuff look into?

I now have also a shell-script running that watches CPU+MEM and kills kodi as suggested if CPU or MEM usage is too high (hopefully detects the freeze and is able to execute):

/storage/watch.sh
```bash
#!/bin/sh

CPU_LIMIT="175"
MEM_LIMIT="40"


PROCNAME="kodi.bin"
KODIPID=`pidof $PROCNAME`
echo "KODI PID=$KODIPID"

while true; do

#echo "Measure ..."

#top -b -n 1 -p $KODIPID

CPU=`top -b -n 1 -p $KODIPID | grep "$PROCNAME" | awk '{print $9}'`
MEM=`top -b -n 1 -p $KODIPID | grep "$PROCNAME" | awk '{print $10}'`

# convert float to integer
CPU=`printf "%.0f" $CPU`
MEM=`printf "%.0f" $MEM`

NOW=`date`

echo "[$NOW] CPU=$CPU LIMIT=$CPU_LIMIT - MEM=$MEM LIMIT=$MEM_LIMIT";

if test $CPU -gt $CPU_LIMIT
then
        echo "$NOW KILLED due to CPU: CPU=$CPU LIMIT=$CPU_LIMIT MEM=$MEM LIMIT=$MEM_LIMIT" >> /storage/watch.log
        echo "$NOW killed toe to cpu!";
        kill -SIGSEGV $KODIPID
        exit;
fi

if test $MEM -gt $MEM_LIMIT
then
        echo "$NOW KILLED due to MEM: MEM=$MEM LIMIT=$MEM_LIMIT CPU=$CPU LIMIT=$CPU_LIMIT" >> /storage/watch.log
        echo "$NOW killed due to mem!";
        kill -SIGSEGV $KODIPID
        exit;
fi
sleep 60
done
```

Simply run it via SSH:

`nohup /storage/watch.sh`


I will report back if I get another crash log ...

**Comment by Jalle19** [comment]
The desktop crash is potentially something specific to the Debian builds since they change a bunch of stuff to confirm with DFSG.

The second crash looks like some bad JSON-RPC request. Obviously a bad request shouldn't kill Kodi, but it's hard to tell without knowing what request it was and what made it.

**Comment by tuxedo0801** [comment]
Normally the box freezes somewhen in the night, when everybody is sleeping. 
This single crash log is a bit old, and the crash is also not during night. No idea what happened.

Currently my MXQ Pro Box is running with my watch-script. Hopefully we will get some information soon. 

If the issue is not caused by hts-pvr addon, it must be caused by kodi, but IN COMBINATION with the addon. 

Kodi is running fine for days without the addon. And the addon also runs fine fine for days when live-tv is stopped.

**Comment by Jalle19** [comment]
It could also be something in Kodi that's only triggered when you play live TV. This addon is just a minor part of the whole PVR infrastructure.

**Comment by tuxedo0801** [comment]
> It could also be something in Kodi that's only triggered when you play live TV.

That's why I've written:

> it must be caused by kodi, but IN COMBINATION with the addon.

Because Kodi itself runs fine for days.

My watch-script was not completely successful. I was not able to catch the freeze-moment and kill kodi to create a crashlog. But I'm able to show, that there's something going wrong with memory consumption:

> [Thu Jun  8 16:35:54 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:36:24 CEST 2017] CPU=33 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:36:55 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:37:25 CEST 2017] CPU=20 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:37:55 CEST 2017] CPU=40 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:38:26 CEST 2017] CPU=25 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:38:56 CEST 2017] CPU=31 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:39:26 CEST 2017] CPU=33 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:39:57 CEST 2017] CPU=20 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:40:27 CEST 2017] CPU=33 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:40:58 CEST 2017] CPU=19 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:41:28 CEST 2017] CPU=20 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:41:58 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:42:29 CEST 2017] CPU=25 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:42:59 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:43:29 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:44:00 CEST 2017] CPU=38 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:44:30 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:45:00 CEST 2017] CPU=81 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:45:31 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:46:01 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:46:32 CEST 2017] CPU=20 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:47:02 CEST 2017] CPU=33 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:47:32 CEST 2017] CPU=38 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:48:03 CEST 2017] CPU=33 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:48:33 CEST 2017] CPU=19 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:49:03 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:49:34 CEST 2017] CPU=31 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:50:04 CEST 2017] CPU=50 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:50:35 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:51:05 CEST 2017] CPU=25 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:51:35 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:52:06 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:52:36 CEST 2017] CPU=60 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:53:06 CEST 2017] CPU=27 LIMIT=175 - MEM=12 LIMIT=90
> [Thu Jun  8 16:53:37 CEST 2017] CPU=20 LIMIT=175 - MEM=14 LIMIT=90
> [Thu Jun  8 16:54:07 CEST 2017] CPU=19 LIMIT=175 - MEM=20 LIMIT=90
> [Thu Jun  8 16:54:37 CEST 2017] CPU=20 LIMIT=175 - MEM=25 LIMIT=90
> [Thu Jun  8 16:55:08 CEST 2017] CPU=12 LIMIT=175 - MEM=31 LIMIT=90
> [Thu Jun  8 16:55:38 CEST 2017] CPU=20 LIMIT=175 - MEM=36 LIMIT=90
> [Thu Jun  8 16:56:09 CEST 2017] CPU=20 LIMIT=175 - MEM=41 LIMIT=90
> [Thu Jun  8 16:56:39 CEST 2017] CPU=27 LIMIT=175 - MEM=46 LIMIT=90
> [Thu Jun  8 16:57:09 CEST 2017] CPU=20 LIMIT=175 - MEM=52 LIMIT=90
> [Thu Jun  8 16:57:40 CEST 2017] CPU=20 LIMIT=175 - MEM=57 LIMIT=90
> [Thu Jun  8 16:58:10 CEST 2017] CPU=20 LIMIT=175 - MEM=62 LIMIT=90
> [Thu Jun  8 16:58:40 CEST 2017] CPU=19 LIMIT=175 - MEM=68 LIMIT=90
> [Thu Jun  8 16:59:11 CEST 2017] CPU=19 LIMIT=175 - MEM=73 LIMIT=90
> [Thu Jun  8 16:59:41 CEST 2017] CPU=20 LIMIT=175 - MEM=79 LIMIT=90
> [Thu Jun  8 17:53:50 CEST 2017] CPU=100 LIMIT=175 - MEM=81 LIMIT=90

At the beginning of the watchscript-log, there was a stable memory consumption of 12%. For hours, there was no change at all (beside CPU which floats a bit). But then, the consumption raised rapidly to >=81%, and then the logs stopps (due to freeze).

I now lowered the mem-limit from 90% to 80% and repeat the whole test. Maybe I then can create a crashlog.

But even if the crashlog get's created: It shows mainly the working threads. There's a chance that we can't see whats causing the mem-leak, or?

I still advise that someone with more debugging/analyzing skills tries to reproduce the issue or at least tell me what to do to create a kind of memory-dump or so...

**Comment by mercora** [comment]
Hello, i just want to say that i got the exact same behavior on similar hardware. It has "MXQ Pro T95N" written on top of it but i think it is more or less the exact same device. I haven't tested yet what happens if playback is stopped during the night but will do so today. Actually installing some sleep timer addon would be a good workaround in my case. If there is anything i could help with debugging this issue i am willing to get it done.

**Comment by stefansaraev** [comment]
@tuxedo0801 @mercora 

> Box is not responding to the remote anymore
> SSH server is no longer reachable

I have a bad news for you guys. your freezes have nothing to do with pvr.hts. they are most likely due to a hardware or amlogic kernel issue

**Comment by tuxedo0801** [comment]
This also happens on Wetek Play 2 boxes. Have not yet checked which chip is used there.

**Comment by tuxedo0801** [comment]
And to mention again: even my Linux desktop PC does not survive an overnight playback. Kodi crashes due to me reasons.

**Comment by tuxedo0801** [comment]
@stefansaraev  If issues is caused by amlogic or kernel: why does it only happen when doing playback for a long time? GPU issue? Do you have any further information or links?

**Comment by stefansaraev** [comment]
god knows. could be an unhandled pts wrap. could be kodi core issue. could be everything. does it work with sw decoding? does it work with different pvr backend (vdr?) why do you think it is pvr.hts issue?

**Comment by stefansaraev** [comment]
fyi, on wetek play 2, sometimes hw (both mpeg-2 and h264) decoding is miserably broken for me with kodi v18 after few hours of live playback. I dont have a dmesg output for you now, but last time I checked, it was related to de-interlacing. rebooting the box solves the issue. not rebooting it makes it freeze

**Comment by BJMg** [comment]
I am experiencing very similar issue with my Wetek Play 2. More info https://forum.libreelec.tv/thread/8990-libreelec-8-0-2-freezes/

My pvr.hts version is 3.4.24

**Comment by CvH** [comment]
log for this ^^^^^ problem https://pastebin.com/4tWmGumw
```
DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - demux unhandled subscription message [descrambleInfo]
DEBUG: CAMLCodec::Decode: ret: 0, sz: 0, dts_in: 18442240474082.1797[AC0], pts_in: 18442240474082.1797[4300], adj:2147483648, ptsOut:23858.5996, amlpts:2147274000, idx:3413763, timesize:2.0400
DEBUG: Previous line repeats 1010 times.
```

**Comment by stefansaraev** [comment]
cc @peak3d then

https://github.com/LibreELEC/LibreELEC.tv/blob/libreelec-8.0/packages/mediacenter/kodi/patches/kodi-999.16-amlogic_timing.patch

**Comment by BJMg** [comment]
I made another log with more info (there some new messages at the end). It might help. This log started a few minutes before memory of kodi.bin starts to grow.

https://pastebin.com/Bp5EwmnR

**Comment by snickers2k** [comment]
same here with newest libreelec and raspberry .. sometime it works 48hours, sometime it crashes after 4 hours or so .. i'll check for logs to post

**Comment by peak3d** [comment]
@BJMg what is the exact kodi version you use?

**Comment by CvH** [comment]
@peak3d `(17.3 Git:147cec4)`
complete log https://pastebin.com/4tWmGumw

**Comment by BJMg** [comment]
I am using 17.3. Official LibreELEC 8.0.2

**Comment by peak3d** [comment]
I'll overwork the PTS swap logic / seems to be not Ok.

**Comment by lorenz** [comment]
I experience the same freeze on a Kodi 17.4 (Ubuntu-based) system. Used GDB to trace it back to a deadlock between this thread:

```
Thread 20 (Thread 0x7ff7361f6700 (LWP 1166)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ff7c6002f8a in __GI___pthread_mutex_lock (mutex=0x7ff7584b45a0) at ../nptl/pthread_mutex_lock.c:115
#2  0x00007ff736a0ec56 in CHTSPConnection::GetProtocol() const () from /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.3.4.27
#3  0x00007ff736a3b45c in tvheadend::Subscription::ParseSubscriptionStatus(htsmsg*) () from /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.3.4.27
#4  0x00007ff736a1d9cf in CHTSPDemuxer::ProcessMessage(char const*, htsmsg*) () from /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.3.4.27
#5  0x00007ff736a25a50 in CTvheadend::ProcessMessage(char const*, htsmsg*) () from /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.3.4.27
#6  0x00007ff736a10495 in CHTSPConnection::ReadMessage() () from /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.3.4.27
#7  0x00007ff736a11ddf in CHTSPConnection::Process() () from /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.3.4.27
#8  0x00007ff736a16ed3 in P8PLATFORM::CThread::ThreadHandler(void*) () from /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.3.4.27
#9  0x00007ff7c60006da in start_thread (arg=0x7ff7361f6700) at pthread_create.c:456
#10 0x00007ff7beea4d7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```
and this thread:
```
Thread 67 (Thread 0x7ff6d51a6700 (LWP 2240)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ff7c6002f8a in __GI___pthread_mutex_lock (mutex=0x7ff7584b23d0) at ../nptl/pthread_mutex_lock.c:115
#2  0x00007ff736a1aa89 in CHTSPDemuxer::ResetStatus() () from /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.3.4.27
#3  0x00007ff736a1b905 in CHTSPDemuxer::Open(unsigned int, tvheadend::eSubscriptionWeight) () from /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.3.4.27
#4  0x00007ff736a26b03 in CTvheadend::DemuxOpen(PVR_CHANNEL const&) () from /usr/lib/x86_64-linux-gnu/kodi/addons/pvr.hts/pvr.hts.so.3.4.27
#5  0x0000557d499862af in PVR::CPVRClient::SwitchChannel(std::shared_ptr<PVR::CPVRChannel> const&) ()
#6  0x0000557d49bb6ef5 in PVR::CPVRClients::SwitchChannel(std::shared_ptr<PVR::CPVRChannel> const&) ()
#7  0x0000557d49bd2b54 in PVR::CPVRManager::PerformChannelSwitch(std::shared_ptr<PVR::CPVRChannel> const&, bool) ()
#8  0x0000557d49bd2f07 in PVR::CPVRManager::ChannelSwitchById(unsigned int) ()
#9  0x0000557d493f3de9 in CDVDInputStreamPVRManager::SelectChannel(std::shared_ptr<PVR::CPVRChannel> const&) ()
#10 0x0000557d49471fdb in CVideoPlayer::HandleMessages() ()
#11 0x0000557d4947270e in CVideoPlayer::Process() ()
#12 0x0000557d496b74a5 in CThread::Action() ()
#13 0x0000557d496b7719 in CThread::staticThread(void*) ()
#14 0x00007ff7c60006da in start_thread (arg=0x7ff6d51a6700) at pthread_create.c:456
#15 0x00007ff7beea4d7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```

This blocks the UI from updating. I have not looked into the code yet, will do that as soon as I have time.

**Comment by BJMg** [comment]
I am no longer experiencing this bug ever since I started using leia build. https://forum.libreelec.tv/thread/4248-libreelec-krypton-leia-agile-build-for-odroid-c2-rock64-wetek-hub-wetek-play2/

**Comment by lorenz** [comment]
@BJMg Thanks for the information, I will try a Kodi 18-agile build.

**Comment by Grolken** [comment]
I have the same problem on a Wetek Play, HTS version 3.4.23.1
Have anyone found an easy solution for the problem except a new build?

**Comment by sbfss** [comment]
Any news? Same happens on Raspberry pi 3+. Sometimes Kodi survive the night but when I switch to another channel, Kodi starts buffering and freeze with 100% progress. I will try get the logs.

**Comment by lorenz** [comment]
Basically the solution is to build Kodi 18. It is a far superior system at this point anyways. I'd actually go for the GBM version if you have a proper mainline kernel on your RPI3, it performs better.

**Comment by ksooo** [comment]
Is this still an issue with latest Kodi v19 nightly builds and latest tvh4.3 buolds? If I get no response within two weeks, I will close this issue.

**Comment by lorenz** [comment]
I've never seen it again since Kodi 18. I'm pretty certain it's fixed.

**Comment by tuxedo0801** [comment]
Yes, seems to be fixed.
