### ISSUE TITLE
Remove the "this is unstable software" disclaimer

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.hts#309]
This is the opposite of unstable

**Comment by tuxedo0801** [comment]
For me it's actually unstable ;-) See #307

**Comment by Jalle19** [comment]
@tuxedo0801 we have yet to determine that your issue is related to this addon at all

**Comment by ksooo** [comment]
"Fixed" with https://github.com/kodi-pvr/pvr.hts/commit/fe0a7ab94b8b4083605480a9a60b3e00a62a49e2
