### ISSUE TITLE
Some recordings not visible

### ISSUE THREAD

**Issue by DocMAX** [kodi-pvr/pvr.hts#311]
Hello,

some recordings aren't visible (59 out of 81).
No clue why. I already checked the "owner" of the recordings. They are all the same.

DocMAX

**Comment by DocMAX** [comment]
ok, i found something... i guess it's because i'm using git version of tvheadend server...

ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - malformed dvrEntryAdd/dvrEntryUpdate: unknown priority value 6
ERROR: Previous line repeats 23 times.

**Comment by DocMAX** [comment]
OK, and now i found the change:

https://github.com/tvheadend/tvheadend/commit/33cc05b37ee982c796936d7d143321f95e365724

Please adapt...

**Comment by mpmc** [comment]
I know this has been closed but I thought I'd leave a note here in case anyone else comes looking with the same issue. 

@perexg has added a version check to master to hopefully prevent this (inc a version bump). https://github.com/tvheadend/tvheadend/commit/a37d5bc6e97f69460ebd5f39a4cab3a728a0e862
