### ISSUE TITLE
Seperate Isengard from master  

### ISSUE THREAD

**Issue by Glenn-1990** [kodi-pvr/pvr.hts#32]
Time to create a Isengard branch as Isengard is in beta?

In this way, we can make the master branch ready for the upcoming series recording support and maybe add minimal autorec support through menu hooks without interfering with ksooo's work?

Minimal autorec supported is requested here:
http://forum.kodi.tv/showthread.php?tid=227249

I had a tvh addon with autorec support for helix and gotham. Pushed it to Isengard, but now with using menu hooks instead of custom dialogs.
https://github.com/Glenn-1990/pvr.hts/commit/c1e728fe90d0e4fa60e2ba3d6c32c4e87ca2034f

@ksooo @Jalle19 Your opinions?

**Comment by ksooo** [comment]
Currently I'm using all of my rare spare time for the series recording PR. There is still some work to do and I want it to merge in the master as fast as possible to have the chance to find any regressions early. 

No time for any activities beside this.

OTOH I'm not sure whether it would be better to put our limited resources on things that are not supposed to be thrown away in a couple of months. Our recruiting roadmap comes to mind as an example.

**Comment by ksooo** [comment]
s/recruiting/refactoring :-O

**Comment by Jalle19** [comment]
A branch is still a good idea, but it can also be created latee if the need to backport a fix arises.

**Comment by ksooo** [comment]
Sure. We should create an Isengard-branch for bugfixes (on-demand). Not sure, about features, though (as I wrote above).

**Comment by Jalle19** [comment]
As of yesterday there is a branch for Isengard.
