### ISSUE TITLE
FEATURE REQUEST:

### ISSUE THREAD

**Issue by Leatherface75** [kodi-pvr/pvr.hts#326]
Would be nice if you could have different profiles for each group for example.
Some groups i just want to use HTSP profile but some others i would like to use transcode profile.
Also it would be nice to be able to use pass profile too.

**Comment by Jalle19** [comment]
I don't think this is something that is feasible to add to the addon. If you have requirements like this you should probably try to do this on the backend side instead.

**Comment by Leatherface75** [comment]
And what's the reason for not adding support for pass profile in pvr.hts?
That's the only way to get subtitles on some channels while others only works with HTSP.
That's why i asked for different profiles support.
pass profile is also needed for some channels that not works with htsp and transcoding of some reason without problems.
With IPTV SimpleClient or opening m3u link directly they works fine because they use pass profile.

**Comment by Jalle19** [comment]
All types of subtitles should be supported with HTSP too, what type doesn't work for you?

The pass profile cannot be used with HTSP, it makes no sense really. HTSP is "untouched" just like the pass profile.

**Comment by Leatherface75** [comment]
Subtitles for hearing impaired on swedish SVT channels doesn't work for example.
Normally it's burned in but for swedish prgograms you need to activate subtitles.
That only works with VLC, IPTV SimpleClient, opening m3u file etc but not with pvr.hts addon because HTSP and transcoding profile removes it.
Same thing happens with closed captions in the US that already have been planned to be included in 4.6 but it works already if you use pass profile with VLC for example.
That's why i want to be able to use pass profile but then we have the problem that Teletext only works with HTSP profile on most other channels than SVT so that's why i need different profiles for different channelgroups for example or able to overide default on a few selected channels.

**Comment by Jalle19** [comment]
If subtitles are stripped when transcoding that's a tvheadend bug. Teletext subtitles work fine with HTSP in general.

Do you have to use transcoding?

**Comment by Leatherface75** [comment]
Yes it works fine normally except for some channels like SVT.
Tried to explain the problem for developer of TVheadend already.
I don't use transcoding i use HTSP but in some cases it would be good with pass for that subtitle problem.

**Comment by Jalle19** [comment]
Do you have a reference to tvheadend's issue tracker? It's technically possible that these types of subtitles have some minor difference compared to normal DVBSUB or TELETEXT subtitles which makes the addon handle them incorrectly, but without more information it's hard to tell.

Either way, this addon uses HTSP and the "pass" profile is only for HTTP, so what you're asking for cannot be implemented.

**Comment by Leatherface75** [comment]
When thinking again pass profile doesn't help with teletext only closed caption or maybe it's no support in Kodi for that either.
But still what makes it impossible in pvr.hts when IPTV SimpleClient can connect to tvheadend with pass profile?

**Comment by Leatherface75** [comment]
And there is streams that stutters when using htsp or transcoding profile when it works perfectly with pass profile.

**Comment by Jalle19** [comment]
> But still what makes it impossible in pvr.hts when IPTV SimpleClient can connect to tvheadend with pass profile?

The addon uses HTSP, all other methods of streaming from tvheadend uses HTTP. This is not something that is going to change. If HTSP doesn't work then there's a bug somewhere that needs fixing, and in this case it sounds like most of the issues are on the tvheadend side (especially since HTTP seems to work).

> And there is streams that stutters when using htsp or transcoding profile when it works perfectly with pass profile if you remember the talk for some year ago

Many things have changed in Kodi over the last few years, I wouldn't be surprised if streams that didn't work back then suddenly work now.

Anyway, this is not a support forum and this ticket is already closed. You should file bug reports against tvheadend if you want these issues fixed. If it turns out that there really is something in the addon that prevents some subtitles from working then reopen this issue with more information.

**Comment by Leatherface75** [comment]
It's not Kodi it's same issue with VLC etc if you use something else than pass profile on those streams.
And it has been working the whole time with those stremas when using IPTV SimpleClient but with pvr.hts client it doesn't because of HTSP profile. Same thing happens when transcoding.

**Comment by Jalle19** [comment]
For the third time, please make a bug report on tvheadend's bug tracker. If it doesn't work in VLC either then this is neither something Kodi nor this addon can do anything about.

**Comment by Leatherface75** [comment]
Yes it works with everything except for pvr.hts addon as long you use pass profile.

**Comment by Jalle19** [comment]
I couldn't find any related reports with a quick search, maybe you should open a new one.

**Comment by Leatherface75** [comment]
http://www.tvheadend.org/issues/3918
