### ISSUE TITLE
Refresh HTS after Kodi Wifi reconnect?

### ISSUE THREAD

**Issue by snickers2k** [kodi-pvr/pvr.hts#327]
Hey.
My Wifi-Repeater sucks some times and it's disconnecting from the wifi.
But even if the connection is back again, HTS is not connecting, until i disable/enable pvr.hts in the settings.
Maybe a refresh-interval or something would help to connect HTS as well, when kodi has a connection again. 

thanks

**Comment by ksooo** [comment]
Works like a charm here. If I disconnect my wifi while watching tv, the playback stops and some seconds after reconnecting my wifi playback continues.

**Comment by snickers2k** [comment]
wtf... what OS/Kodi you use? I'm using LibreELEC with latest Kodi

**Comment by ksooo** [comment]
pvr.hts and Kodi both implement reconnect on connection loss. So, nothing to fix. No idea what's going wrong on your end. Please describe your problem to the LibreELEC folks.

**Comment by CvH** [comment]
@snickers2k I had the same issue with K16 and earlier where every restart restart/reconnection from the Tvh daemon could lead to a Kodi crash etc. Since K17 this was entirely fixed for me and I use several WLAN attached clients. Pls open a thread at the LE forum with dmesg and logs - if there is a general problem we should find it :)

**Comment by nmaclean** [comment]
@snickers2k I fixed this by adding a simple sleep into the HTSPConnection. I noticed that my windows laptop doesn't have the issue but my libreelec boxes all do. The libreelec boxes connect but get this error back when sending the hello msg - PVR_CONNECTION_STATE_SERVER_MISMATCH. I assume its making an connection too early or something. A one second delay fixes it. 

diff --git a/src/tvheadend/HTSPConnection.cpp b/src/tvheadend/HTSPConnection.cpp
index 611875a..00db646 100644
--- a/src/tvheadend/HTSPConnection.cpp
+++ b/src/tvheadend/HTSPConnection.cpp
@@ -632,8 +632,12 @@ void* HTSPConnection::Process ( void )
     /* Create socket (ensure mutex protection) */
     {
       CLockObject lock(m_mutex);
-      if (m_socket)
-        delete m_socket;
+      if (m_socket){
+        free(m_socket);
+        m_socket = NULL;
+      }
+        
       m_connListener.Disconnected();
       m_socket = new CTcpSocket(host.c_str(), port);
       m_ready  = false;
@@ -643,7 +647,7 @@ void* HTSPConnection::Process ( void )
         m_challenge = NULL;
       }
     }
-
+    Sleep(1000);

**Comment by Jalle19** [comment]
Feel free to open a pull request if you're certain this fixes something

**Comment by CvH** [comment]
@nmaclean 
>I assume its making an connection too early or something

Is this different to activate `wait for network` at the LE settings? Kodi starts after network is established and all connections are available. Adding some random 1sec sleep sounds wrong.

**Comment by Jalle19** [comment]
The "wait for network" only applies during boot AFAIK

**Comment by CvH** [comment]
sry you are right, reconnect is ofc not handled by that

**Comment by ksooo** [comment]
<pre>
-      if (m_socket)
-        delete m_socket;
+      if (m_socket){
+        free(m_socket);
+        m_socket = NULL;
+      }
</pre>

This change is unrelated and definitely not correct. `m_socket` is allocated using `new`, thus it must be freed using `delete`.

**Comment by ksooo** [comment]
Looking at the code, the problem seems to be that https://github.com/kodi-pvr/pvr.hts/blob/master/src/tvheadend/HTSPConnection.cpp#L667 `Socket::Open` returns `true`and thus the 'wait and retry sequence on socket open error' is not initiated. IMO, we must look into this if we want to find the right fix.

**Comment by nmaclean** [comment]
> -      if (m_socket)
> -        delete m_socket;
> +      if (m_socket){
> +        free(m_socket);
> +        m_socket = NULL;
> +      }
> This change is unrelated and definitely not correct. `m_socket` is allocated using `new`, thus it must be freed using `delete`.
> 
> Assigning `NULL` to m_socket is not necessary as it will be assigned a new value two lines below and access is mutex protected.
> 
> Finally, inserting an unconditional wait of a second whenever a new connection is requested feels like a hack to me, not a real fix for the actual problem.

Agreed, the first change is due to a crash that only happens when you restart TVH, I assume its due to the connection being open and so trying to delete the m_socket. 

Agree with the second point as well. Let me look at it.

**Comment by ksooo** [comment]
Is this still an issue with latest Kodi v19 nightly builds? If I get no response within two weeks, I will close this issue.
