### ISSUE TITLE
Since Kodi 17 multiple HTS addons no longer work

### ISSUE THREAD

**Issue by stuartjbrown** [kodi-pvr/pvr.hts#329]
I'm currently using Kodi 16 at home (LibreELEC) and found some issues when I last tried upgrading to Kodi 17.  I'm running a (probably unsupported) configuration where I cloned the pvr.hts addon (and renamed various folders + config files) so I could use 2 TVH backends on 1 Kodi instance (1 remotely in the UK, 1 here in DE).  It's worked brilliantly but I'd quite like to be able to upgrade at some point.

The symptoms are that both add-ons appear to load ok, but the guide + channel listings are the duplicated entries from 1 of the 2 add-ons, instead of the combined list from both.

Obviously this was broken at some point in Kodi 17 development, I'm just wondering if it would be a relatively easy fix to get working again?  Thanks!

**Comment by ksooo** [comment]
This is an unsupported hack. Noting to fix.
