### ISSUE TITLE
Feature Request: Seperate make install target.

### ISSUE THREAD

**Issue by bas-t** [kodi-pvr/pvr.hts#331]
Hi, would you please consider to provide a "make install" target for your very nice addon (Leila and up, in Krypton I don't need it)?
This way I would be able to distribute the addon as a package to all my systems using checkinstall.
Thanks in advance,
Tycho

**Comment by Jalle19** [comment]
Can you not use the existing cmake build system?

**Comment by bas-t** [comment]
Yes of course and I did.
The make install command is only so I can produce a .deb package with checkinstall.
Chekinstall needs that command in order to registrate what file goes where and build a package with that info.

**Comment by bas-t** [comment]
To clarify a bit more: without the make install target, I can only install locally. Meaning that on each and every update I have to rebuild and install Kodi as well as the pvr.hts addon on all of my frontends.
My update scripts are designed to only rebuild on the fastest machine, synchronise the resulting .deb file(s) withe my personal apt repository and finally only do apt-get update && apt-get upgrade on all my low power frontends.

Mind you, I can live with the current situation, nevertheless, having a make install target (no fancy things, just repeating the install step) would make life a lot simpler.

So if it's not too much to ask: please consider adding the target.

**Comment by bas-t** [comment]
The difference between Krypton and Leila is that in Krypton I was able to cmake build the pvr.hts addon and install it into the kodi source PRIOR to building kodi with a './bootstrap ./configure make checkinstall' sequence, where checkinstall (in this sequence equivalent to make instal) would not only install kodi, but the pvr.hts addon as well.
The resulting .deb file would mimick this behaviour and thus install both kodi and the addon in one run.

Now, with Leila, that does not build with ./bootstrap etc anymore, I have to cmake build the pvr.hts addon AFTER building kodi. So afaik, there's no chance to create a single .deb file installing the lot in one run anymore.

No problem, two .deb files are serving me well: one for kodi and one for the pvr.hts addon.

But for that to happen, I need this make install target.

**Comment by Jalle19** [comment]
@wsnipex can you help this guy out? I'm not very familiar with packaging these days.

**Comment by bas-t** [comment]
@Jalle19
It's not so much a packaging problem though.
I'll try to explain in a better way.

It's like this: the recommended  cmake command, according to your readme:

cmake -DADDONS_TO_BUILD=pvr.hts -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/kodi-build/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons

(or a similar instruction with different prefixes and/or paths) produces a Makefile in the build directory of the pvr.hts addon that lacks a 'make install' target. When running 'make' it just builds AND installs the lot according to parameters used, 'make install' is not even available.

Those two steps, 'make' (or a more cmake-like instruction like 'cmake --build . -- -j2') and 'make install' should imho be separate targets in any Makefile, like in Kodi's Makefile.

So my request is to generate a better Makefle with the recommended (or similar) command BEFORE the 'make' step. Not so much to help me out with packaging.

Sorry for not being able to make myself clear enough up to this point.

**Comment by Jalle19** [comment]
Okay, I think I get it now. AFAIK there used to be a make install target at some point, maybe there's a way to resurrect it.

**Comment by bas-t** [comment]
Thanks for your patience.
And if one of the devs can resurrect the make install target, please do.
Thanks in advance.

**Comment by wsnipex** [comment]
all pvr addons already include debian packaging files. You just have to create changelog from changelog.in and run debuild.
We're not going to change our build system to accommodate simply wrong methods to create debs.

**Comment by bas-t** [comment]
@wsnipex there is never just one way to achieve a goal, so let's call my method just different from yours, not wrong. My method has served me perfectly well for over a decade.

Having said that, I get what I want anyway by renaming the 'all' target to 'install' and setting the default target to 'install'. Just 3 sed commands in my script, as simple as that.

**Comment by Jalle19** [comment]
@bas-t since you already know what needs to change, can you make a PR?

**Comment by bas-t** [comment]
@Jalle19 sure, but at this time I consider my changes as a very good workaround for private use, not good enough for your official source code. I have to investigate some more, when time permits (or wait a couple of days for the eureka moment).

However, if and when I think I hit the jackpot, @wsnipex  still has to test if it does not break his method, that I don't want.

**Comment by wsnipex** [comment]
There is nothing to change. The build instructions are just wrong for standard linux.
try this:
>mkdir build
cd build
cmake ..
make
make install

**Comment by bas-t** [comment]
@wsnipex Hmm, the 'just wrong' instructions would pull and build as a part of its sequence kodiplatform, p8-platform and tinyxml. witch is very neat, but finish with a combined make/make install target in the generated Makefile, witch is obviously less desirable.

Your cmake .. instruction however, fails with:

CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "Findkodiplatform.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "kodiplatform", but CMake did not find one.

  Could not find a package configuration file provided by "kodiplatform" with
  any of the following names:

  kodiplatformConfig.cmake
  kodiplatform-config.cmake

  Add the installation prefix of "kodiplatform" to CMAKE_PREFIX_PATH or set
  "kodiplatform_DIR" to a directory containing one of the above files.  If
  "kodiplatform" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!


As expected!

Your instruction works for Kodi itself, I agree. And likewise it should work for the pvr.hts addon, don't you agree?

Sadly at this time it does not, so something has to change after all.

Kodi uses a bunch of files from it's cmake directory that are included from the CMakeLists.txt file. IMO those are responsible for having separate make and make install targets in the generated Makefile.
At least using a couple of those (or parts of them) as a reference to create the ones needed here would make the difference for the pvr.hts addon.

**Comment by wsnipex** [comment]
Building software on linux usually requires you to provide needed dependencies yourself, so you have to install kodiplatform and libp8-platform. This is how you build packages.

OR you use the kodi intree addon wrappers and everything is handled for you, but do NOT build deb packages.

I repeat: We are not going to change this.

**Comment by bas-t** [comment]
@wsnipex I get your point. Partially agree with it (from your point of view), not in full, but I get it.
@Jalle19 As you can see, this is going nowhere, so I withdraw my request and I'll close this ticket. It was just a request, I never filed this issue as a bug.

Having said that and not having any changes to this repo in mind, I still have a question to the both of you. Since I value your opinions very high, I'd like you to explicitly state your point of view about this single matter:

Should a/any Makefile, regardless the circumstances under witch it is generated, have a separate make and make install target?

If not, please explain why this common practice has been abandoned.

Cheers to the both of you and thank you very much for donating your time to my quest.

**Comment by Jalle19** [comment]
I don't really have an opinion on that, I'm usually fine as long as the README instructions are correct.

**Comment by bas-t** [comment]
@Jalle19 I took another look at the method that @wsnipex uses, an it does indeed produce a Makefile with separate make and make install targets.
So I have to conclude that I agree with wat @wsnipex said in full. That implies that the README instructions for pvr.hts are indeed wrong.

**Comment by Jalle19** [comment]
They are correct for developers AFAIK, at least they have served me well. Feel free to PR instructions for normal use cases.

**Comment by bas-t** [comment]
I meant in case you need a make install target. Otherwise you are right. And yes I'll PR this this week.
