### ISSUE TITLE
Failed to load add-on in OSX 10.13

### ISSUE THREAD

**Issue by xswqaz** [kodi-pvr/pvr.hts#339]
Failed to load add-on in OSX 10.13

Add-on couldn't be loaded 
Can't load shared library

I make binary from source and put into 
/Applications/Kodi.app/Contents/Resources/Kodi/addons/pvr.hts
which was downloaded binary from Kodi official page 

Which library should I add?

**Comment by Jalle19** [comment]
Which branch did you build and which version of Kodi do you have? Why not just install the official release, this addon is included there?

**Comment by xswqaz** [comment]
I cloned master pvr.hts
Kodi version is 17.4
pvr.hts was not included in package

**Comment by xswqaz** [comment]
I found it 
Close
