### ISSUE TITLE
pvr.hts addon causes Kodi crash when activating OSD channel list

### ISSUE THREAD

**Issue by sakos** [kodi-pvr/pvr.hts#343]
The setup.
HTPC running on Libreelec 8.2.0 with latest pvr.hts addon 3.4.27.1. The backend is a Wetek Play box running on Libreelec 8.2.0 with latest Tvheadend backen addon (HTS Tvheadend 4.3-628 ~ LibreELEC Tvh-addon v8.2.444). Nevertheless the issue has been present for ages.

The symptom.
Rarely happens that Kodi crashes and restarts when I activate the OSD channel list during watching TV. The problem is almost 100% reproducible if I try to open the OSD channel list immediately after a system start.

Workaround.
The issue is not reproducible if async EPG mode is configured in pvr-hts addon settings.

Logs.
See attached logfile. The reproduction steps were:
- enable debug logging
- restart Libreelec
- wait until the system restarts and last TV channel is automatically started
- activate OSD channel list -> Kodi crashes.
- wait for Kodi restart and collect logs.
[log-2017-11-12-09.34.18.zip](https://github.com/kodi-pvr/pvr.hts/files/1464497/log-2017-11-12-09.34.18.zip)

**Comment by ksooo** [comment]
Accoeing to the logs, tThis is not a pvr.hts issue, but a Kodi core issue (a deadlock).  From what I can see this should be fixed in Kodi Leia.
