### ISSUE TITLE
Timeshift stops 20s after pressing PAUSE

### ISSUE THREAD

**Issue by hanzoh** [kodi-pvr/pvr.hts#353]
Hello,

first of all, I am not sure if this a problem of pvr.hts or Kodi itself:

When I press PAUSE on any channel, the GUI for timeshift appears as expected.
But after about 20 seconds, the grey timeshift bar disappears and the TVHeadend server reports:

unsubscribing from "xxx", hostname="yyy", username="zzz", client="Kodi Media Center"

The stream is then unrecoverable, I have to press STOP and start it again.

I have tested this with both TVHeadend server versions 4.2.5 and 4.3.991, the issue is the same.

Kodi 17.6 does not have this problem (also tested with 4.2.5 and 4.3.991).

Debug log is attached: [kodi.log](https://github.com/kodi-pvr/pvr.hts/files/1659769/kodi.log)

Kind regards
hanzoh

**Comment by Jalle19** [comment]
@ksooo maybe knows?

**Comment by ksooo** [comment]
No idea. Just tested with latest Kodi master and tvh 4.2.4 - works like expected.

**Comment by hanzoh** [comment]
I wanted to avoid that, but I have now tested a fresh configuration (including scanning for channels and mapping them) and the issue is gone.
At first I thought as well that tvh itself is the culprit, but after successfully testing with Kodi 17.6 I thought otherwise.
So nevermind, no problem here, move along.
But thanks for looking into it as well.
