### ISSUE TITLE
jittery/stutterring recordings

### ISSUE THREAD

**Issue by BinsonBuzz** [kodi-pvr/pvr.hts#357]
My setup:
- linuxserver tvh server
- kodi v18 latest builds on mibox 3 and fire tvs

Live TV works fine, but when I watch recordings the playback can be jittery and will even stop if I skip.  Recordings work fine on SBMC V16, but not on Kodi V18.  

My recordings are set to use 'pass' - should I be doing something different?

Thanks

**Comment by fsegouin** [comment]
By experience I had less issues with matroska files instead of using the pass profile.

**Comment by Jalle19** [comment]
If the recordings worked in previous Kodi versions I guess the bug is in Kodi, not the addon. Have you tried v17 too?

**Comment by BinsonBuzz** [comment]
sorry for the slow reply - a lot on.

I tried mkv and the recordings worked much better, but posed a problem when trying to watch an in-progress recording.

I went back to pass and things seem much better with the latest builds of v18.

Going to close as I think the work on the tv client in v18 will resolve this
