### ISSUE TITLE
PVR Add-on broken since upgrading to tvheadend 4.3-1082

### ISSUE THREAD

**Issue by fsegouin** [kodi-pvr/pvr.hts#358]
I know it's in the unstable branch but since upgrading to this new version it seems like the PVR add-on can not get the channels list anymore. No error in connection whatsoever but it just hangs at getting the channels list forever. Any ideas?

**Comment by Jalle19** [comment]
Without more information it's hard to tell. Do you get any errors in tvheadend's log? Maybe the version of tvheadend you're using just happens to be broken?

**Comment by fsegouin** [comment]
Turns out it was a mistake on my side. Sorry all!
