### ISSUE TITLE
Any way to run on Kodi 18?

### ISSUE THREAD

**Issue by ReekyMarko** [kodi-pvr/pvr.hts#359]
Any way to make this addon run on Kodi 18? I just get a popup saying "this addon is not compatible with this version of Kodi". I guess they changed up something in the way addons are handled with the upcoming release.

**Comment by Jalle19** [comment]
You need to use a compatible version of the addon. Normally these are pre-packaged when you install Kodi so you only have to enable it.

**Comment by ReekyMarko** [comment]
I'm running Kodi on Arch Linux, and I believe that the prepackaged addons only come with Windows versions of Kodi. I had to install a package from AUR in order for any pvr addons to show up

**Comment by Jalle19** [comment]
If you install the addons using the system package manager then you just have to make sure you install a compatible version. The rule of thumb is to use the master branch for the addon when you use the master branch of Kodi.

**Comment by ReekyMarko** [comment]
Ok thanks :wink:

**Comment by ReekyMarko** [comment]
The -git package on AUR was building against krypton so that was the problem. Built by hand from master and everything works :grin:
