### ISSUE TITLE
Handle OnQuit announcement

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.hts#36]
The addon should stop all subscriptions when this announcement is made. A subscription can be left "dangling" if Kodi is quit while in the middle of a channel switch, see http://sprunge.us/habO.

**Comment by ksooo** [comment]
Only OnQuit our also OnSleep?

**Comment by Jalle19** [comment]
Both I guess. Are there any more?

**Comment by ksooo** [comment]
Don't know. We have to look that up.

On second thought, isn't this something  Kodi should do instead of each add-on?

**Comment by Jalle19** [comment]
Normally yes, but looking at the log I don't really know what to say.

**Comment by ksooo** [comment]
@FernetMenta, @opdenkamp  shouldn't dvdplayer or PVRManager react on OnQuit (and friends) and close the open subscriptions?

**Comment by opdenkamp** [comment]
correct, dvdplayer should close the playing file, which should close the resources it has opened
