### ISSUE TITLE
Backup server (as second option where first one is unavailable)

### ISSUE THREAD

**Issue by nickiman** [kodi-pvr/pvr.hts#361]
Hi,
Recently I had to disable my tvheadend setup (it was running on a QNAP NAS) to configure it in a Raspberry Pi where my DVB-T device was recognized correctly. So, at the end, I have two tvheadend servers running fully operational with
a) SAT>IP device
b) DVB-T device connected right now in the raspberry pi due to the problem before mentioned
c) and several streams that I get from Internet processed with ffmpeg.

I was wondering if could be a good idea to implement in the tvheadend addon the possibility to configure a second IP address where it could be called if the first one server it´s unavailable.

This could be useful in order to have the oportunity to restart the device where tvheadends runs in the first instance and meanwhile the clients can swith to the second tvheadend server and can keep watching the TV.

What´s your opinion?
Keep waiting your feedback...
Regards.

**Comment by ksooo** [comment]
Will not happen any time soon. Too much effort, sorry.

**Comment by ksooo** [comment]
Will be available in Kodi Nexus. See #591

**Comment by Jalle19** [comment]
Closing this
