### ISSUE TITLE
Client shows wrong free disk space

### ISSUE THREAD

**Issue by Markus4210** [kodi-pvr/pvr.hts#362]
Hello @ all!

On my TVH Server i have 5 Users.
Every User has his own DVR configuration and own partition for recordings on an external drive.
So the Problem is that the users on the clients only see the free disk space from the Servers Main HDD.

Is there a chance to get this fixed?

Thanks Markus

**Comment by Jalle19** [comment]
We just report whatever the server gives us, this needs to be fixed in tvheadend itself AFAICT.
