### ISSUE TITLE
ERROR: Add-on 'pvr.hts' is not compatible with Kodi

### ISSUE THREAD

**Issue by FoxBob79** [kodi-pvr/pvr.hts#367]
The latest build does not work in Kodi 18! 
The following Errors a shown in the LOG file:

```
ERROR: EXCEPTION: Unknown addon id 'pvr.hts'.
ERROR: Add-on 'pvr.hts' is not compatible with Kodi
```
[kodi.log](https://github.com/kodi-pvr/pvr.hts/files/2089171/kodi.log)

**Comment by ksooo** [comment]
The addon needs to be rebuilt.
