### ISSUE TITLE
New feature: HTTPS option in settings

### ISSUE THREAD

**Issue by jkscz** [kodi-pvr/pvr.hts#369]
Please can you add option for secure communication in settings? When client communicate over HTTP, then communication is unsecured. When a Apache web server is built in front of TVheadend server as HTTPS proxy, HTTP communication must be redirected to HTTPS port. Unfortunately, the client is able to send the login information before the communication is redirected to the HTTPS protocol. The login information can easily be intercepted during initial communication via the HTTP protocol. If communication could be started directly on the HTTPS protocol, communication would be secured and the login data could not be intercepted. The HTTPS option is great possibilty how to secure TV streaming outside LAN.
How to built HTTPS proxy for TVheadend:
https://tvheadend.org/boards/5/topics/20739
https://tvheadend.org/issues/4372
https://tvheadend.org/boards/5/topics/27593

Complete Apache config:
```
<VirtualHost *:443>
  SSLEngine on
  ServerName tvh.server.net:443
  SSLCertificateFile "c:\Users\Administrator\AppData\Roaming\crt\tvh.server.net-chain.pem"
  SSLCertificateKeyFile "c:\Users\Administrator\AppData\Roaming\crt\tvh.server.net-key.pem"
  CustomLog "${SRVROOT}/logs/tvh-server-net_ssl_request.log" \
          "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"

ProxyRequests Off
ProxyPreserveHost On

ProxyPass /comet/ws ws://192.168.0.50:9981/comet/ws
ProxyPassReverse /comet/ws ws://192.168.0.50:9981/comet/ws

ProxyPass / http://192.168.0.50:9981/
ProxyPassReverse / http://192.168.0.50:9981/

AddOutputFilterByType INFLATE;SUBSTITUTE;DEFLATE audio/x-mpegurl
Substitute "s|http://|https://|i"
</virtualhost> 


Redirect:

<VirtualHost *:80>
    ServerName tvh.server.net
    ErrorLog logs/tvh.server.net-error_log
    CustomLog logs/tvh.server.net-access_log common

    Redirect / https://tvh.server.net/
</VirtualHost>
```

**Comment by fsegouin** [comment]
+1 for this one. I have my tvheadend backend behind a reverse proxy that supports SSL and it's all working well with https://github.com/zipleen/tvheadend-iphone-client. Any chance we could have SSL support in the kodi addon?

**Comment by jobrien2001** [comment]
+1 for this feature.  I am in the same boat.

**Comment by sic79** [comment]
+1.  Would really love to have this feature also

**Comment by trimethia** [comment]
+1 using nginx reverse proxy behind tvh backend too and need this.

**Comment by Gee1111** [comment]
+111!
