### ISSUE TITLE
Feature: show programme details for timers outside guide time

### ISSUE THREAD

**Issue by azlm8t** [kodi-pvr/pvr.hts#375]
Summary: Kodi's timer window shows all timers for weeks, even with "days to display" set to 3 days;  timers outside the guide data time window have no information and IWBNI they did have info.

=-=

I have async epg, guide data set to the default of three days, default theme, Kodi 18Beta3.

Although the guide data is 3 days, the timers view in Kodi shows all of my timers that are scheduled for the next couple of weeks. It took me a little while to realize that EPG=3days is the reason the timers for today/tomorrow have full programme information in the right hand panel, whereas timers further in the future have no information in that panel and just say "No information available."  (Mainly because I have few timers set and I didn't pay attention to the dates). I didn't associate "timer" with "epg" that way and so tried a few times to bounce tvh/kodi to "fix" the missing data, even though it's obvious in hindsight.

So, to be clear, the left panel has channel, title, time for all timers on tvheadend, but only timers within the guide data timeframe window are the ones with guide data have full description in the right panel.

I actually quite like seeing all of the future timers that are set, so it would be a shame to limit timers to the same number of days as the guide data. I could increase guide limit (is it just in DB not all in memory?), but it might not work for other people with small boxes.

Assuming most people have a limited numbers of timers, then, for me, ideally, pvr.hts would track the "epg event id" of timers and pass the corresponding epg events to Kodi/database even if they are outside the guide data window. So, if I had a timer for 9pm +10days, then this one epg event would be processed/stored even though it's not within my 3-day epg window. That way I guess the timer window would show data for all timers.

However, it seemed perhaps pvr.hts tells tvh to only send epg info for 3 days and not all days?

An alternative could be to rename the text from "No information available" to perhaps make it clearer that it's due to the guide data config?

No problems if this is rejected as "user error" as it's mostly just a nice to have in a later release.

**Comment by ksooo** [comment]
This is a valid feature  request, but nothing to be implemented in the add-on. This has to be incorporated into Kodi pvr core.

I actually have this on my long list of things to do for quite some time. Maybe I will find the time for this for Kodi v19.
