### ISSUE TITLE
epg changes in tvheadend hangs pvr.hts on import

### ISSUE THREAD

**Issue by schreibubi** [kodi-pvr/pvr.hts#378]
Recently tvheadend master with commit db437039114c62c5973a2c8cba8dca8a497ecb1c added support for keywords/credits/categories. Since this commit pvr.hts hangs on importing the epg. Seems like pvr.hts is not able to decode one of the getEvents messages it gets as a response from the tvheadend server. When I remove the additional new fields from the response in tvheadend, then everything works fine again.

**Comment by ksooo** [comment]
post a debug log with pvr component logging activated, please

**Comment by ksooo** [comment]
@azlm8t could it be that parsing "credits" goes wrong as it is (no longer) what you told me some time ago? => https://github.com/kodi-pvr/pvr.hts/pull/342#issuecomment-342014574

=> https://github.com/kodi-pvr/pvr.hts/blob/master/src/Tvheadend.cpp#L2633

**Comment by schreibubi** [comment]
I do not have a pvr log at hand, but the relevant error message "failed to decode message" in the log came from HTSPConnection.cpp:

  /* Deserialize */
  if (!(msg = htsmsg_binary_deserialize(buf, len, buf)))
  {
    /* Do not free buf here. Already done by htsmsg_binary_deserialize. */
    Logger::Log(LogLevel::LEVEL_ERROR, "failed to decode message");
    return false;
  }

So, seems that deserialization goes wrong. When enabling htsp tracing in tvheadend, I saw that the client always disconnected/reconnected after the getEvents request.

**Comment by azlm8t** [comment]
Sorry, I was away.

I don't believe the structures have changed in Tvheadend. I've not noticed any problems running with recent pvr.hts and latest master tvheadend. I can't see any relevant changes in the htspserver code in Tvheadend.

Am I right in understanding that if you run with Tvheadend db437039114c62c5973a2c8cba8dca8a497ecb1c then it fails, but if you run with the version before that then all works?

schreibubi, in Tvheadend, you can run `support/htspmon -e` and that will show what we would send to pvr.hts.

```
{ 'ageRating': 3,
  'category': [ 'bus./financial',
                'episode',
                'home improvement',
                'house/garden',
                'series',
                'show'],
  'channelId': 6876327,
  'copyrightYear': 2018,
  'credits': {'Nicki Chapman': 'presenter'},
```

Do your programmes have credits, etc.?

**Comment by schreibubi** [comment]
After removing the following lines in htsp_server.c, everything works fine again (using current master):
if (e->credits) {
    htsmsg_add_msg(out, "credits", htsmsg_copy(e->credits));
  }
  if (e->category) {
    htsmsg_add_msg(out, "category", string_list_to_htsmsg(e->category));
  }
  if (e->keyword) {
    htsmsg_add_msg(out, "keyword", string_list_to_htsmsg(e->keyword));
  }

So I'm quite sure that one of those messages is the culprit.

I will try to run htspmon tonight using an unpatched tvheadend to see what messages get send to pvr.hts.

**Comment by azlm8t** [comment]
I can't see anything obviously wrong. I don't have keywords in my xmltv file.

There have been various fixes to the xmltv parser in Tvh.

Even if `e->keyword` is true but `string_list_to_htsmsg` thought there was no message and returned NULL, I'd expect a crash in Tvh rather than an invalid message to be sent.

I'll take a better look tonight and see if I can force through some different xmltv combinations to cause a problem.

I don't know if you could perhaps also comment out the individual blocks one at a time (starting with keyword since I don't have that enabled)?

The only other change I can think of is something like:
```
if (e->keyword) {
  htsmsg_t *m = string_list_to_htsmsg(e->keyword);
  if (!m) abort();
  htsmsg_add_msg(out, "keyword", m);
}
```
(for both keyword and category), i.e., immediately abort in case we have an empty message since that would give an obvious place to look for a problem.

**Comment by azlm8t** [comment]
I've run the above code with abort, and enabled keywords in my xmltv and don't seem to have a problem with Tvh aborting, which suggests it is sending proper messages (at least for my xmltv).

```
 { 'ageRating': 3,
  'category': ['comedy', 'feature film', 'movie'],
  'channelId': 3450835,
  'contentType': 20,
  'copyrightYear': 1957,
  'credits': { 'Alfred Shaughnessy': 'writer',
               'Delphi Lawrence': 'actor',
               'Edward Chapman': 'actor',
               'Jill Dixon': 'actor',
               'Joan Sims': 'actor',
               'John Paddy Carstairs': 'director',
               'Leslie Phillips': 'actor',
               'Margaret Rutherford': 'actor',
               'Marjorie Rhodes': 'actor',
               'Norman Wisdom': 'actor',
               'Peter Blackmore': 'writer',
               'Peter Copley': 'actor',
               'Vic Wise': 'actor'},
...
'image': 'https://json.schedulesdirect.org/20141201/image/assets/p83362_p_v8_aa.jpg',
  'keyword': [ '1950s',
               'amusing',
               'assistant',
               'betting',
               'bookie',
               'café',
               'engagement',
               'horse racing',
               'jewelry',
               'jewelry shop',
               'jockey',
               'london',
               'love',
               'love interest',
               'madcap',
               'money',
               'partner',
               'racetrack',
               'rise',
               'secretary'],
  'method': 'eventAdd',
```

**Comment by schreibubi** [comment]
Can't reproduce the issue any more. So closing it for now.
