### ISSUE TITLE
HTSPVFS and in progress recordings

### ISSUE THREAD

**Issue by Glenn-1990** [kodi-pvr/pvr.hts#379]
HTSPVFS sends incomplete packets when reaching the end of the file, also when the file is still growing (in progress recordings). This is the root cause of a longstanding issue when trying to watch recordings at the live point. However, not all hw suffers from this. Typically this leads to stuttering or stopping playback. Another problem here is that kodi will not correctly buffer, actually there is no buffer at all.

Incomplete packets are not supported by Kodi, see https://github.com/xbmc/xbmc/blob/389f30da825bbf4baf82c63d758f66966fa0fa13/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamPVRBase.cpp#L65

However I'm wondering how to fix this issue, a few possibilities:
1) Discharge incomplete packets, this doesn't work well as the filepointer on the tvheadend side moves forward on every read.  
2) Let HTSPVFS::Size() return a smaller value (filesize-kodibuffersize), this works but I consider this as a workaround.
3) return the read only if the read is complete, this will introduce a delay. I'm not sure if this is acceptable from the kodi point of view. I did a quick test over here: https://github.com/Glenn-1990/pvr.hts/commit/88b7c7eb8ebe952e93cbce0e7165efc68a049541
4) Make kodi support incomplete reads.

Any opinions ?

Just opening an issue here before I'm putting effort in a PR :-)

**Comment by FernetMenta** [comment]
> Incomplete packets are not supported by Kodi, see 

you misinterpreted this comment. this function is before demuxer. at this time there is no packets (in terms of frames). the linked function can return any number of bytes. zero means eof.

**Comment by Glenn-1990** [comment]
@FernetMenta What I actually mean are incomplete packets of binary data (from the VFS), so requesting x number of bytes but getting less back. This is not supported by imputstream/demuxer right?

**Comment by FernetMenta** [comment]
wrong. as mentioned above: we speak about packets after demuxer. before demuxer it is just a stream that can deliver any number of bytes. the requested number of bytes varies with the underlying protocol, i.e. nfs, smb, etc

**Comment by Glenn-1990** [comment]
@FernetMenta Ok I get that, I will stop speaking about packets :-)
The requested number of bytes is 64k (default addon setting), when reaching eof, the returned number of bytes by prv.hts can be less. My guess is that Kodi can't cope with this? If not, there is an issue somewhere else.

**Comment by FernetMenta** [comment]
Again, returning less is not a problem

**Comment by jahutchi** [comment]
I am also experiencing this same problem.

I am running on OSMC on a Vero4K using kodi v18.1 and pvt.hts v4.4.14.

From an end-user perspective, the symptoms of issue as I am seeing it are as follows:

* Start playback of an in-progress recording (e.g. the recording is 3 minutes into the show).
* Watch the recording until the commercial break starts
* Hit skip forward a few times to attempt to return to real-time playback.

At this point the playback completely chokes - (video goes blocky/choppy and the audio goes out of sync and breaks up). Sometimes I can get things back to normal by skipping back, but sometimes I'm best off hitting stop, then going into the tvguide, finding the show and playing it from there to trigger real-time playback.

**Comment by jahutchi** [comment]
> as long as at least one byte is returned it is ok. we currently do not support returning nothing because this is interpreted as eof.

I added some debugging and found that pvr.hts does exactly that when playing an in-progress recording near the end of the file (within a couple of MB's).

I've mocked up a change here, feels a little hack-ish but may act as a starting point for resolving this long-standing issue: https://github.com/jahutchi/pvr.hts/commit/8058ced4ca06fd287138ce2bd42c3e6d702f007d

**Comment by Glenn-1990** [comment]
@jahutchi 
That's interesting, I always thought (before the discussion above) that we need to return the full requested length, but your commit points out we only need to return at least 1 byte.

**Comment by jahutchi** [comment]
> @jahutchi
> That's interesting, I always thought (before the discussion above) that we need to return the full requested length, but your commit points out we only need to return at least 1 byte.

Yes thats certainly what i found. 

My mocked up change basically retries when 0 bytes are returned. This means you no longer get messed up video and audio. The only remaining issue is then the 5-6secs wait whilst it buffers if you go right to the end of file...hence the change to Size() to trick it into thinking the file is 3mb smaller in size than it actually is (preventing you from skipping right to the eof). I played around with different sizes and 3mb gave the best results in my setup. Feels like a bit of a hack though.

EDIT 12/04/2019: found some time to look into a less-hackish way to resolve the excessive buffering when you reach EOF and found that returning true from the IsRealTimeStream API call seemed the way to go. 

Pull request has been submitted for consideration.

**Comment by ksooo** [comment]
Is this still an issue with latest Kodi v19 nightly builds? If I get no response within two weeks, I will close this issue.
