### ISSUE TITLE
Total time of ongoing recordings not updated during playback

### ISSUE THREAD

**Issue by Aydan** [kodi-pvr/pvr.hts#380]
The total playtime of an ongoing recording is not updated during playback.
This causes the recording to be marked as watched when stopped close to the displayed "end", although the recording is definitely not watched completely, and the playback position is lost.

My System:
Kodi 17.6 on Debian Stretch with HTS PVR plugin version 3.4.28
Tvheadend 4.3 built from source on Cubox 4x4 with Debian Stretch

**Comment by Aydan** [comment]
I just found #347 and if I understand it correctly this should work with my setup, so why doesn't it?

**Comment by ksooo** [comment]
Update to Kodi Leia and it will work.
