### ISSUE TITLE
Live video/audio stutter

### ISSUE THREAD

**Issue by hpmueller1971** [kodi-pvr/pvr.hts#384]
Hi,

with the Leia/Millhouse builds, i have an annoying stuttering when switching to a channel, it plays for about 1second, then pauses for 1second, plays 0.1-0.2 seconds, pauses for 0.2seconds and then plays without any interruptions. This happens on every channel (some with DVB-backend, IPTV, ffmpeg etc), but only with OMX, *not* with MMAL.

I combs through the logs, the only thing that stands out:

19:38:37.542 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:37.645 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:37.759 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:37.908 T:1497748336   DEBUG: CVideoPlayer::OMXDoProcessing Pause 0.43,0.00 (A:01 V:10) EOF:0 FULL:0 T:0.40
19:38:37.908 T:1497748336   DEBUG: OMXClock::OMXSetSpeed(0.000) pause_resume:1
19:38:37.959 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:38.259 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:38.376 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:38.576 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:38.676 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:39.194 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:39.410 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:39.611 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:39.727 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:39.927 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.028 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.244 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.344 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.346 T:1497748336   DEBUG: CVideoPlayer::OMXDoProcessing Resume 3.03,0.40 (A:01 V:01) EOF:0 FULL:0 T:0.40
19:38:40.346 T:1497748336   DEBUG: OMXClock::OMXSetSpeed(1.000) pause_resume:1
19:38:40.461 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.561 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.661 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.855 T:1497748336   DEBUG: CVideoPlayer::OMXDoProcessing Pause 2.87,-0.04 (A:01 V:10) EOF:0 FULL:0 T:0.80
19:38:40.855 T:1497748336   DEBUG: OMXClock::OMXSetSpeed(0.000) pause_resume:1
19:38:40.878 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer

This is from playback with OMX, when using MMAL it looks the same, the only difference are the lines with

DEBUG: CVideoPlayer::OMXDoProcessing Pause 2.87,-0.04 (A:01 V:10) EOF:0 FULL:0 T:0.80

but the CRender-Timeouts are there too, but no stuttering...

Can someone give me a hint if i can log more on the client, what debugging on the server i could do, or can someone at least confirm that this is happening on other systems? TVH runs on a dedicated server, the stuttering happen from RPi2 to RPi3+, so i doubt its a network issue.

Regards...

**Comment by ksooo** [comment]
> This happens on every channel (some with DVB-backend, IPTV, ffmpeg etc)

 Definitely not an addon problem... report this to https://github.com/xbmc/xbmc/issues , please
