### ISSUE TITLE
"Deep voices" with "Sync playback to display" + OMX

### ISSUE THREAD

**Issue by hpmueller1971** [kodi-pvr/pvr.hts#385]
Hi,

since krypton, i'm getting "deep voices" when enabling "Sync playback to display", like pitch is changing. If i play a philips-testcard with a 1khz tone, it becomes a kind of "wah-wah" darth vader sound, it sounds like playback speed is changing constantly...

i realize this is very hard to debug (basically the reason i've waited for so long to report it), there is absolutly nothing in the logs... The usual suspects (like resampling/PLL adjustment, or even the obvious "pitch correction", set to 0 or 100) make no difference...

Can someone confirm this...?

**Comment by ksooo** [comment]
Definitely not an addon problem... report this to https://github.com/xbmc/xbmc/issues , please
