### ISSUE TITLE
wrong value of EPISODE when SEASON is empty

### ISSUE THREAD

**Issue by walterheisenberg** [kodi-pvr/pvr.hts#387]
I'm using xmltv with TVheadend. The Season/Episode-info is stored as xmltv_ns.
this means e.g. 
"2 . 15" is the third season with Episode 16 (counting begins at "0")
TVH-webif shows: s3.e16, Kodi also

"12 . 11" is 13th Season with Ep 12
TVH-webif shows: s13.e12, Kodi also

" . 36" is the 37th Episode with no Season info (here is the bug in pvr.hts)
TVH-webif shows: e37, Kodi shows "**S**37"
So, the WebIF of TVH is showing everything correctly and the bug is IMHO in pvr.hts or Kodi itself.

If the info in xmltv is " . 36" then Kodi shows "**S**37" as ListItem.Episode, it should be only "37", because there is no season info in the xmltv-file.
I checked with Developer web:
```
ListItem.Season:
ListItem.Episode S37
```
Thx for fixing this issue

**Comment by ksooo** [comment]
Is this still an issue with latest Kodi v19 nightly builds? If I get no response within two weeks, I will close this issue.
