### ISSUE TITLE
Switch to last viewed channel is messing up channel numbers

### ISSUE THREAD

**Issue by sakos** [kodi-pvr/pvr.hts#393]
Since upgrade to Tvheadend HTSP Client addon version="4.4.7.2" the switch to last viewed channel is not working properly.
So far pressing button 0 on the remote switched to the previously watched channel.  Pressing button zero more times was switching between the last two channels back and forth. This behavior has been broken in recent pvr.hts addon version.
The issue occurs if I configure Live TV to use backend channel order but not the backend channel numbers. When I press button zero a wrong channel is selected and its channel number is changed in the channel list. If I repeat the action more and more channels got renumbered.
Recovery: apply data reset and restart addon
Workaround: if "use backend channel numbers" option is also enabled then it works fine.

**Comment by ksooo** [comment]
What makes you think it's an addon bug? Have you tried with same kodi build and older addon version? No idea what version 4.4.7.2 is. The official addons all have only three digit version numbers.

**Comment by ksooo** [comment]
Have you set "delay mark last watched" to a value > 0 seconds?

https://user-images.githubusercontent.com/3226626/48271989-e58a8a80-e43d-11e8-857c-f35bd1b0026c.png

**Comment by sakos** [comment]
No, I was not aware of this option.
I am running Coreelec 8.95.7 with Kodi Leia. Anyway, I installed an old version of the addon - it worked fine - and went back to latest. Now, I cannot reproduce the fault.
I close the issue and reopen when I can reproduce and provide more information.

**Comment by ksooo** [comment]
Sorry, no support for CoreELEC here. They carry to many Kodi and what not patches. Reproduce with vanilly Kodi please or ask for help at the CoreELEC forum.
