### ISSUE TITLE
Programme summary missing in Kodi EPG  - Rev 4.4.9 & 4.4.10 

### ISSUE THREAD

**Issue by biryets** [kodi-pvr/pvr.hts#397]
The programme summary is missing from the Kodi EPG. The programme title and subtitles are however shown ok.
I've conducted multiple testing to confirm that 4.4.9 & 4.4.10 are affected.
Using the default Estuary skin,  Everything works ok when rolled back to 4.4.6.

**Comment by ksooo** [comment]
No need to open another one of these.

**Comment by ksooo** [comment]
I will take look. I now  have an idea what could be the cause.
