### ISSUE TITLE
Age Rating, Star Rating, Date String not displayed in EPG overview

### ISSUE THREAD

**Issue by sunsettrack4** [kodi-pvr/pvr.hts#404]
Good day,

I'm using tvHeadend 4.3 and the latest Kodi PVR addon. I'm grabbing my own xml files, and all strings are recognized within tvHeadend, but not in Kodi. E.g. Episode, categories and credits are displayed in Kodi, but the a/m strings are not available there.

Could you please help me? The strings are:

```
<rating system="FSK">
  <value>12</value>
</rating>

<star-rating system="IMDb">
  <value>7/10</value>
</star-rating>

<date>2018</date>
```

Thank you

**Comment by Jalle19** [comment]
Are you saying the `7/10` style rating values don't show in Kodi?

**Comment by sunsettrack4** [comment]
Yes, it's not displayed in Kodi

**Comment by ksooo** [comment]
@Jalle19 not sure what happens here. Looking at the code, both pvr.hts and Kodi should support "age rating", "star rating" and "year first aired". So, no missing feature, but a bug somewhere.

**Comment by ksooo** [comment]
A quick look deeper into Kodi code indicates that support for the a/m information is incompletely implemented in Kodi and/or missing in Estuary.

No signs of Listitem.ParentalRating / VideoPlayer.ParentalRating in Estuary sources, for example.

So, close this issue, please. No bug, but missing Kodi (Estuary) feature. You my open a feature in the kodi forum, though.
