### ISSUE TITLE
Feature Request: Add option to specify Broadcast type when scheduling timers

### ISSUE THREAD

**Issue by RKCRLR** [kodi-pvr/pvr.hts#405]
The Tvheadend web interface has an option to specify Broadcast type in the Autorecs tab.  This allows for specifying to record only New broadcasts.  It would be useful to have this option when creating Timer rules.

**Comment by ksooo** [comment]
We have already a setting for this. Timer settings dialog => field "Prevent duplicate episodes"

**Comment by RKCRLR** [comment]
There are a bunch of different options listed under "Prevent duplicate episodes" but not one of them is called new broadcasts.  Which option is equivalent to new broadcasts only?  
Thanks

**Comment by ksooo** [comment]
This is a dev space, not a user support forum.

EDIT: oops. This comment was not ment to go here.

**Comment by ksooo** [comment]
> There are a bunch of different options listed under "Prevent duplicate episodes" but not one of them is called new broadcasts. Which option is equivalent to new broadcasts only?

 Well, none I guess. I mixed that up with "duplicate handling" field in TVH web UI. Kodi/pvr.hts supports "duplicate handling", but not "broadcast type".

Re-opening the issue... but implementation will need changes in Kodi as well. Will not happen anytime soon, sorry.

**Comment by RKCRLR** [comment]
I've been doing most of my recordings using the "Timer rule (series link)" Type.  The problem I was having with using "guide based" was I would record too many non-related shows.  I.e., if I wanted to record the series "Nature" I wound up recording anything with the word nature in the title. (Nature Cat, Nature Fun, etc.)  
"Prevent duplicate episodes" is only available when you select guide based.  The broadcast type would need to be at the top level in Timer settings.  
Broadcast Type would be a useful feature.  I understand it will take some time.  My current work-around is to bring up the Tvheadend interface and change the type to new.  
Thanks for reopening the issue.

**Comment by RKCRLR** [comment]
Curious if any progress has been made on this request.

**Comment by ksooo** [comment]
The data needed for this feature are not accessible via HTSP, thus first tvheadend must be extended, then pvr.hts and Kodi could be adapted.
