### ISSUE TITLE
Subscription not closed when stopping timeshifted playback with predictive tuning enabled

### ISSUE THREAD

**Issue by jahutchi** [kodi-pvr/pvr.hts#406]
**Steps to reproduce**

1. Configure Tvheadend to enable time shifting - for example:

![image](https://user-images.githubusercontent.com/14977362/53493772-1269b880-3a94-11e9-8d5d-e2f2e64b7443.png)

2. Enable the Predictive Tuning options in the add-on settings.

    On my setup I have:

    Number of subscriptions to use: 2
    Unused subscription close delay (seconds): 20   (AKA pretuner_closedelay)

3. Start playback of a tv channel

4. Wait 1 minute

5. Hit Step Back to shift back 10 seconds

6. Hit Stop

7. Check in the Tvheadend web interface, and you'll see the subscription is never closed. (I even waited several hours overnight - it really is never closed)

![image](https://user-images.githubusercontent.com/14977362/53493930-81dfa800-3a94-11e9-85dd-ecf292462cfa.png)

**Log Files**

Here are some logfiles when re-producing the issue using the steps above:
* kodi debug log: [kodi.no-sub-end.log](https://github.com/kodi-pvr/pvr.hts/files/2910504/kodi.no-sub-end.log)
* kodi debug log with pvr.hts tracing enabled:  [kodi.no-sub-end-trace.log](https://github.com/kodi-pvr/pvr.hts/files/2910502/kodi.no-sub-end-trace.log)

**Description**

My Setup is:

* Kodi 18.1 running on a Vero4K+
* pvr.hts version 4.4.14
* Tvheadend 4.2.8 running on a Debian 9.8 server

I have found that this only occurs when predictive tuning is enabled, and only when hitting stop whilst in time-shifted playback. At this point, the only way I've found to close the subscription is to restart Kodi.

I also noticed that when stopping live tv (non-timeshifted) with predictive tuning enabled, it takes _{pretuner_closedelay}_ seconds before the subscription ends, and during that time you get a large number of debug lines in kodi.log as follows (not sure if this is expected):

`DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index xxxx`

If you hit stop whilst in time-shifted playback with predictive tuning enabled, then these errors continue indefinitely and the subscription is never closed.

**Comment by jahutchi** [comment]
I have also just done some testing on:
Rpi3 with LibreELEC Kodi v17.6 pvr.hts v3.4.27

With the same predictive tuning enabled as per above:
* Hit Stop during non-timeshifted playback: subscription is closed immediately
* Hit Stop during timeshifted playback: subscription is closed immediately

**Comment by ksooo** [comment]
> Hit Stop during timeshifted playback: subscription is closed immediately

 This is an intended change in bahavior. If you switch back (quickly) to the channel after closing, you will still have timeshift data, whcih is fine.

> and you'll see the subscription is never closed. (I even waited several hours overnight - it really is never closed)

 That's clearly a bug. :-)

**Comment by jahutchi** [comment]
> > Hit Stop during timeshifted playback: subscription is closed immediately
> 
> This is an intended change in behavior. If you switch back (quickly) to the channel after stopping playback, you will still have timeshift data, which is just fine.

Understood: so this was an improvement in Leia.

So to summarise my findings:

**Kodi Krypton:**
* Hit Stop during timeshifted playback: subscription is closed immediately
* Hit Stop during non-timeshifted playback: subscription is closed immediately

**Kodi Leia:**
* Hit Stop during timeshifted playback: subscription is left open indefinately.
* Hit Stop during non-timeshifted playback: subscription is closed after _pretuner_closedelay_ seconds. 

Note: during the seconds that the subscription is left open, a large number of these errors are written to the logfile (not sure if these are of concern, or can simply be ignored):

`AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index xxxx`
