### ISSUE TITLE
Feature External recording via tvh client

### ISSUE THREAD

**Issue by a1danslat3** [kodi-pvr/pvr.hts#41]
Hello,

Amazing work guys but I have one request which keeps bothering me. Is it possible to implement a record destination within the client add-on ? VDR has this feature and is excellent for people who want to setup recording themselves within Kodi instead of the webserver. 

As I'm no use with programming, I would be happy to donate or pay the devs direct if this feature is possible.

Regards,

Aidan

**Comment by Jalle19** [comment]
Closing this since I answered you on the forums already.
