### ISSUE TITLE
First line in EPG missing

### ISSUE THREAD

**Issue by wombat01** [kodi-pvr/pvr.hts#417]
Reopen this issue https://github.com/xbmc/xbmc/issues/15960 from

19+ ALPHA (2019-04-25) still same .. PVR HTS 5.0

**Comment by ksooo** [comment]
Why do you think this is a pvr.hts issue?

**Comment by wombat01** [comment]
IPTV Simple for example Ok.

**Comment by ksooo** [comment]
This does by no means point to pvr.hts as root cause and I actually think this is a Kodi problem. Why have you closed the Kodi issue?

**Comment by wombat01** [comment]
Sorry, yesterday at the miracle after the update to the build 2019-04-24 began to work. Today I hit 2019-04-25 + HTS 5.0 and it happens again. So please if you open the cases again on main repository.

Thank you.
