### ISSUE TITLE
Stream randomly gets stalled for no apparent reason + a feature request

### ISSUE THREAD

**Issue by smp79** [kodi-pvr/pvr.hts#422]
This happens rarely, maybe once in a few days and I have no idea how to reliably reproduce this. 

This is what I see in Tvh Status/Subscriptions when this happen:
![capture_001_26062019_171202](https://user-images.githubusercontent.com/28512968/60189001-e808eb80-9838-11e9-9c9d-84979ecbd23c.jpg)
The input is working but there is no data on the output.

The annoying thing is that it never automatically recover - Kodi just show a frozen frame until I switch a channel or manually drop/restart HTSP connection. 
So, I'm wondering if it is possible to add some sort of timeout for the situations when there is no input data on client side, so the HTSP connection is automatically reset?

**Comment by Jalle19** [comment]
Are you sure it's not a tvheadend bug? There are 3 million stream errors according to your screenshot.

**Comment by smp79** [comment]
I'm not sure, But even if the stream is stalled due to a tvheadend issue - it would be nice if the HTSP client could reset the connection without user intervention.

**Comment by Jalle19** [comment]
Sometimes a channel is legitimately dead, I don't think this is worth pursuing since it would be hard to get it just right. There are maybe some tvheadend settings you could fiddle with to alleviate this issue.

**Comment by ksooo** [comment]
Is this still an issue with latest Kodi v19 nightly builds? If I get no response within two weeks, I will close this issue.

**Comment by smp79** [comment]
I switched to VDR+VNSI in mid-2019. Were there any commits that can potentially fix this? I can go back to TVH and test but that's not really what I'm looking forward to tbh.
