### ISSUE TITLE
Can't open H.265 stream from Tvheadend 4.3 in Kodi 18

### ISSUE THREAD

**Issue by diogosalazar** [kodi-pvr/pvr.hts#424]
I have a H.265 channel in Tvheadend 4.3 that will not be played by Kodi 18.
The same Tvheadend stream is played just fine by VLC 3.07.

Kodi is able to play the H.265 steam:
-  Directly from the source (bypassing Tvheadend)
-  By using the IPTV Simple Client plugin pointed to https://tvheadend-server:9981/playlist

**Comment by ksooo** [comment]
I can. ;-/

To get meaningful assistence you need to provide far more details.

**Comment by diogosalazar** [comment]
Sorry, pressed 'return' accidentally while opening this issue

**Comment by ksooo** [comment]
Please provide a complete Kodi debug log with PVR component logging enabled or nothing will happen with this issue.

**Comment by diogosalazar** [comment]
Thanks for your quick response.

Here is the log file link: [kodi.log](https://paste.kodi.tv/ikagifeyun.kodi)

Actions taken in the log file:

1.  Open Kodi
2. Load H.264 stream (line #768)
3. Load H.265 stream (line #3650)
4. Load another H.264 stream (line #3735)
5. Load same H.265 stream (line #6723)
6. Close Kodi

Please let me know if the uploaded log file suffices

**Comment by ksooo** [comment]
Is this still an issue with latest Kodi v19 nightly builds? If I get no response within two weeks, I will close this issue.
