### ISSUE TITLE
addon not compatible with late kodi git

### ISSUE THREAD

**Issue by fleixi** [kodi-pvr/pvr.hts#425]
this addon isnt compatible with Kodi (19.0-ALPHA1 Git:20190601-2db68e19b34-dirty). Platform: Linux x86 64-bit using the last build from today r812.7f3c0d9-1

i could not enable the addon in kodi getting the error:

 ERROR: Add-on 'pvr.hts' is not compatible with Kodi

**Comment by ksooo** [comment]
Can happen at any time in alpha and pre alpha development phase. Just wait for an update.

**Comment by fleixi** [comment]
I know this could happen in alpha, but it is an issue.

As far as i understand the last two commit was intended to fix this but it isnt working so this was just a hint that the last commits arent working as expected

**Comment by ksooo** [comment]
> As far as i understand the last two commit was intended to fix this but it isnt working so this was just a hint that the last commits arent working as expected

 The commits do exactly what they are supposed to do.

 Committing a code change is only the first step in a longer process which at the end offers an updated addon for your Linux distro. That process started, but obviously has not finished yet. All you have to do is to be a bit patient.
