### ISSUE TITLE
Channel order problems in 5.2.1

### ISSUE THREAD

**Issue by andy-in-worthing** [kodi-pvr/pvr.hts#430]
pvr.hts 5.2.1 seems to have lost my channel order and groups.  I've tried re-ordering the channels again, but the changes aren't preserved.  I have 'use channel order from backend' and 'use channel numbers' from backend turned off

Log with 5.2.0: https://paste.osmc.tv/maquxepiti
Log with 5.2.1: https://paste.osmc.tv/zekiwubala

(This is using OSMC on Raspberry Pi, Matrix beta builds.  The latest 2 builds use 5.2.1 and have the problem.  If I roll the build back to the version using 5.2.0 the channel order and groups are restored, OSMC developer suggested I raise the issue here)

**Comment by Jalle19** [comment]
Could it be related to https://github.com/xbmc/xbmc/pull/16696 ?

**Comment by phunkyfish** [comment]
Have you tried clearing the PVR database to see if the ordering is fixed?

**Comment by andy-in-worthing** [comment]
Yes, tried clearing database from 'PVR & live tv' settings, channels still
come back in same mixed-up order. Also tried manually removing the TVxx.db
files and restarting.

I can move channels around in the channel manager, but the EPG shows the
original order again.

**Comment by ksooo** [comment]
> move channels around in the channel manager

 he's talking about kodi's built-in channel manager.

>  I have 'use channel order from backend' and 'use channel numbers' from backend turned off

 Seems, we do not respect anymore that user does not want backend order?

 Anyway, I guess this is a Kodi problem, so it should be reproducible with every pvr addon, not only pvr.hts

**Comment by phunkyfish** [comment]
Will take a look.

**Comment by phunkyfish** [comment]
So I assume you synchronize the groups with the backend in PVR settings?

**Comment by andy-in-worthing** [comment]
> So I assume you synchronize the groups with the backend in PVR settings?

No, that's turned off.  I basically leave the channels alone in TVHeadend, and re-order and create groups within Kodi.

I can see the TV36.db file is being modified when I try changing channel order (the timestamp changes anyway), but still the changes are lost.  The order is weird too, doesn't reflect anything I see in TVHeadend.

Um.. I might delete the channels in TVHeadend and rescan from scratch.

**Comment by phunkyfish** [comment]
I think this is related to the PR referenced above. Let me do some testing and work on a fix over the next few days.

**Comment by phunkyfish** [comment]
So you set the order in channel manager and that dictates the order in whatever groups you create?

So if you change the order in channel manager after creating the groups the order of the channels within the groups should change too?

**Comment by andy-in-worthing** [comment]
> So you set the order in channel manager and that dictates the order in whatever groups you create?

Yes, I do all channel order/group creation inside Kodi.

> So if you change the order in channel manager after creating the groups the order of the channels within the groups should change too?

Just checked, yes it does in the OSMC build which includes 5.2.0 but not in the builds including 5.2.1

Not sure if this helps, but these are screenshots of the channel order I've created in earlier builds and 'expect' to see, and the channel order I see when using the build including 5.2.1.  If I reinstall the earlier builds of OSMC, the channel order is back to normal.

BTW I'm not knowledgeable enough to know if this is a pvr.hts issue or a Kodi one!  I've not seen anyone else mention this, maybe just me :-/

![screenshot001](https://user-images.githubusercontent.com/56472907/67111232-69abcd00-f1cc-11e9-9601-98de5eaf0fe9.png)
![screenshot000](https://user-images.githubusercontent.com/56472907/67111213-61ec2880-f1cc-11e9-9785-43c17f919f61.png)

**Comment by phunkyfish** [comment]
It’s kodi core. I have a fix PR’d. It’s linked above.

**Comment by ksooo** [comment]
Is this still an issue with latest Kodi v19 nightly builds? If I get no response within two weeks, I will close this issue.
