### ISSUE TITLE
TVheadend htsp client server unreachable and connection estabalished message for 4-5 minutes

### ISSUE THREAD

**Issue by ghost** [kodi-pvr/pvr.hts#434]
Many times when I turn on my sony 900f andriod tv and select the Kodi app via the TV it will say TVheadend htsp client server unreachable. Then it blinks TVheadend htsp client connection established. It will continuously blink both messages back and forth for about 4-5 minutes. I can even select a channel and view it with no issues via the EPG but it will still show both messages back and forth saying TVheadend htsp client server unreachable and then show TVheadend htsp client connection established.

Is it possible to stop showing the message once the connection is established rather than showing it for 4-5 minutes?

Thanks

**Comment by ghost** [comment]
This seems to happen when there are multiple clients connected to the same TVHeadhend server at the same time.  When there is only one client the message disappears pretty quickly.

**Comment by PantherTS** [comment]
Also experiencing this issue on my multiple Sony Android-based TVs with the Kodi app running the tvheadend add-on. Live TV is working fine but these notifications will continue to cycle back and forth and finally after a few minutes go away. Running the latest release version of the app and the add-on.

**Comment by ksooo** [comment]
Without a debug log I can not say anything.

**Comment by PantherTS** [comment]
Thank you for the response. I'll get you a log as soon as I can.

**Comment by ghost** [comment]
[kodi.log](https://github.com/kodi-pvr/pvr.hts/files/3908247/kodi.log)

Hopefully this is the correct log file

**Comment by ksooo** [comment]
The log is full of  "unable to connect to 192.168.2.109:9982" messages.

Maybe you should check your network setup. Increasing the "connection timeout" value in pvr.hts settings could also be worth a try.

**Comment by ghost** [comment]
Ok, I tried changing the "connection timeout" value to 25 seconds.  When I open Kodi I believe it works fine but when I turn off the TV while still on the Kodi app I still sometimes receive the connection issue when I turn the TV back on and it automatically has Kodi on.  

Maybe it still has Kodi open when the TV is off and it loses connection to the internet causing it to show the connection issue when I open it?

**Comment by PantherTS** [comment]
I'm so sorry I cannot provide a log. The Sony TVs are out at my parents' place which is 4.5 hours away. Next time I'm out or if I manage to get my dad to send a log to me I'll upload it.

**Comment by Leatherface75** [comment]
I would like an option to disable "connection timeout" completely.
When i start my TV in bedroom it always and sometimes when it looses connection while watching i can't watch anything for a few minutes.
With other apps on AndroidTV boxes i can watch from server directly without waiting.
Maybe changing how Kodi handles this?

**Comment by ksooo** [comment]
Is this still an issue with latest Kodi v19 nightly builds? If I get no response within two weeks, I will close this issue.

**Comment by PantherTS** [comment]
Unsure here as we've switched to using Nvidia Shield devices behind every TV with Kodi running on them. Probably have to wait for someone else with the Sony TVs still running the client to chime in. Thanks!

**Comment by ghost** [comment]
I tried using Kodi 19 beta 2 and the issue is now resolved.  You may close the issue.

Thanks
