### ISSUE TITLE
HTSP streaming of IPTV channels stuttering

### ISSUE THREAD

**Issue by stredwizard** [kodi-pvr/pvr.hts#435]
I have been using TVH in conjunction with kodi for about a month, in that time I have never had a 100% reliable setup.

using your add-on in kodi results in the odd stutter and then eventually the channel locks up and to restart the stream it is required to switch channels and back, where I may be lucky and it will work fine for a while and then start buffering again.

meanwhile I've got the TVH app for ios watching the same channel but of course using the pass profile and it is absolutely perfect no dropouts at all, i've now switched to Emby using the TVH plugin which again uses the pass profile and that is also perfect.

Watching the input/output while streaming using the HTSP profile they never match, whereas they mostly do with the pass profile, not sure if this is important though.

sadly I miss the convenience of kodi though so i need to find the solution, clearly there is a problem with my setup and/ or the HTSP profile in general, its worth mentioning i've tried many fixes i've found around various forums including disabling timeshift, rolling back to a different TVH version etc, also i've tried the nextpvr server and kodi add-on which also work just fine, but isnt as easy to use as TVH and isn't reliable with my USB tuners.

my setup is ubuntu 18.04 server using tvheadend in docker with kodi on windows 10, rpi3 (libreelec) and a S905W based android TV box, they all exhibit the same problems.

I'm guessing you would need logs but from where? the server and the clients?

Thankyou!

**Comment by Jalle19** [comment]
Bugs like these are almost always tvheadend bugs, not addon or Kodi bugs.

**Comment by ksooo** [comment]
Is this still an issue with latest Kodi v19 nightly builds? If I get no response within two weeks, I will close this issue.
