### ISSUE TITLE
duplicate channels

### ISSUE THREAD

**Issue by ghost** [kodi-pvr/pvr.hts#437]
I'm using TVHeadend 4.2.8 along with with kodi 18.5 with add on htsp client 4.4.20.  I'm using a HDhomerun prime and HDhomerun dual.  I have the same channel name for the duplicate channels from both Hdhomerun prime and Hdhomerun dual on TVHeadend server and I merged the channels together on the TVHeadend server but when I view the channels on Kodi guide I still see both duplicate channels on the guide.  I thought it was suppose to merge the two channels together on the guide and play from which ever tuner has the higher priority unless the tuner is already being used then it would go to the secondary tuner.

**Comment by ksooo** [comment]
The addon displays whatever tvheadend sends to it. So, this is a tvheadend problem.
