### ISSUE TITLE
Stuck at PMT switching

### ISSUE THREAD

**Issue by matthias1403** [kodi-pvr/pvr.hts#439]
Hi,

I'm watching regular TV channel which is changing the PMT to dristribute regional programs.

After switching the PMT playback stucks, sometimes it recovers on its own, but  mostly I have to restart the playback....very annoying; esp. for the WAF.
TV headend seems to work properly as a check with VLC is working ok. 

To verify, one can check on the channel TEST-R, which changes its PMT every minute from PHOENIX to ARTE and vice versa.

Don't know if this is a know issue.
Hope anyone can help with a workaround or a fix.

Br,
Matthias
[kodi.log](https://github.com/kodi-pvr/pvr.hts/files/4021900/kodi.log)

**Comment by matthias1403** [comment]
No comment here?
Any workoaround, which could help?

Best regards,
Matthias

**Comment by Jalle19** [comment]
> To verify, one can check on the channel TEST-R, which changes its PMT every minute from PHOENIX to ARTE and vice versa.

@ksooo do you have this channel?

**Comment by ksooo** [comment]
Did some testing with channel TEST-R on latest Kodi master with latest pvr.hts and latest tvheadend. Confirming 1-2 secs freeze of video when switching PMT between phoenix and arte. Never encountered an unlimited freeze, though. Audio switches just fine, without any dropouts, btw.

**Comment by CvH** [comment]
I had similar problems at MDR, since changing to http streaming at pvr.hts all those problems are gone for me.

**Comment by matthias1403** [comment]
Could you give a hint how to enable http streaming? Tried to use the "pass" profile already earlier, but pvr.hts refused it with "streaming profile not available".
Profile "pass" is enabled in tvheadend and allowed for the user.

@ksooo On more powerful machines it stops sometimes not completely in my case.

Thanks,
Matthias

**Comment by ksooo** [comment]
> I had similar problems at MDR,

 Never encountered any problems with MDR.

**Comment by CvH** [comment]
> Never encountered any problems with MDR.

It was reproduceable at ~18.55 at the moment they switch from some magazine toSandmänchen/News (not sure if this is exactly the same issue).

**Comment by matthias1403** [comment]
> It was reproduceable at ~18.55 at the moment they switch from some magazine toSandmänchen/News (not sure if this is exactly the same issue).

Yes this is the same. The PMT switching (or whatever it is called) is done for the regional programs. In my case it happens every day when Nordmagazin starts at 19:30 on NDR and when it ends. On MDR it is starting 19:00 another program for each "Bundesland" (e.g. Sachsenspiegel for "MDR Sachsen").

So, would like to know how to change to http streaming.

Thanks & Br,
Matthias

**Comment by ksooo** [comment]
http streaming has a major downside - no timeshift. Just saying.

**Comment by CvH** [comment]
> So, would like to know how to change to http streaming.

K19 required
![image](https://user-images.githubusercontent.com/1355173/101001120-ff382680-355e-11eb-87fb-355936abde9b.png)

> no timeshift

Sadly at the moment you have to choose between rock solid or features, besides timeshift http streaming works much better for me without a single hickup since merge (I have to respect waf).  stable > features

Workaround would require client side handling of timeshift that someone needs to create of course (wasn't there a pvr.iptv implementation for that?).

**Comment by matthias1403** [comment]
OK, thanks; with the Kodi 19 Beta I see this now as an option. Assuming this will fix it for me.

Is this only available with the Kodi 19? Don't know if the coreelec distri will upgrade for my Odroid C2.

**Comment by Jalle19** [comment]
> Is this only available with the Kodi 19?

Yes.

**Comment by matthias1403** [comment]
Here some observations:

Tested now with Kodi 19 Beta 1 (Android & Windows) in http mode. Generally it works but PMT switching unfortunately not, the following is logged by the server when the PMT is switching:

Dec  3 13:12:27 localhost tvheadend[8091]: webui: Unable to reconfigure stream /stream/channelid/944953863
Dec  3 13:12:27 localhost tvheadend[8091]: webui: Stop streaming /stream/channelid/944953863, muxer reported errors
[tvheadend_4.2.8.log](https://github.com/kodi-pvr/pvr.hts/files/5641772/tvheadend_4.2.8.log)
The client playback simply stops in this case.


I'm using tvheadend stable (4.2.8) and decided to check the unstable branch (4.3). In this case http mode is not working at all. The client (all platforms) has an issue with the url:

2020-12-04 10:26:21.495 T:8183    ERROR <general>: Open - failed to open source <http://USERNAME:PASSWORD@192.168.179.49:9981/stream/channelid/586436545>
2020-12-04 10:26:21.495 T:8183    ERROR <general>: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/Alle%20Kan%c3%a4le/pvr.hts_586436545.pvr]
[kodi.log](https://github.com/kodi-pvr/pvr.hts/files/5641773/kodi.log)

One good point is that an Android and Windoes the PMT Switching mainly works in non-http mode with the 4.3 server. But on coreelec it does not.

Matthias

**Comment by ksooo** [comment]
Haha, http mode was sold to me to heal every known streaming issue....

**Comment by ksooo** [comment]
No idea about coreelec and I don't care, tbh. I only know that it's Kodi is different from vanilla Kodi due to several patches they apply. Those patches can lead to all kind of different behavior compared to vanilla Kodi.

**Comment by FernetMenta** [comment]
@matthias1403 tvh 4.3 works but you need to enable "persistent authentication" in tvheadend passwords in order to make http streaming work.

**Comment by matthias1403** [comment]
Ok, with this setting http works and also PMT switching...so far so good.

Will check with coreelec to get a solution.....or will change to another setup. WAF is still not good, as long we have to stop/start each time ;-)

Thanks all for the support.

Cheers,
Matthias

**Comment by multiple1** [comment]
Why did you close this issue?
Is this a coreelec or kodi or pvr.hts issue?

Running Tvheadend 4.3-1923~gaaca05cc1 server, tested with Test-R channel.

No issues on Windows PC:
Kodi 18.9.0
pvr.hts 4.4.21

No issues on Android:
Kodi 18.9.0
pvr.hts 4.4.21

BUT issues on Coreelec on Odroid N2+
Coreelec 9.2.5
Kodi 18.9.0
pvr.hts 4.4.21.1

Strangely the coreelec version is 4.4.21.1
I can not find this version in this Repo?

**Comment by ksooo** [comment]
No idea what corelec bundles, how it patches pvr.hts and kodi. This repo is for vanilla kodi and addons. Ask for support in the coreelec support channels, please.

**Comment by FernetMenta** [comment]
Detecting PMT switches and signalling those to video player is responsibility of the demuxer. In case of hts protocol this is pvr.hts. It is a confirmed bug and should not be closed.

**Comment by multiple1** [comment]
> No idea what corelec bundles, how it patches pvr.hts and kodi. This repo is for vanilla kodi and addons. Ask for support in the coreelec support channels, please.

Ok, i will look for pvr.hts patches in coreelec.

Like the issue author said http streaming solves this issue on odroid n2+ with beta coreelec (kodi matrix), without http the issue still happens. But http streaming seams to have much higher channel switch times.

**Comment by multiple1** [comment]
I only can find a single patch here:
https://github.com/CoreELEC/CoreELEC/tree/9.2.5/packages/mediacenter/kodi-binary-addons/pvr.hts

Coreelec 19  does not have this patch applied anymore, but i have the same issue without http streaming:
https://github.com/CoreELEC/CoreELEC/tree/coreelec-19/packages/mediacenter/kodi-binary-addons/pvr.hts

**Comment by CvH** [comment]
> But http streaming seams to have much higher channel switch times.

do you have more then one pvr addon activated ? 
http switching is basically identical to hts for me, just more stable compared to hts

**Comment by multiple1** [comment]
Only pvr.hts is installed.
Switching times are hard to measure but with http it seems to take 1s more. Same on Windows PC and Odroid N2+. I am using predictive tuning (set to max 3 tuners).
Is there any debug option to log switch times.

**Comment by multiple1** [comment]
> I only can find a single patch here:
> https://github.com/CoreELEC/CoreELEC/tree/9.2.5/packages/mediacenter/kodi-binary-addons/pvr.hts
> 
> Coreelec 19 does not have this patch applied anymore, but i have the same issue without http streaming:
> https://github.com/CoreELEC/CoreELEC/tree/coreelec-19/packages/mediacenter/kodi-binary-addons/pvr.hts

With the patch applied again the issue still exists in Coreelec 19.
https://github.com/CoreELEC/CoreELEC/tree/coreelec-19/packages/mediacenter/kodi-binary-addons/pvr.hts

**Comment by multiple1** [comment]
> Detecting PMT switches and signalling those to video player is responsibility of the demuxer. In case of hts protocol this is pvr.hts. It is a confirmed bug and should not be closed.

Can anyone reopen this issue as there is only a workaround?
And the workaround using http streaming also freezes for some seconds but it does not get stuck.
How to debug this further?

**Comment by ksooo** [comment]
I fear this has to be fixed in tvheadend's demuxer. Nothing that the pvr.hts addon can do about.
