### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dev-0x7C6** [kodi-pvr/pvr.hts#441]
Please submit license file.

**Comment by ksooo** [comment]
Sorry, what exactly do you mean?

**Comment by Jalle19** [comment]
He means the repository is missing a LICENSE file, e.g. GPL. I guess since we integrate pretty tightly with Kodi we should/have to use the same license as Kodi?

**Comment by ksooo** [comment]
Sounds reasonable.

**Comment by AlwinEsch** [comment]
About them I can do an next new round over all addons to add the LICENSE file and also (where missing) the:
```xml
    <license>GPL-2.0</license>
    <source>https://github.com/kodi-pvr/pvr.hts</source>
    <forum>https://forum.kodi.tv/forumdisplay.php?fid=168</forum>
```
and add them https://www.gnu.org/licenses/old-licenses/gpl-2.0.md or https://github.com/nevir/readable-licenses/blob/master/markdown/GPLv2-LICENSE.md as `LICENSE.md`

**Comment by CvH** [comment]
> I guess since we integrate pretty tightly with Kodi we should/have to use the same license as Kodi?

just saying, this is basically re licencing (if no licence is stated every author has the personal copyright for each commit) - make sure you get the okay from all author to prevent the GPL warriors to complain

**Comment by Jalle19** [comment]
Yeah that's true

**Comment by Jalle19** [comment]
Actually, all source files have the GPL license header already, so this already open source. Adding a LICENSE.md to the root should suffice.

**Comment by Jalle19** [comment]
Actually, all source files have the GPL license header already, so this already open source. Adding a LICENSE.md to the root should suffice.

**Comment by AlwinEsch** [comment]
About the License, started to add now on the addons , this the first https://github.com/kodi-pvr/pvr.argustv and here about this https://github.com/kodi-pvr/pvr.hts/pull/447

**Comment by ksooo** [comment]
As we meanwhile have a LICENSE.md, I guess it is okay to close this issue.
