### ISSUE TITLE
DVR lifetime default of 3 months is not synchronized with TVH backend and can unintentionally delete recordings

### ISSUE THREAD

**Issue by m4tt075** [kodi-pvr/pvr.hts#458]
Last week, I started realizing, that some recordings were deleted after 3 months, although my TVH backend has always been configured to keep recordings "forever". I then learned that there is a (newish?) timer setting on recording retention in the pvr.hts addon configuration, which defaulted to 3 months, and "overrules" the backend setting. Maybe also the default of 3 months is newish (based on recent Kodi upgrades?). I don't know. I also don't know whether this is a "broader" issue. There was at least one other user on Kodinerds, who struggled with the same problem.

In any case, I don't think that having two (independent) settings on recording retention makes sense. Personally, I'd consider that setting to sit naturally in the backend (as it used to be?), as it is probably mostly about managing disk space on the server. Of course it could also be removed from the backend instead. But if you have both, I'd expect them to be synchronized.

Hope that makes sense. Any thoughts appreciated...

**Comment by ksooo** [comment]
Sorry, works as designed.

**Comment by ksooo** [comment]
Not possible to sync the values as backend does not offer an API for this.

**Comment by ksooo** [comment]
The setting including its default value in the addon is there for years, btw.

https://github.com/kodi-pvr/pvr.hts/pull/138/commits/92b1919ec39f346e9cdb922a72b2bc439492ccb8 <= Dec 2015

**Comment by ksooo** [comment]
So, cant be so much of a problem, otherwise we would have gotten many many complaints earlier.

**Comment by FernetMenta** [comment]
Anyway, I can confirm that there was a change in behaviour recently. A friend of mine complained about disappearing recordings. Maybe the setting was ignored in earlier versions or the default values was "accidentally" set to infinity or disk full. IMO a default of three months is not user friendly.

**Comment by ksooo** [comment]
@FernetMenta  Thanks for the feedback. Setting the default to "infinite" to avoid unexpected data loss is a good idea. However, syncing with the backend setting, which would be the best solution, is currently not possible. As far as I know there is no API for that.

**Comment by m4tt075** [comment]
Wow, I'm honored! If both of you are looking into this, I know it will be alright eventually...   :-)
Thanks, guys!

**Comment by m4tt075** [comment]
OK, I've just PRed the proposed workaround. I'll also change the issue title to generalize it. @ksooo : Could you please reopen the issue, until the synchronization (or another) solution has been implemented? In case @FernetMenta and I are right, and the issue has only popped up relatively recently (for whatever reason), it might help if other users can find it as well. Thanks for your consideration...

**Comment by m4tt075** [comment]
Another idea: Could we extend the `dvr_lifetime` setting by an additional option "Use TVH backend setting" and just default to that? We could also add help text in the setting which alerts users that the setting "overrules" the backend setting. This would have two advantages: Firstly, the user would have to actively intervene in order to overrule the backend setting. Secondly, the user is fully aware that the backend setting will be overruled in case a non-default value is specified.

**Comment by ksooo** [comment]
> Another idea: Could we extend the dvr_lifetime setting by an additional option "Use TVH backend setting" and just default to that? We could also add help text in the setting which alerts users that the setting "overrules" the backend setting. This would have two advantages: Firstly, the user would have to actively intervene in order to overrule the backend setting. Secondly, the user is fully aware that the backend setting will be overruled in case a non-default value is specified.

 Well, no. To much effort for just a small issue. If we change the default to 'forever' this should be sufficient.

> in case FernetMenta and I are right, and the issue has only popped up relatively recently (for whatever reason)

 Not 100% sure, but the only thing I can imagine that could have caused this change is an upgrade of the tvheadend backend from some version less official 4.2 to 4.2.x, because 4.2 introduced some intrusive changes with respect to recordings lifetime management.

**Comment by ksooo** [comment]
> Another idea: Could we extend the dvr_lifetime setting by an additional option "Use TVH backend setting" and just default to that? 

 On second thought, I like that idea and it should be easy to implement.

> We could also add help text in the setting which alerts users that the setting "overrules" the backend setting.

 Nobody reads those help texts and imo it should be clear anyway that a setting in the addon overrides the backend setting.

**Comment by m4tt075** [comment]
Thanks much for implementing this, @ksooo!!!
