### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by ghost** [kodi-pvr/pvr.hts#462]
From the Kodi folder (I have it installed through RetroPie) I get the following error when building the addon.

![59800FAA-8593-4BEC-B047-B22A3474E8EE](https://user-images.githubusercontent.com/45421716/87126499-90df8880-c28c-11ea-8126-a57ffe541b03.jpeg)

What is wrong?

**Comment by ghost** [comment]
> From the Kodi folder (I have it installed through RetroPie) I get the following error when building the addon.
> 
> ![59800FAA-8593-4BEC-B047-B22A3474E8EE](https://user-images.githubusercontent.com/45421716/87126499-90df8880-c28c-11ea-8126-a57ffe541b03.jpeg)
> 
> What is wrong?

@ksooo

**Comment by ksooo** [comment]
You need to build pvr.hts Matrix branch against latest xbmc master branch. Seems, your xbmc source is outdated.

**Comment by ghost** [comment]
For all facing similar challenges:
- Make sure you check out the same branches. I had to `git clone --branch=Leia ...`
