### ISSUE TITLE
Streaming profile not set when startup is set to "Play TV"

### ISSUE THREAD

**Issue by ljalves** [kodi-pvr/pvr.hts#464]
When Kodi is set to automatically start Live TV (Settings->Interface->Startup->Perform on startup=Play TV) the profile used in the streaming is the "default" profile and not the one set in the Addon config.

I tried to check the logs but there's no reference to the profile in use.

**Comment by Jalle19** [comment]
Can you enable trace debugging in the addon's settings and post it? It should say something about the profile used IIRC.

**Comment by ljalves** [comment]
I tried, but it doesn't say anything about profiles in use.

**Comment by ljalves** [comment]
I might be wrong, but I suspect that this is what happens:
- Kodi starts and immediately lauchs Live TV and plays last tuned channel
- At this time, the profile list has not yet been received from the server.
- Since the profile in the addon config is not on the "valid profile list", it uses the default.

From the logs I could confirm that the streaming starts before the profile list is queried to the server.

**Comment by ljalves** [comment]
I believe my suspicious is correct.
Profile is set here: https://github.com/kodi-pvr/pvr.hts/blob/Matrix/src/Tvheadend.cpp#L1925
But the tv channel starts playing way before "SyncCompleted" ends.

**Comment by Jalle19** [comment]
You're probably right, I guess the profile stuff should be done earlier before the addon signals Kodi that it has initialized.
