### ISSUE TITLE
frequent UI freeze on LibreELEC / OSMC

### ISSUE THREAD

**Issue by christianrauch** [kodi-pvr/pvr.hts#465]
I get very frequent UI freezes when the Tvheadend plugin loads the available channels and records in the overview on LibreELEC and OSMC on a Raspberry Pi 1. I can still login via ssh etc. but the Kodi UI becomes completely frozen at 100% CPU usage.

Since I can still login via ssh and this happens before playing any live stream, I think that this issue is different from https://github.com/kodi-pvr/pvr.hts/issues/307.

I get a couple of errors:
```
ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command getDiskSpace failed: No response received
ERROR: GetDriveSpace: Add-on 'Tvheadend:omv.local:9982' returned an error: server error
ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to read packet (Bad file descriptor)
ERROR: GetTimers: Add-on 'Tvheadend:omv.local:9982' returned an error: the command failed
ERROR: GetTimers: PVR client 'Tvheadend:omv.local:9982' returned an error: the command failed
```
But I am not sure if they actually cause the freeze or if they are just a symptom of the freeze.

I have this issue since years on the Raspberry Pi, but never encountered them on more capable hardware like my Ubuntu laptop. I have the feeling that this is some kind of race condition that is more likely triggered on slower single-core systems. If I restart the Pi a sufficient amount of times, it will successfully read all the metadata and let me access live TV streams.

Any ideas how I can further debug this issue, e.g. which "server error" is produced and which "command failed"?

Full logs:
`kodi.log`: https://pastebin.com/raw/zts4gHtA
`kodi_crash.log` (triggered by `-SIGSEGV`): https://pastebin.com/raw/VHhT3d7v

**Comment by Jalle19** [comment]
Honestly, a first-gen Raspberry Pi is simple so slow that freezes like this are bound to happen.

**Comment by Jalle19** [comment]
Are you sure it doesn't finish loading after a while? Give it 10 minutes or so.

**Comment by christianrauch** [comment]
> Honestly, a first-gen Raspberry Pi is simple so slow that freezes like this are bound to happen.

What do you mean by that? The hardware is more than capable to run Kodi. Do you mean it is just a give that deadlocks will happen on this hardware, i.e. that the slow Pi 1 will expose software bugs more likely?

If it would be a hardware issue, I would not be able to use it once in a while without this issue showing up. The issue is only frequently, not consistently.

> Are you sure it doesn't finish loading after a while? Give it 10 minutes or so.

I waited 2.5h and nothing happened. Trust me, the UI is frozen and I can still login via ssh.

**Comment by Jalle19** [comment]
Is tvheadend running on the same machine? Have you checked if the issue still occurs if you run the server on a separate device?

**Comment by christianrauch** [comment]
> Is tvheadend running on the same machine? Have you checked if the issue still occurs if you run the server on a separate device?

No. The Tvheadend server is not running on the Pi, but on a dedicated server. The Pi and my laptop are connected over WiFi to a AP/router and the server is connected via wired Ethernet. The issue also occurs when the Pi is connected via wired Ethernet.

**Comment by christianrauch** [comment]
@Jalle19 I am able to prevent this issue by simply increasing the `getDiskSpace` timeout (https://github.com/kodi-pvr/pvr.hts/pull/466).

While this issue is indirectly caused by the slow hardware of the Pi 1 and thus the large response times, this would happen with any latency larger than the default response timeout of 5 seconds. Increasing this timeout is just a workaround since the plugin and Kodi should continue to operate if no response has been received instead of locking the UI.

**Comment by ksooo** [comment]
Blocking the UI means Kodi is not reacting  to any user input while pvr.hts is waiting for getdiskspace? Strange, as Kodi uses a special thread for polling those values from the add-ons. This thread was introduced exactly to avoid blocking the UI.

**Comment by christianrauch** [comment]
> Blocking the UI means Kodi is not reacting to any user input while pvr.hts is waiting for getdiskspace? Strange, as Kodi uses a special thread for polling those values from the add-ons. This thread was introduced exactly to avoid blocking the UI.

No, this is after `getDiskSpace` fails / timeouts.

I think the real reason is some unsolved race condition. There are other ways to prevent the UI freeze if `getDiskSpace` fails, e.g. by adding an arbitrary command before `return PVR_ERROR_SERVER_ERROR;`. However, increasing the timeout solves the issue of the failing `getDiskSpace` method and also makes this race condition much less likely.

**Comment by ksooo** [comment]
What is your definition of "UI freeze", please? Is it Kodi not being responsive to user input?

And this Kodi UI freeze occurs always after the call to tvheadend's getdiskspace method via pvr.hts fails?

**Comment by christianrauch** [comment]
> What is your definition of "UI freeze", please? Is it Kodi not being responsive to user input?

Yes. The UI is not updated at all. E.g. the clock time stays constant and the animated circular progress "bars" are stuck at a state.

> And this Kodi UI freeze occurs always after the call to tvheadend's getdiskspace method via pvr.hts fails?

Not always, only very frequent. It never occurred without the hts plugin; only after the plugin has been installed and configured. I think this is a race condition, indirectly caused by the failing `getDiskSpace`. The outcome will change by slight changes to the code. E.g. just printing debug information will already change the outcome of the UI freeze (in my setting), but it will of course not change the outcome of the `getDiskSpace` call.

The PR #466 will fix the timeout issue with the `getDiskSpace` method, but it will of course not fix the original race condition.

**Comment by ksooo** [comment]
@Jalle19 this looks suspicious: https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/guilib/guiinfo/PVRGUIInfo.cpp#L1698

**Comment by ksooo** [comment]
Could you give this a try, but without applying also #466. I want to see whether the GUI freeze is fixed after running in the getDiskSpace timeout.

```diff
diff --git a/src/tvheadend/HTSPConnection.cpp b/src/tvheadend/HTSPConnection.cpp
index ce55afb..db93fab 100644
--- a/src/tvheadend/HTSPConnection.cpp
+++ b/src/tvheadend/HTSPConnection.cpp
@@ -557,8 +557,6 @@ void HTSPConnection::Register()
   std::string pass = Settings::GetInstance().GetPassword();
 
   {
-    CLockObject lock(m_mutex);
-
     /* Send Greeting */
     Logger::Log(LogLevel::LEVEL_DEBUG, "sending hello");
     if (!SendHello())
@@ -581,7 +579,6 @@ void HTSPConnection::Register()
 
     /* Send Auth */
     Logger::Log(LogLevel::LEVEL_DEBUG, "sending auth");
-
     if (!SendAuth(user, pass))
     {
       SetState(PVR_CONNECTION_STATE_ACCESS_DENIED);
@@ -595,15 +592,19 @@ void HTSPConnection::Register()
 
     Logger::Log(LogLevel::LEVEL_DEBUG, "registered");
     SetState(PVR_CONNECTION_STATE_CONNECTED);
-    m_ready = true;
-    m_regCond.Broadcast();
+
+    {
+      CLockObject lock(m_mutex);
+      m_ready = true;
+      m_regCond.Broadcast();
+    }
     return;
   }
 
 fail:
   if (!m_suspended)
   {
-    /* Don't immediately reconnect (spare server CPU cycles)*/
+    /* Don't immediately reconnect (spare server CPU cycles) */
     Sleep(SLOW_RECONNECT_INTERVAL);
     Disconnect();
   }
@@ -632,7 +633,6 @@ void* HTSPConnection::Process()
       if (m_socket)
         delete m_socket;
 
-      m_connListener.Disconnected();
       m_socket = new CTcpSocket(host.c_str(), port);
       m_ready = false;
       m_seq = 0;
@@ -643,6 +643,8 @@ void* HTSPConnection::Process()
       }
     }
 
+    m_connListener.Disconnected();
+
     while (m_suspended)
     {
       Logger::Log(LogLevel::LEVEL_DEBUG, "suspended. Waiting for wakeup...");
```

**Comment by christianrauch** [comment]
> Could you give this a try, but without applying also #466. I want to see whether the GUI freeze is fixed after running in the getDiskSpace timeout.

Your patch indeed fixes the UI freezes that I saw. Kodi now boots fully without UI freeze 10/10 even with the `Command getDiskSpace failed: No response received` error.

**Comment by ksooo** [comment]
The initial fix causes deadlocks at other places. Reopening...
