### ISSUE TITLE
Season and episode numbers not displayed on the recordings

### ISSUE THREAD

**Issue by jake404** [kodi-pvr/pvr.hts#477]
I recently moved from TVMosaic to TVHeadend and I noticed that the season and episode numbers are not displayed on the recordings in Kodi. I can, however, see them in the TVHeadend webUI.

**Comment by ksooo** [comment]
feature request

**Comment by ksooo** [comment]
Screen shot of the TVH Web UI showing the numbers, please. Thx.

**Comment by jake404** [comment]
<a href="https://ibb.co/CndJJKQ"><img src="https://i.ibb.co/CndJJKQ/2020-10-14-16-47-33.png" alt="2020-10-14-16-47-33" border="0"></a>

**Comment by ksooo** [comment]
Interesting. Can you please make a screen shot of the details of that recording in Kodi (hit "i" while selecting this recording in the Recordings window)?

**Comment by jake404** [comment]
I removed that recording, so I made a new one.

EPG
<a href="https://ibb.co/vvqM4rV"><img src="https://i.ibb.co/vvqM4rV/2020-10-14-17-54-28.png" alt="2020-10-14-17-54-28" border="0"></a>

EPG program information
<a href="https://ibb.co/Q83YZJY"><img src="https://i.ibb.co/Q83YZJY/2020-10-14-17-54-36.png" alt="2020-10-14-17-54-36" border="0"></a>

Recording listing
<a href="https://ibb.co/QQcwsSR"><img src="https://i.ibb.co/QQcwsSR/2020-10-14-17-54-19.png" alt="2020-10-14-17-54-19" border="0"></a>

Recording information
<a href="https://ibb.co/JHLvZTN"><img src="https://i.ibb.co/JHLvZTN/2020-10-14-17-54-11.png" alt="2020-10-14-17-54-11" border="0"></a>

TVH webUI
<a href="https://ibb.co/VwHwYsd"><img src="https://i.ibb.co/VwHwYsd/2020-10-14-18-01-10.png" alt="2020-10-14-18-01-10" border="0"></a>

**Comment by ksooo** [comment]
Please send screenshots from vanilla Estuary, no mod.

**Comment by jake404** [comment]
<a href="https://ibb.co/SBbzNXf"><img src="https://i.ibb.co/SBbzNXf/2020-10-14-18-55-18.png" alt="2020-10-14-18-55-18" border="0"></a>

<a href="https://ibb.co/zxpBpZM"><img src="https://i.ibb.co/zxpBpZM/2020-10-14-18-55-24.png" alt="2020-10-14-18-55-24" border="0"></a>

**Comment by ksooo** [comment]
Which tvh version? 4.2.x? 
If so, please update your tvh. 
HTSP API for recording season/episode number was added in tvh 4.3.x!

**Comment by jake404** [comment]
I was running version 4.2.8 (stable), but have now updated to 4.3 (unstable), but I still can't see the season and episode numbers.
I'm running Kodi 18.8 with the Tvheadend addon version 4.4.21.

**Comment by ksooo** [comment]
Okay, tvh version is fine. pvr.hts 4.4.21 is also fine. Then we have to check Kodi 18...

**Comment by ksooo** [comment]
Strange. Kodi 18 should also be fine. I'm out of ideas for now, sorry.

**Comment by jake404** [comment]
I had updated TVH to 4.3, the unstable release in the master branch, which didn't help. But after updating to the nightly builds in the master branch, the episode information showed up in the recordings.

**Comment by ksooo** [comment]
Good to know. Issue solved.
