### ISSUE TITLE
Times in the EPG view do not seem to change on DST change

### ISSUE THREAD

**Issue by AndersGustafsson** [kodi-pvr/pvr.hts#480]
Hi! Please see this thread: https://discourse.osmc.tv/t/epg-and-dst-change/87379/8

In my case, the client is OSMC/Kodi running on a Vero4k and TVHeadend runs on a separate box (OpenSuSe). When DST changed last sunday the display on OSMC/Kodi was one hour off. When I checked the TVHeadend web interface, times were right. For me, restarting OSMC fixed it. Others reported that just restarting the TVHeadend plugin fixed it.

It will probably be 6 months until next time, but what should I check if it happens again?

**Comment by ksooo** [comment]
Long standing kodi issue. Not to be solved in the addon.

**Comment by AndersGustafsson** [comment]
OK. Fair enough. Can you please elaborate (or provide link) to the Kodi issue?
