### ISSUE TITLE
Stream read chunk size

### ISSUE THREAD

**Issue by danielkucera** [kodi-pvr/pvr.hts#482]
The option description says:
```
Stream read chunk size for recordings
```
Does this really apply for recordings only? Its value is returned in hts client method `GetStreamReadChunkSize`

From this it seems it also affects live stream buffering:
https://github.com/xbmc/xbmc/blob/04202f6caefddd12539a9c00350d0ba44e0c3366/xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/PVR.h#L2610

**Comment by danielkucera** [comment]
According to my testing it also seem to influence live streaming. Setting some bigger default (e.g. 256kB) could help many people with not-so-great Internet lines.

**Comment by Jalle19** [comment]
A few lines below the one you linked there is https://github.com/xbmc/xbmc/blob/04202f6caefddd12539a9c00350d0ba44e0c3366/xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/PVR.h#L2615 ("Optional, and only used if not reading from demuxer")

**Comment by ksooo** [comment]
Is this still an issue with latest Kodi v19 nightly builds? If I get no response within two weeks, I will close this issue.

**Comment by ksooo** [comment]
Closing.
