### ISSUE TITLE
8.2.1-Matrix fails to compile: ‘PVR_ERROR CTvheadend::SetEPGMaxFutureDays(int)’ marked ‘override’, but does not override

### ISSUE THREAD

**Issue by candrews** [kodi-pvr/pvr.hts#491]
Compiling version 8.2.1-Matrix of this plugin against kodi-19.0_beta2 results in a compilation failure:
```
pvr.hts-8.2.1-Matrix/src/Tvheadend.h:121:13: error: ‘PVR_ERROR CTvheadend::SetEPGMaxFutureDays(int)’ marked ‘override’, but does not override
```
Here's the full build output: https://765058.bugs.gentoo.org/attachment.cgi?id=682507

Originally reported at https://bugs.gentoo.org/765058

**Comment by bkuhls** [comment]
Kodi needs https://github.com/xbmc/xbmc/pull/19035 which was committed after the release of beta2.
