### ISSUE TITLE
changing htsp port and addon fails

### ISSUE THREAD

**Issue by glenb77** [kodi-pvr/pvr.hts#495]
i had to change my tvheadend server to use a different htsp port because of a conflict, i set it to 9980, left http at 9981. the server correctly is listening on 9980, but when i change the port number in settings in the pvr addon, i lose the channels and the recordings. any idea if something else i can change or where in the code this is failing.. thanks

**Comment by ksooo** [comment]
without a debug log I can say absolutely nothing

**Comment by ksooo** [comment]
Please provide a debug log. Otherwise I will close this issue.

**Comment by ksooo** [comment]
No log, no issue.
