### ISSUE TITLE
Compatibility problem for Kodi 19 under Windows 10

### ISSUE THREAD

**Issue by enigma131** [kodi-pvr/pvr.hts#497]
After Linux distros, I have to move to Kodi 19 for x reasons under Windows 10.
After that it had done plugin auto migrations, and there is a conflict with HTS addon (it says it i not compatible) . Dvbviewer's one is compatible and works.
Any ways to resolve this ?
ps: Linux distros are working under kodi 19 + hts plugin

**Comment by ksooo** [comment]
Not something that can be fixed in the addon. Seems we have problems with the content of our addon repos @wsnipex ?

**Comment by wsnipex** [comment]
why? https://mirrors.kodi.tv/addons/matrix/pvr.hts+windows-x86_64/

**Comment by ksooo** [comment]
Okay, latest windows version of pvr.hts is on the mirrors, so outdated repo infos in kodi? 

Goto "My add-ons" -> "Add-on repository" -> "Kodi add-on repository" -> open context menu -> "Check for updates". Latest version of pvr.hts should be available afterwards.

**Comment by enigma131** [comment]
Thanks for prompt response. Hum got it working by removing the plug-in, then reinstall it and got finally v 8.2.3. I think the auto migration of plug-ins is little buggy under windows, it was working under linux.
I have a little other problem since Kodi 19.
I have in fact 2 pvr plug-ins, hts and dvbviewer because server is sometimes under Linux and some times under Windows and boths are ativated.
Under earlier version of Kodi, this wasn't a problem.
Under Kodi 19, some times i have double channel names (cache problem ?) , so i have to deactivate the unused one.
I don't know if it is coming from one of pvr plug-in or from Kodi 19 or a new setting?
Any idea ?

**Comment by ksooo** [comment]
> I have a little other problem since Kodi 19.

 Please open an issue, include step-by-step instructions how to reproduce and a proper debug log. => https://github.com/xbmc/xbmc/issues

**Comment by enigma131** [comment]
next is here : https://github.com/xbmc/xbmc/issues/19345
