### ISSUE TITLE
Audio stream not detected sometimes

### ISSUE THREAD

**Issue by TheChoconut** [kodi-pvr/pvr.hts#503]
Log at 2021-04-09 20:59:40.965
Kodi is opening a Live TV channel which has a HEVC, AAC and a TELETEXT stream. 

First it loads HEVC and AAC streams but then the data changes and it loads HEVC and TELETEXT streams (without AAC). 
AAC stream is not loaded and no audio is played.

Steps to reproduce: 
Unknown, seems to happen at random. Play random TV channels and sometimes this happens.

This is part of log with debugging enabled.
[cleaned_kodi.log](https://github.com/kodi-pvr/pvr.hts/files/6288696/cleaned_kodi.log)

**Comment by erbasandrade** [comment]
I have similar problems
https://forum.kodi.tv/showthread.php?tid=357987&pid=2986094#pid2986094

**Comment by ksooo** [comment]
I want the full unmodified log, not what you think I might be interested in, thanks.

**Comment by ksooo** [comment]
Anyway, the add-on is just passing the stream data it gets from tvheadend without modifying it. So, I'm almost sure that this is a tvheadend or Kodi problem, but nothing the add-on can do about.

**Comment by TheChoconut** [comment]
Can you please look at this log again?
I'm providing my full log as this now happened on my Windows machine. And the bug is different. This could point to a tvheadend issue but some guidance on where to look would be nice.

This is the service which had problems before even though it has audio specified in the Tvheadend interface and it usually does load.
![image](https://user-images.githubusercontent.com/16463535/114264919-1051e200-99ee-11eb-873d-b9d4b871e6b7.png)

2021-04-10 11:10:51.735 it starts loading, at 2021-04-10 11:10:54.490 it makes the subscription.

Is this a Tvheadend bug then? Should I pass this issue to their forum?
[kodi.log](https://github.com/kodi-pvr/pvr.hts/files/6289568/kodi.log)

**Comment by ksooo** [comment]
First of all, please update to Kodi 19.0 official release version. You are running beta 2, which is rather old.

**Comment by ksooo** [comment]
... and the pvr.hts version you are using is also outdated (8.1.3).

So, please update both Kodi and the add-on and report back whether your problem still persists.

**Comment by TheChoconut** [comment]
Updated to latest release version of Kodi and pvr.hts.

Happened again, on different channel.
![image](https://user-images.githubusercontent.com/16463535/114276678-0220b780-9a28-11eb-9017-78e6bf2f01d8.png)

2021-04-10 18:06:39.721 T:17948 is demux subscription start.


[kodi.log](https://github.com/kodi-pvr/pvr.hts/files/6290238/kodi.log)

**Comment by hagaygo** [comment]
@TheChoconut I had a lot of problems with different streams.
All of them were o.k while playing them via VLC.
On latest addon version a http streaming option was introduced, try enabling it.

https://github.com/kodi-pvr/pvr.hts/pull/476

**Comment by TheChoconut** [comment]
> @TheChoconut I had a lot of problems with different streams.
> All of them were o.k while playing them via VLC.
> On latest addon version a http streaming option was introduced, try enabling it.
> 
> #476

Not the solution I want. Also, HTTP streaming is not working for me (slow zapping and stream is stuttering). 
I've been doing some testing on my own and it seems like this could be a Tvheadend issue, but I want to be sure.

I've been running a custom script that uses ffprobe to check all the given data from a Tvheadend stream and read the available streams from it. Sometimes, it would only manage to read HEVC and TELETEXT (also no metadata is read) and audio stream wouldn't get recognized as audio but some unknown stream?

I want to know if its possible that exactly this is happening while demuxing in pvr.hts?

[254268960_fail.txt](https://github.com/kodi-pvr/pvr.hts/files/6291625/254268960_fail.txt)
[254268960_good.txt](https://github.com/kodi-pvr/pvr.hts/files/6291626/254268960_good.txt)
