### ISSUE TITLE
Playback position not saved

### ISSUE THREAD

**Issue by H-Sachse** [kodi-pvr/pvr.hts#505]
Since upgrading to Kodi19 / PVR-HTS 8.3 the playback position of a recording is lost when restarting Kodi.
This happens on both Windows and Linux.
It did not happen with Kodi 18.9 / PVR-HTS 4.4.21
TVheadend version is 4.3 (on a different computer and unchanged)

To Reproduce:
- Start Kodi
- Start playback of a recording via the TV->Recordings selection
- Skip ahead in the recording
- Stop playback
- Observe the icon next to the recording, it will show the "partially watched" state
- Open the context menu, it will show a "resume from ..." entry
- Restart Kodi
- Select the previously used recording.
- Open the context menu, the "resume from ..." entry is missing

**Comment by ksooo** [comment]
Please try latest Kodi 19 nightly build and report back whether problems still occurs.

=> https://github.com/xbmc/xbmc/pull/19451

**Comment by H-Sachse** [comment]
Confirmed fixed with KodiSetup-20210428-082f66cd-Matrix-x64. Seems like the position got stored, but not loaded back after a restart.
