### ISSUE TITLE
DVR configuration profiles is not always respected

### ISSUE THREAD

**Issue by DESK-coder** [kodi-pvr/pvr.hts#509]
Setup:

tvheadend 4.3-1964
Kodi 19
pvr.hts 8.3.0

--

In tvheadend I created a "DVR configuration profile" with SD quality (576p). When I select a channel in Kodi and start recording (red button under the timeline), DVR is recorded with the profile "pass (default profile)", when I go over the program guide and click on "record" there, likewise.

However, when I add a timer rule and schedule a recording, the profile that is entered in tvheadend for the user under "DVR configuration profile" is used.

**Comment by ksooo** [comment]
The pvr.hts add-on currently only supports the default profile, which means there is no possibility to enter a profile when creating a timer or timer rule in Kodi, thus tvheadend will always use the default profile. Support for non-default configs could be added to the add-on as the HTSP API supports this. However, a clean solution not only needs changes in the add-on, but also an PVR-Addon API change and some Kodi PVR core changes. All doable, when somebody with the required skills finds some time for this some day.

**Comment by Gee1111** [comment]
up ^^

**Comment by ksooo** [comment]
down ;-)

**Comment by Gee1111** [comment]
:( relly need this feature

**Comment by ksooo** [comment]
Then, come up with a PR or be patient. ;-)

**Comment by Gee1111** [comment]
i think only the tvh server need to be changed (@ flole).. when user xy is planing a autorecord or manual record tvh server must only use the specified DVR Profile

**Comment by ksooo** [comment]
> i think only the tvh server need to be changed

 Then, this would be the wrong place to discuss this feature.

**Comment by dreamcat4** [comment]
https://tvheadend.org/issues/5930

**Comment by ksooo** [comment]
Closing as a Tvheadend issue.
