### ISSUE TITLE
Transifex update for pvr addons

### ISSUE THREAD

**Issue by ksooo** [kodi-pvr/pvr.hts#51]
It's long time ago that we did a translation update for the pvr addons. Let's do this before Isengard release. ;-)

**Comment by ksooo** [comment]
@alanwww1 what do you think?

**Comment by MartijnKaijser** [comment]
since it's Isengard only it could be done in the new string folder structure

**Comment by alanwww1** [comment]
I will do it soon. Probably this weekend.
2015.06.27. 13:28 ezt írta ("Martijn Kaijser" <notifications@github.com>):

**Comment by ksooo** [comment]
Cool, thanks @alanwww1

**Comment by alanwww1** [comment]
All updated, both master and Isengard branches. Might worth a bump in Kodi master to the new commits.
Thanks guys, cheers, Attila

**Comment by MartijnKaijser** [comment]
@alanwww1 vdr.vsni Isengard branch isn't updated

**Comment by MartijnKaijser** [comment]
thx btw :)

**Comment by alanwww1** [comment]
@MartijnKaijser Thanks for the heads up. I just forgot to push the commit. Now it is done.
btw, it can happen because I am doing things semi-manually, as I am still reworking my sync infrastructure.

**Comment by MartijnKaijser** [comment]
np thx :)
bumping them now
