### ISSUE TITLE
Not loading icons when using https reverse proxy

### ISSUE THREAD

**Issue by RealCommerzpunk** [kodi-pvr/pvr.hts#519]
Hello,
i have set up my TVH to be accessed via internet and reverse proxy.
It works fine, but for some reason i dont get any icons / picons when i use it that way.
The channels are all loading and playing, but just the icons are missing.
When i check the logs, it says: "CCurlFile::Open failed with code 400 for http://tvh.domain.de:443/tvheadend/imagecache/411"

Of course i have checked the "use https" inside the addon. But it seems to find the icon with http.
When i simply add the "s" manual, it works in my browser. Just the http produces Error 400.

Is it a bug?

**Comment by ksooo** [comment]
Which authentication scheme is tvh configured to use? This must match the auth scheme supported and used by your client.

**Comment by ksooo** [comment]
Which Kodi version? Which PVR.hts version? Which tvh version? We need a debug log, which contains all these information and more.

**Comment by ksooo** [comment]
If you use Kodi < 19 and you have configured tvh to use only digest authentication, the effect will be exactly what you describe.

Kodi < 19 does not support digest authentication properly. Workaround is to configure tvh to use only basic auth or both basic and digest.

Kodi 19 will work fine with tvh configured to use only digest auth and no basic auth.

**Comment by RealCommerzpunk** [comment]
[kodi.log](https://github.com/kodi-pvr/pvr.hts/files/6835175/kodi.log)
Hello and thanks.
The authentication scheme is configured to "both plain and digest".
(Just by the way, when i log into the webif via https it shows up the icons just normal)
It is Kodi 19.1, the addon is 8.33, TVH is 4.3-1967

Edit: log attached

Edit 2: chaged to only digest auth and nothing changed, the log includes this change

**Comment by ksooo** [comment]
> http://tvh.nas-hunda.de:443/tvheadend/imagecache/456

http ? => pvr.hts settings => use https - does this help?

**Comment by RealCommerzpunk** [comment]
no, it does not. And thats the point why i thought it must be a bug. ;)

**Comment by ksooo** [comment]
entered in my browser: http://tvh.nas-hunda.de:443/tvheadend/imagecache/456

=> 
400 Bad Request
The plain HTTP request was sent to HTTPS port

**Comment by RealCommerzpunk** [comment]
exactly. thats what i get too. and thats ok, because its only accessible via https. i dont know why the addon tries http

**Comment by ksooo** [comment]
I will check that.

**Comment by ksooo** [comment]
Are you 100% sure you enabled "Use HTTPS" in the settings of the pvr.hts add-on?

**Comment by RealCommerzpunk** [comment]
I am! that was the point to switch over to matrix because your great addon provides this magic button for using reverse proxy.

**Comment by ksooo** [comment]
Show me a screenshot of the setting, please. Reading the code, if HTTPS is enabled, the image URL must start with https://

**Comment by RealCommerzpunk** [comment]
![grafik](https://user-images.githubusercontent.com/41644537/126048090-3392e88f-0a45-4205-8257-3c345f4a0cdf.png)

Here we go

**Comment by ksooo** [comment]
Okay thanks. Very strange. Have you tried to clean Kodi userdata folder and to setup things again from scratch? Maybe we're having some image caching problems on Kodi side? Just guessing.

**Comment by RealCommerzpunk** [comment]
I completly cleaned the userdata, no problem because its my test setup:

![grafik](https://user-images.githubusercontent.com/41644537/126049623-8511dded-5dea-4748-957d-2ea8a14f2152.png)

Same in a log:
2021-07-17 23:19:15.989 T:7548    ERROR <general>: CFileCache::XFILE::CFileCache::Open - <http://USERNAME:PASSWORD@tvh.nas-hunda.de:443/tvheadend/imagecache/455> failed to open
2021-07-17 23:19:15.994 T:7548    ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 400
2021-07-17 23:19:15.994 T:7548    ERROR <general>: CCurlFile::Open failed with code 400 for http://tvh.nas-hunda.de:443/tvheadend/imagecache/451:

Its still http

**Comment by ksooo** [comment]
Are you able to take a look into your TV38.db file, located in userdata/Databases ? Are the values stored there for sIconPath correct, means https:// URLs there?

**Comment by ksooo** [comment]
I found the problem. It is a really stupid bug in pvr.hts. Fix to follow.

**Comment by RealCommerzpunk** [comment]
Thank you very much!

**Comment by ksooo** [comment]
Here is a test build for the add-on containing the fix: https://jenkins.kodi.tv/view/Addons/job/kodi-pvr/job/pvr.hts/view/change-requests/job/PR-520/lastSuccessfulBuild/artifact/cmake/addons/build/zips/pvr.hts+windows-i686/pvr.hts-8.3.4.zip (32 bit windows)

EDIT: 64 bit windows: https://jenkins.kodi.tv/view/Addons/job/kodi-pvr/job/pvr.hts/view/change-requests/job/PR-520/lastSuccessfulBuild/artifact/cmake/addons/build/zips/pvr.hts+windows-x86_64/pvr.hts-8.3.4.zip

Could you install, test and report back?

**Comment by RealCommerzpunk** [comment]
This is pretty pretty and a quick and perfect fix for that.
THANKS!

![grafik](https://user-images.githubusercontent.com/41644537/126064339-d4c5bf0d-8331-4cd0-8335-a645614e503b.png)
