### ISSUE TITLE
Settings for tvheadend with http_root

### ISSUE THREAD

**Issue by lucentwolf** [kodi-pvr/pvr.hts#528]
If tvheadend is configured with http_root (eg to be accessible on http://x.x.x.x:9981/tvh), and the additional http_root (/tvh) is added to the host in hts addon's configuration, it will try to connec to

http://x.x.x.x/tvh:9981 -> which fails, because it's an invalid url

Now, adding the trailing /tvh to the server port instead of the host (hoping it will concat the url to http://x.x.x.x:9981/tvh) also fails, since the port setting will only accept numbers.

Currently the only way I see to get this working is by going through a webserver and reverse proxying with some rewrite acrobatics... quite some effort just to correct the url.

Seems to me, we'd either need an additional setting (e.g. path), or a change in the code, where the port is inserted before the first / of the host string; and in case if there's no / appending it; or allowing alphanum values in the port setting (quirky)

**Comment by ksooo** [comment]
I think a setting for the path is the way to go.

**Comment by ksooo** [comment]
> If tvheadend is configured with http_root

 How exactly did you configure it? From what I see in the pvr.hts code the tvh server sends the webroot when pvr.hts connects to it. pvr.hts then picks up the http root and completes all request accordingly.
 
 So, it should work automatically, without the need to enter the http root anywhere in pvr.hts settings.

**Comment by lucentwolf** [comment]
Hi, the tvh daemon is started with command line option --http_root /tvh

**Comment by ksooo** [comment]
Then, there should be no need to enter the path in pvr.hts settings. Once connected, tvh sends the http root value to pvr.hts which will use it, then.

So, what is your actual problem?

**Comment by ksooo** [comment]
Can this issue be closed?

**Comment by lucentwolf** [comment]
I was trying to connect remotely through an apache reverse proxy, and needed the http_root since there*s some other service on /

I got it working to reach the tvh web interface, via https://mydomain/tvh that is reverse proxied to http://internal:9981/tvh - but I could not make hts to use this url - even if I start tvh without http_root and configure the reverse proxy accordingly.

**Comment by ksooo** [comment]
@lucentwolf is this still an issue?

**Comment by lucentwolf** [comment]
hey ks000

...well; I'm ssh-tunneling now - so i guess this can be closed ;-)
