### ISSUE TITLE
can we add a feature to edit individual timers that are made from an epg based timer rule in kodi

### ISSUE THREAD

**Issue by liam8888999** [kodi-pvr/pvr.hts#529]
in kodi individual recordings (e.g. scheduled once off from the guide) can be edited individually such as extra padding at the end etc. while currently recording, however auto generated recordings from an autorec or timer rule cant be edited individually and only the entire autorec ot timer rule must be edited which is annoying if for example you want to add an extra 5 minutes to a show that is currently recording if it is running overtime

**Comment by ksooo** [comment]
@liam8888999 Can this be done from within TVheadend Web GUI? Then there would be chances to implement this for pvr.hts/Kodi.

**Comment by liam8888999** [comment]
You can do it in the web ui quite easily. It can already be done in kodi for once off recordings just doesn't work for series recordings, they both seem to work the same in the web ui though

**Comment by liam8888999** [comment]
@ksooo did you have any more thoughts on this

**Comment by ksooo** [comment]
No.
