### ISSUE TITLE
Some channels refuse to play live but work fine when played from recording

### ISSUE THREAD

**Issue by deeptho** [kodi-pvr/pvr.hts#533]
I have one specific DVB channel that refuses to play from within kodi with pvr.hts
tested version kodi-pvr-hts-8.3.2-1.fc34.x86_64 on fedora 34.

Sometime 1 still picture appears and sporadicaly (e.g., after 20 seconds_) another one. 
At other times, nothing appears at all. The channel is fine: it can be played live via the web interface
of tvheadend. It can also be recorded and then plays fine in kodi. The only thing that does not work
is live play. All other channels are fine (although many months ago I encountered another channel
with a similar problem; they are rare!)

kodi itself remains functional after stopping the playback but consumes very cpu time (160% or more).
The problem happens all the time on this specific channel (so reproducible).

temp/kodig.log contains very few relevant log messages:
```
2021-08-30 20:14:06.805 T:1261146    INFO <general>: Loading skin file: DialogPVRInfo.xml, load type: LOAD_EVERY_TIME
2021-08-30 20:14:06.878 T:1261146    INFO <general>: VideoPlayer::OpenFile: pvr://channels/tv/All%20channels/pvr.hts_998571427.pvr
2021-08-30 20:14:06.879 T:1263632    INFO <general>: Creating InputStream
2021-08-30 20:14:06.879 T:1263632    INFO <general>: Creating Demuxer
```

ffmpeg -i shows the following information:

```
mpegts @ 0x7f6a7c000bc0] start time for stream 0 is not set in estimate_timings_from_pts
[mpegts @ 0x7f6a7c000bc0] PES packet size mismatch
[mpegts @ 0x7f6a7c000bc0] Packet corrupt (stream = 2, dts = 4823369264).
Input #0, mpegts, from '/mnt/streacom/tvheadend/Familie.ts':
  Duration: 00:01:05.84, start: 53528.452067, bitrate: 2568 kb/s
  Program 1 
    Metadata:
      service_name    : vtm
      service_provider: Telenet
    Stream #0:1[0x1005]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg, top first), 720x576 [SAR 16:11 DAR 20:11], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:2[0x1006](dut): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 128 kb/s
    Stream #0:3[0x1007](dut,dut,eng): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
  No Program
    Stream #0:0[0x12]: Data: epg
```

Log file
[kodi.log](https://github.com/kodi-pvr/pvr.hts/files/7078706/kodi.log)

Short piece of the stream can be found here
[https://0x0.st/-vzd.ts](https://0x0.st/-vzd.ts)

**Comment by ghost** [comment]
I don't know if it was the same root cause, but my kodi (19.1.0 - 85e05228b4) with iptv plugins (8.4.0) crash systematically when I play Live channels. But recorded show is fine.

As workaround I play recorded show and then without stopping, launch live channel and it works.

**Comment by ksooo** [comment]
@deeptho is this still an issue, with latest Kodi version?

**Comment by deeptho** [comment]
Currently I do not see this problem

kodi-pvr-hts-19.0.6-2.fc37.x86_64
kodi-19.5-1.fc37.x86_64
