### ISSUE TITLE
playback recordings and time shift jumping latest per.hts Kodi 19.1 ubuntu 18

### ISSUE THREAD

**Issue by liam8888999** [kodi-pvr/pvr.hts#534]
If I skip forward in a partial/complete recording, or paused live TV buffer, the results are really inconsistent.
Sometime it skips forwards the correct amount, sometimes a smaller amount.
If I repeatedly skip then it often skips backwards a chunk! Occasionally this unexpected backwards skip is to the beginning of the programme (although, at the point of doing this, I'm no where near the end of the recording or buffer).
The top-right "Seeking" display always shows the correct "SEEKING +01:00" (or multiple of) as you'd expect to see, but more often than not I don't end up where I should do. it goes to a negative time so restarts the show. this also happens when fast forwarding and is most noticeable at 32x

I ought to say that I've set the Skip steps to be just -5 and +5, so my skipping is just 1 or more increments of 5minutes

This doesn't happen when I watch the same recordings from "Videos" (via a share), or when watching other videos not recorded with tvheadend - skipping seems to work fine from there - it only happens when playing back partial or complete recordings from TV | Recordings or when pausing live TV and then trying to skip forwards.

**Comment by ksooo** [comment]
@liam8888999  is this still an issue, with latest Kodi version?
