### ISSUE TITLE
Recording playback from distant server

### ISSUE THREAD

**Issue by graza** [kodi-pvr/pvr.hts#543]
I have a Kodi instance that has a very long ping time to the tvheadend server - about 350ms round-trip.  Playing live TV works perfectly well however playing recordings does not.  I had a look at the HTSP protocol used by tvheadend and it seems that live TV is asynchronous while playback of a recording is synchronous.

- Live TV - client sends a subscribtion request and starts receiving asynchronous messages from the server with the program stream.
- Recordings - client sends a fileRead request and waits for the data to come back.

I have tried increasing the buffer to something very big, but it would seem that Kodi doesn't send the fileRead request in time to avoid the buffer running empty.  The result is that Kodi keeps stopping and re-buffering.

- Is there a way to get Kodi to request the next buffer sooner?
- Maybe the pvr.hts add-on could read multiple buffers into an internal queue at the start, or on seeking, so that it's more in control of the queueing of requests?
- Or perhaps there could be an enhancement to the recording playback protocol to allow asynchronous streaming?

**Comment by ksooo** [comment]
Go to the addon's settings and increase recording playback buffer size

**Comment by ksooo** [comment]
> I have tried increasing the buffer to something very big

 Means, you found the setting and increasing its value did not help? For me it always did when testing with distant servers.

**Comment by graza** [comment]
I tried setting to the maximum that Kodi would allow with no joy.  I then tried making it even bigger by logging via SSH and editing the configuration file.

The behaviour changes slightly in that with a bigger buffer it takes longer to load the buffer initially, then plays for a little longer, and then buffers again.

I will see if I can get some debug output...

**Comment by GitHubinat0r** [comment]
Not to hijack this bug report, but it's been a few months since the last activity. I'm in the same boat as @graza and have a distant server where streaming works perfectly for live TV after increasing the 'Stream read chunk size for recordings (KB) to 512. But for recordings, it will continually buffer. I also attempted to increase Kodi's video cache: https://kodi.wiki/view/HOW-TO:Modify_the_video_cache with no luck. Is there another option to adjust?

**Comment by graza** [comment]
Thanks @GitHubinat0r for the bump on this issue.  Travel restrictions have finally eased to the point where I can travel to the remote location and hopefully I can get some meaningful logs for the issue.  

One of the things I have tried is using the tvhclient app on my iPhone.  It works well when playing recordings.  When the network between the two locations isn't too busy I can watch HD recordings.  

SD recordings work any time on the app regardless of network activity.  Howver, the Kodi add-on doesn't work.  Same buffering issue as reported.

Since it works on the iPhone app, I'm wondering what's different about its implementation of the protocol?  It would seem that the playback is handled by VLC, so perhaps there's something in the VLC implementation of buffering, etc...

**Comment by disaster123** [comment]
@GitHubinat0r same for me - Live TV for HD channels work fine - even with chunk size 64k - but playing recordings buffer occasionally even with 512k set. But 512k works better than 64k. I'm wondering in 2MB or something would help.

**Comment by disaster123** [comment]
I even raised it to 2MB via patching the source code but this does not help as well. To me it seems the kodi video cache isn't enabled at all - would this be possible?

**Comment by Jalle19** [comment]
I don't think the general video cache in Kodi is used in this case.

**Comment by ksooo** [comment]
@graza is this still an issue, with latest Kodi version?

**Comment by graza** [comment]
Hi Kai,

Soon I will be travelling to the site where the distant Kodi client is
located and will check again.  Has the implementation of playback changed
in recent versions?

Kind Regards,
Graham

**Comment by ksooo** [comment]
>  Has the implementation of playback changed in recent versions?

Don't know. You will find out by testing I guess.

**Comment by GitHubinat0r** [comment]
Sorry for the delay; I've just tested and the issue is still present.
