### ISSUE TITLE
Kody 19 and htsp plugin v19 on ShieldTV subtitle problem

### ISSUE THREAD

**Issue by aurelmarius** [kodi-pvr/pvr.hts#546]
Hi, i have a strange problem with subtitles on only 2-3 channels. The problem is that the subtitiles are skipping a lot of dialogs, 1 dialog is displayed then 2-3 not and so on. If i select Use http for streaming in addon configuration subtitles are correctly displayed. Tvheadend version is HTS Tvheadend 4.3-1979~g8fc2dfa7e.

**Comment by ksooo** [comment]
TVHeadend problem, nothing pvr.hts can fix. Please open an issue for tvheadend.
