### ISSUE TITLE
Editing existing timer rule and enabling "Start any time" doesn't work

### ISSUE THREAD

**Issue by arnova** [kodi-pvr/pvr.hts#548]
When you edit an already existing timer rule with "Start any time" disabled and enabling "Start any time" for it, it doesn't work. It will keep "Start any time" disabled after finishing editing the timer rule. When directly changing it in the tvheadend webinterface it does work. I've enabled debug tracing but the log didn't give any clue why this doesn't work. Please let me know if you need any additional info.

**Comment by ksooo** [comment]
Sorry, cannot reproduce. Kodi 19.2, latest pvr.hts, latest tvh 4.3

**Comment by arnova** [comment]
Strange: I can reproduce it doing this:
1) Create a new timer rule by adding a timer from within the Guide-window. Obviously the rule is initially created with "Start any time" disabled
2) Go to the "Timer Rules"-window and do "Edit" for the timer rule created in step 1
3) Enable "Start any time" and press OK
4) Notice the rule still having start/stop-times set (and "Start any time" disabled)

In my setup it consistently fails for every rule created this way.

I'm running TVHeadend v4.2.8 but I doubt that could be the issue since it does work when doing it directly using TVH's web interface . Btw. tried with both Kodi 18.9 & 19.2: Same issue.

**Comment by ksooo** [comment]
> Obviously the rule is initially created with "Start any time" disabled

No, for me it gets initially created with "Start any time" enabled. Very strange. 

And tvh 4.2 vs 4.3 could very well be the problem. If it works in the tvh webui this is not a guarantee that it works with the HTSP API. But honestly, 4.2 is so old (although the last official release), I wont dig into this. Waste of time. Update to 4.3 - it's very stable.

**Comment by arnova** [comment]
> No, for me it gets initially created with "Start any time" enabled. Very strange.

Sorry I should have mentioned that: As you noticed, the default setting for "Start any time" is on when creating a new timer rule but sometimes I disable it when creating the initial(!) rule.

I will give TVH 4.3 a try and report back. Hopefully it fixes the issue but I have strong doubts

**Comment by ksooo** [comment]
> I will give TVH 4.3 a try and report back. Hopefully it fixes the issue but I have strong doubts

 Cool. Would be nice to hear whether this fixes your problem.

**Comment by arnova** [comment]
> > I will give TVH 4.3 a try and report back. Hopefully it fixes the issue but I have strong doubts
> 
> Cool. Would be nice to hear whether this fixes your problem.

Just gave it a try: Unfortunately the same issue with TVH 4.3....

**Comment by arnova** [comment]
@ksooo : Do you use "relaxed" for "Start time window calculation"? I think that could make a difference, looking at the code...

**Comment by ksooo** [comment]
No, I’m using strict mode.

**Comment by ksoo** [comment]
Hello Arno, I think you may have mistyped the @ target name for this.
Cheers!

**Comment by arnova** [comment]
@ksooo : I suspect we don't do addon backports for Leia anymore?

**Comment by ksooo** [comment]
Right, Leia is EOL
