### ISSUE TITLE
EPG information from SatIP stream

### ISSUE THREAD

**Issue by chaptergy** [kodi-pvr/pvr.hts#554]
I am not really familiar with the RTSP / SatIP protocol, so forgive me if this is only very surface-level information.

Many Sat>IP boxes provide an RSTP-server which distributes the tv data in the local network as a stream. This stream usually includes EPG information within the stream. The VLC media player is able to use this information and display a program guide:
![image](https://user-images.githubusercontent.com/26956711/141495724-37283409-9df4-4747-aa66-32f3a74328b2.png)

This addon however is unable to use this information, it seems to only support a separate EPG file. It would be cool if the EPG data from the stream could also be used, so a separate file (which is often not available) is not necessary.  
Is there any way I could help with this? 

Thanks!

**Comment by ksooo** [comment]
This add-on supports every EPG data the tvheadend server it is connected to supports. The add-on does not know anything about the way the EPG data is fetched by tvheadend, it just takes what it gets from the backend via a tvheadend API for EPG data. So, if there is a problem / missing functionality, this would be an issue with tvheadend, not this add-on.

**Comment by chaptergy** [comment]
Ah, I'm sorry, this is the wrong repo. The [wiki page of IPTV Simple Client](https://kodi.wiki/view/Add-on:PVR_IPTV_Simple_Client) links to this repo, when it should be https://github.com/kodi-pvr/pvr.iptvsimple.
