### ISSUE TITLE
Add-on is not compatible with Kodi

### ISSUE THREAD

**Issue by Durlyn** [kodi-pvr/pvr.hts#567]
Hi! Happy New Year! 
in the latest version of the Kodi Next (from git) addon does not work. 
log:
Add-on 'pvr.hts' is not compatible with Kodi
CAddonMgr: DisableReason for pvr.hts update to 2

**Comment by ksooo** [comment]
This is intended. Stick to the Addon version from the repo or update to latest Kodi master.

**Comment by phunkyfish** [comment]
There is a API change on going where kodi is out of sync with the addons. It should resolve not be next 24-48 hours
