### ISSUE TITLE
SNR and signal strength not working

### ISSUE THREAD

**Issue by SvenLuebke** [kodi-pvr/pvr.hts#569]
Dear developers!

I'm using Kodi 19 and since three years the SNR and strength is always 0 but I can see the values in TvHeadEnd. Is this normal? If not, how can I fix it?

Thank you and best regards,
Sven

**Comment by hagaygo** [comment]
On my setup it only shows the values on KODI (using default skin) if they are are shown as percentages on Tvheadend web interafces (i have 3 kind of tuners , the one which show as numeric values is shown as 0 on KODI)

**Comment by ksooo** [comment]
Exactly, tvh supports both percentage and numeric values, where Kodi only supports percentage values. Missing feature on Kodi side.

**Comment by SvenLuebke** [comment]
Thank you very much for this explanation. Now I understood the issue. I wasn't aware of it!
