### ISSUE TITLE
pvr.hts: playing recordings does not use video cache

### ISSUE THREAD

**Issue by disaster123** [kodi-pvr/pvr.hts#579]
I'm using a Fire TV Stick connected via WLAN. While this is most of the time pretty stable it might have latency spikes (1-3 in 1-2 hours). While playing HD recordings i'm seeing 3-5 read requests per second (512kb chunk size). If there are spikes or lost packets in WLAN. Playing recordings start to buffer.

As far as i was able to check it seems playing recordings does not use any video cache.

**Comment by Jalle19** [comment]
This is something that has to be fixed in Kodi, not in the addon.
