### ISSUE TITLE
Live-TV buffering issues with htsp streaming (not with http)

### ISSUE THREAD

**Issue by m4tt075** [kodi-pvr/pvr.hts#580]
## Setup 

- Intel-based DIY NAS running OMV and TVH 4.3-2008~ge2ae8f4eb in Docker
- Odroid N2 client running CoreElec 19.4 RC3 (tried RC2, RC1 and 19.3 before, same issue)
- pvr.hts client 19.06 (19.05 before, same issue)

## What happens

It started occasionally about 4-6 weeks ago, but got increasingly worse. Effect is always the same. Live-TV streaming stops, the blue buffering circle occurs, streaming restarts. The kodi.log file captures "stream stalled" messages. Stalling ranges between ~5 seconds (connection to TVH server maintained), to ~15 seconds (when client and server lose the connection). I can see the client losses in the TVH logs on the server-side, but otherwise, there is nothing.

## Analyses so far

- I'm struggling to nail down where the problem originates
- I've looked at network latencies, but could not find anything suspicious
- I don't think there are issues with the Sat signal "upstream" either, as I'm perfectly able to record TV programs and play them without problem (from the recording directory as well as through the TVH client's recording section)
- I've tried to increase the buffer size in the streaming section of the hts client to 128kb and 256kb, still buffering
- I've then tried to stream through http instead of htsp, and the buffering issues are gone. 

## Hypotheses

I've been looking at Kodi and CE forums, but apparently this is not a common issue, as otherwise there would have been way more reports. I know from @FernetMenta that there are "flaws" with the htsp protocol anyways. I suspect that this is the problem. Maybe something is disturbing the streams on the server side, and htsp cannot handle the buffering correctly whereas http can. But I don't know how to debug the issue further.

## Questions
- Have some of you ran into similar problems in the last couple of months?
- Are you aware of bugs / known issues which could be related to this problem?
- Do you have any idea how to debug this problem further?

As always, any insights appreciated...

**Comment by M0dj0** [comment]
I am facing the exact same problem.

Here some information to my setup:
- Server: TVHeadend 4.3-2008 in docker container (network_mode: host) on Raspberry Pi 4 8 GB
- Client 1: Libreelec 11.0-nightly-20220325 with pvr.hts 20.2.2 on Intel NUC8i3BEH
- Client 2: Libreelec 11.0-nightly-20220325 with pvr.hts 20.2.2 on Intel NUC5i5RYH

Stream over HTTP: No Problems (Client 1 & Client 2)
Stream over HTSP: Stuttering after a few seconds with "Uncorrected Blocks" increasing in TVHeadend Server. (Client 1 & Client 2). 
It feels like a depleted cache or so, which doesn't manage to build up anymore and then causes the dropouts.

**_But when I start a HTSP Stream from another Device like TVHClient Addon on Android, there are no problems at all._**

For some reason there seems to be a bug or a different setting in pvr.hts 20.2.2 which pulls everything down.

**Comment by ksooo** [comment]
> But when I start a HTSP Stream from another Device like TVHClient Addon on Android, there are no problems at all.

And you are absolutely sure that this Addon is streaming using HTSP? Do you have some proof, a log maybe?

**Comment by m4tt075** [comment]
I'm not sure. I've resolved my problem in the meantime. It was caused by a Chia container that kept writing to and reading from it's database on my slow HDD NAS drives. Since I've moved the db to a quicker SSD, the stuttering is gone. 

I keep believing that HTSP streaming is more error-prone than HTTP streaming though, i.e. that it is simply not as stable. Not sure this is helpful for you. But you can log into your server and use `docker stats` to see what is causing CPU or memory workload or anything else. I've found that helpful for the diagnostics.

Closing, as my problem was only exposed, but not caused by TVH.
