### ISSUE TITLE
Shared recordings from other users not showing until owner is changed

### ISSUE THREAD

**Issue by flyingstar16** [kodi-pvr/pvr.hts#581]
Hi,

In my setup I have an admin user for myself ("admin") and a low-privileged user ("user") that's only used by Kodi.

Per https://tvheadend.org/boards/5/topics/26241 I can share recordings by adding "View all" to the user's "Video recorder" settings.
![image](https://user-images.githubusercontent.com/582280/162617520-28637f98-6f44-42d9-afe3-a73092675c6a.png)

This works perfectly in the Web UI (as soon as "admin" starts recording, the "user" web interface shows the recording and can play it) but in Kodi the recordings made by the admin user don't show up in the "Recordings" list until I change the Owner to "user".

Then, once I refreshed the list, I can revert the owner back to "admin" and the recording is still available (as in "visible in the list") and playable.

I think there is a filter somewhere in the code that only lists recordings from the user in Settings, when in reality it should return them all.

Can this be fixed? (I tried looking at the code but I'm not a C++ programmer and I can't understand where the filtering I mentioned above is).

Side note: if, after having a recording show up, I switch its ownership to "admin" and remove "View all" from "user" the recording stays in the list, but trying to play it returns an error (I'm guessing because TVHeadend refuses to serve it); re-adding "View all" makes it playable again.

Thanks you!

**Comment by ksooo** [comment]
> Can this be fixed?

Yes, but in tvheadend, not in this add-on. The add-on only displays what it gets from the tvheadend server. 
Please open an issue for tvheadend here: https://tvheadend.org/issues/

**Comment by flyingstar16** [comment]
Reported https://tvheadend.org/issues/6160

FWIW tvheadend seems to return the correct data via its HTTP API. Modifying the example python code from https://github.com/dave-p/TVH-API-docs/wiki/examples to 
```python
#!/usr/bin/env python3

import json
import requests
from requests.auth import HTTPDigestAuth

def api_call(ts_url):
    ts_server = 'http://192.168.44.45:9981'
    ts_user = 'user'
    ts_pass = 'user'
    ts_query = '%s/%s' % (
        ts_server,
        ts_url
    )
    ts_response = requests.get(ts_query, auth=HTTPDigestAuth(ts_user, ts_pass))
    return ts_response

def get_recordings():
    resp = api_call("api/dvr/entry/grid")
    if resp.status_code != 200:
        print('<pre>Error code %d\n%s</pre>' % (resp.status_code, resp.content, ))
        return {}

    ts_json = json.loads(resp.text, strict=False)
    return ts_json['entries']

def main():
    recs = get_recordings()
    if len(recs):
        for r in recs:
            print("Title: {}\nOwner: {}\n\n".format(r['disp_title'], r['owner']))
                
main()

```

Returns the recordings owned by my admin user.

In case it doesn't get fixed upstream would it be an option to switch the "get list recording" endpoint to using the `api` proxy instead of direct HTSP? I had a poke around the code anyway and IIUC in https://github.com/kodi-pvr/pvr.hts/blob/Nexus/src/Tvheadend.cpp#L458 what's happening is that pvr.hts is reading the list of subscriptions and filtering for recordings.

**Comment by ksooo** [comment]
I do not intent to use tvheadend HTTP API to work around tvheadend HTSP bugs.
