### ISSUE TITLE
Too many status messages after long inactivity time

### ISSUE THREAD

**Issue by shartrec** [kodi-pvr/pvr.hts#584]
**Feature request**
I  have a HTPC system with TVHeadend and Kodi which works great without any issues. 
I also have a second Kodi instance connected to the same TVHeadend instance. This system is only used rarely and when the TVHeadend client starts up on this, it receives a huge back log of notifications about timers that are added and deleted, which are a great distraction for maybe 15 minutes or more when trying to watch some recording.
It would be great if notifications were just discarded or maybe combined some way when there are more than just a few.

**Comment by ksooo** [comment]
There is a Kodi setting to suppress timer messages.

**Comment by ksooo** [comment]
I will close this issue as this cannot be fixed in pvr.hts. This feature needs to be implemented in Kodi PVR core. What you could do is raise the feature request in the Kodi forum. Thanks.

**Comment by shartrec** [comment]
Thanks Kai, The Kodi setting does partially address the issue, but only for timer updates afaict. I will raise a feature request in the Kodi forum.
