### ISSUE TITLE
Kodi 19.4 (Nvidia Shield Pro) Audio Stutter and Buffering with TVHeadend Addon

### ISSUE THREAD

**Issue by Starfoxfs** [kodi-pvr/pvr.hts#590]
Hi,

i have freshly installed TVHeadend Server to my Raspberryi Pi4 with Raspian OS 32bit Bullseye Ver. 11 Kernel 5.15
For Backend i use Kodi 19.4 Matrix with latest TVHeadend HTSP Client Addon 19.0.6 on a new Nvidia Shield TV Pro (Firmware 9.1)

On Raspberry Pi4 (same as TVHeadend Server) i use Telerising API 0.8.2 for M3U Playlist with FFMPEG Pipe to forward Playlist to TVHeadend Server.

Hardware:
Raspberry Pi4B 2GB RAM
Nvidia Shield TV Pro 2022
Fritzbox 7590 between
Connected via LAN 100mbit
Internet Connection Speed 50Mbit (53Mbit Tested) Ping about 10ms Upload 10Mbit (10Mbit Tested)

Software installed on Raspberry Pi4:
UFW Firewall
TVHeadend Server (Port 9981 & 9982 allowed for Homenetwork in Firewall)
PiHole
Unbound DNS Server
Telerising API

Ok now my 2 Problems:
On Kodi (Nividia Shield): If i stream 5.1 content i get Audio stuttering, crackling. With 2.0 Stereo AAC no problems.
Before i used PVR Simple IPTV Client the Audio (5.1 and 2.0) is fine.

In the Evening most between 8PM (UTC+2) and 9PM (UTC +2) i get solid Buffering issues (more in Streams with 5.1 Audio).

For the crackling Audio the Kodi.log says:
WARNING <general>: ActiveAE - large audio sync error: .....

For the Buffering (spamming this for some Channels (Client ID i removed)):
Update: Failed to update table 'RTL'
2022-08-31 20:46:59.232 T:16614   ERROR <general>: UpdateFromScraper: Client 'xxx' not found, can't update

Here is the whole Kodi.log

[kodi.log](https://github.com/kodi-pvr/pvr.hts/files/9467538/kodi.log)

I hope you can help me

**Comment by Starfoxfs** [comment]
Here the TVHeadend Server log:
[tvheadend.log](https://github.com/kodi-pvr/pvr.hts/files/9467750/tvheadend.log)

For Testing i have disabled Unbound DNS and Pihole

"ActiveAE - large audio sync error " with disabled Unbound and Pihole the same.

**Comment by titus-kruse** [comment]
Same issue here. Tried several hours installing Libreelec 10 again and again on my Pi4 with tvheadend 4.2 or 4.3a and different settings. Audio is ok, video lacks or doesn't start at all. DVC-C Tuner is Sundtek Media TV. After going back to Libreelec 9.2 watching tv works fine.

**Comment by ksooo** [comment]
I'm not sure this is a problem with pvr.hts add-on. Have you guys any indicators for this?

**Comment by ksooo** [comment]
No response from issue submitter for half a year. Closing.
