### ISSUE TITLE
Selecting a different video decoder

### ISSUE THREAD

**Issue by MastaG** [kodi-pvr/pvr.hts#593]
Hi there,

I'm using the v19.0.6 version of this plugin with Kodi (19.4 (19.4.0) Git:20220412-9bc14d0c11) to try and play my Tvheadend live channels, which are all encoded in h264 video.

Kodi has been patched to use ff-h264_v4l2m2m (HW) when playing h264 content.
This works great for my local videos.

However when using this plugin, it will use ff-h264 (SW).
The platform isn't powerful enough to software decode h264 live streams from my cable provider.
Is it possible I can somehow configure the plugin to just use the kodi default instead of forcing ff-264?

**Comment by titus-kruse** [comment]
Still no answer here?

**Comment by Jalle19** [comment]
I think you need to open an issue on Kodi's issue tracker instead - the codec selection is not something that the addon can control.
