### ISSUE TITLE
Channel switch times

### ISSUE THREAD

**Issue by multiple1** [kodi-pvr/pvr.hts#598]
Hello!
I am comparing two systems:
Windows 10 / Nvidia d3d11va
Ubuntu 22.04 / Intel iGPU vaapi

All systems connect to the same tvheadend server (SATIP tuner) via gbit/s copper network.
Predictive tuning is on. Tuning times should be the same for both systems.

Splitting the channel switch into 4 steps:
1. Short annoying screen flicker. dark green on windows system. black on ubuntu system.
 the flicker is annoying but takes only <=200ms on both systems.
 It would be better if a static image of the old channel is shown until the static image of the next channel is ready.

2. First static image of new channel is shown
 nearly instant on windows system if the next channel is already tuned. Ubuntu system is a little bit slower from time to time.
 Maybe this delay is different based on how quick kodi interacts / sets up the hardware decoding libs. 

3. Some kind of buffering, while still showing a static image
 ~2s on Windows. ~3-5s on Ubuntu.
 Is this some kind of buffering. I don't think that such large buffers are necessary on local wired ethernet.
 Is there some way to reduce this buffer?
 e.g. vlc has such option. Changing kodi advancedconfig.xml buffer settings did not help.

4. video plays

Another test would be to switch the ubuntu system to windows and test again.
Linux hw accelerated video support still seams to be lacking. e.g. tv channel with hevc encoding is also not working with kodi. Using vlc with vaapi to play the same channel shows no issue.

**Comment by Jalle19** [comment]
This really is not a pvr.hts addon issue but more likely a Kodi and/or tvheadend issue.

**Comment by multiple1** [comment]
It can be any issue. At first I must find out if its only an issue on my side.
Maybe it belongs here to get feedback if other people experience the same behavior.
Looking at the kodi open issue list, I don't think its belongs there either...

This issue can be observed with the tvheadend pvr client. I do not have this long buffering when watching videos from network shares. I do not use kodi for anything other than using the pvr.hts. Therefore I can not relate to other pvr clients if its a kodi general thing or not.

Does anyone observe a similar buffering delay? Or does your video start straight away after the first picture of the next channel is shown?

**Comment by Jimpan81** [comment]
Apple TV Kodi is the fastest for me , no black screen on channel change as on my Nvidia shield. But on all systems i get som pixels on sometimes, but only for 1-2 seconds .
