### ISSUE TITLE
Feature request: Force software decoding for hts streams

### ISSUE THREAD

**Issue by msxmine** [kodi-pvr/pvr.hts#604]
The AMD h264 decoder on my system handles (partially corrupted) TV streams very poorly (Video slowdowns/corruption/audio desync/kodi crashes etc.) FFMpeg on the other hand works fine.

Currently I have to use transcoding on the tvheadend server to sanitize the stream or disable HW decoding kodi-wide.

It would be nice if the addon exposed a toggle to force kodi to use software decoding for it's streams.

**Comment by ksooo** [comment]
This is nothing that should or can be handled by the add-on. The add-on just delivers the stream data to Kodi, without modifying it nor can it control the Kodi video player.

**Comment by msxmine** [comment]
Are you sure? When looking at the docs it seems that PVR addons can specify some stream properties (PVRStreamProperties/InputstreamInfo) like video dimensions, fps, codec name etc. which seem to correspond directly to properties inside Kodi's VideoPlayer.  (And CDVDStreamInfo also has a codecOptions field with a CODEC_FORCE_SOFTWARE flag).
The fact that a gettter/setter for it is missing seems to be an oversight.
Anyway, even without Kodi changes it still seems to be possible with the InputStream/Codec addon APIs.
I'm not sure if just setting PVR_STREAM_PROPERTY_INPUTSTREAM to PVR_STREAM_PROPERTY_VALUE_INPUTSTREAMFFMPEG wouldn't suffice, but I'm guessing that it just uses ffmpeg for demuxing in that case and inputstream.adaptive only forces SW decoding when HWdec conflicts with DRM decryption.

Worst case, it's possible to just toggle SETTING_VIDEOPLAYER_USEAMCODEC kodi-wide when a video starts and toggle it back on playback stopped callback.
