### ISSUE TITLE
Season 0 shows up as season 2

### ISSUE THREAD

**Issue by liam8888999** [kodi-pvr/pvr.hts#612]
Season 0 (specials) shows correctly on the tvheadend server but through pvr.hts on kodi it shows as season 2

**Comment by ksooo** [comment]
Nothing the add-on can fix. It just takes the number it gets from tvheadend and delivers it to Kodi.

**Comment by liam8888999** [comment]
I'm confused. The number in the tvheadend server is correct but it doesn't seem to be passing through correctly

**Comment by liam8888999** [comment]
this issue doesn't appear to be fixed. tvheadend correctly reads it as s0 and the kodi still shows as s2
