### ISSUE TITLE
Choppy audio only on bluetooth

### ISSUE THREAD

**Issue by ripper17** [kodi-pvr/pvr.hts#613]
Hi all, thanks for putting this Kodi-add-on together!

I've got a new issue that started after updating to Kodi 20 on Android. If I watch any stream from the TVHeadend server, the audio is very choppy almost always. There's a rare lucky chance that the audio actually works (independent of the station being watched). 

This issue does not happen when watching TV on the Smartphone speakers
This issue does not happen when watching movies or series with BT audio.
Changing BT headphones does not help.
If I start playback on VLC on the same phone, the audio works fine (BT and phone speakers).

TV Headend 4.2.8 running on openSuse Leap 15.4 fully up-to-date
Kodi 20
TVHeadend HTSP Client 20.6.1

I've attached the kodi log (I hope I didn't cut to many lines):
[kodi.log](https://github.com/kodi-pvr/pvr.hts/files/10865191/kodi.log)

I think the interesting lines are 365 (starting to watch TV where the audio stream actually worked) and line 1030 (starting to watch a channel where the audio was broken). I see a big number of ffmpeg error messages in the log, seemingly increasing with every frame?

**Comment by ripper17** [comment]
This is still happening on Kodi 21 / HTSP Client 21.2.5

Any other log I should upload?

**Comment by Jalle19** [comment]
You should open an issue for Kodi itself instead: https://github.com/xbmc/xbmc/issues

**Comment by ripper17** [comment]
So I did open a ticket with Kodi itself at

https://github.com/xbmc/xbmc/issues/25816

and a nice person named "fritsch" helped me debug quite a bit more. Audio-playback works in Kodi when bypassing the TV Headend PVR plugin, by simply putting a "strm"-file with the URL of a channel into Kodi and loading it via the Files menu. Audio playback with bluetooth headphones now works fine. 

May I ask to re-open this ticket, if you agree that it doesn't seem to be a Kodi issue, but a HTSP Client issue?
