### ISSUE TITLE
[issue] GUI is blocked when starting any live channel in Kodi Nexus

### ISSUE THREAD

**Issue by chpasha** [kodi-pvr/pvr.hts#616]
Hi there, I have a Kodi 20.1-Nexus on Coreelec with Pvr.Hts Plugin version 20.6.2.1 (Tvheadend is at 4.2.9). I must confess, that I've skipped Kodi 19, jumping from 18 directly to 20 (clean installation, different device). I have immediately noticed an issue when starting any live channel - the gui gets blocked showing a spinner and I have to wait until the channel starts (best case) or a timeout kicks in (worst case). This is a huge regression in user experience compared to old setup. I found a ticket dealing with similar problem (https://github.com/kodi-pvr/pvr.hts/issues/575) but with http mode enabled, but I definitely have this option disabled. Do I still have the same (kodi) issue? Which issue is it exactly, if so?  

P. S. I've deleted the pvr configuration and setup everything again, also switched back to default skin (just for the case) - issue still there. Ok, I do can interrupt the process by pressing "stop" on my remote, but it is still an ugly behaviour, that the GUI is blocked.

**Comment by ksooo** [comment]
What else would you do while the channel gets prepared for playback? I don’t see the problem, to be honest. And this is nothing that is controlled/caused by the add-on.

**Comment by chpasha** [comment]
Well, I click on channel and if it doesn't start within a couple of seconds, I move to next (I have multiple not very stable sources for the same channel - yes I know that tvheadend can have a channel with multiple services ordered by prio, but it didn't prove to be a reliable solution). It feels a way better this way, because the simple iptv plugin was always blocking and it sucked a lot in my opinion. What exactly has changed in Kodi to cause the issue? I would like to report it there or upvote a ticket if there is any already. Thanks, for answering by the way and supporting this great plugin  :-)

**Comment by ksooo** [comment]
Okay, you could have a point here. Please open an issue for Kodi. Most probably it will be me taking it, we will see.

**Comment by chpasha** [comment]
Thanks, I will do just that

**Comment by ksooo** [comment]
@chpasha I don't think you have a real point. I tried to press up/down/enter while the busy circle was spinning and Kodi switched to the other channel immediately, even while the busy circle was visible.

**Comment by chpasha** [comment]
Ok, I didn't come to the idea to press up/down while the spinner is shown, but I find the behaviour still silly, because I don't see the cursor and don't know what channel is selected. And the funny thing is, that after clicking multiple times somewhere else spinner was not shown any more and the behaviour was as it used to be in older versions. So it is clearly a bug (and a regression in UX), that a spinner is shown in such inconsistent way.

**Comment by ksooo** [comment]
You actually see the selected channel in upper right corner - at least with Estuary. Not saying we’re not going to change anything about the spinner, just saying that the problem is far away from being really serious. 

EDIT: and unless you wrote an issue for Kodi nobody will care. 😗

**Comment by chpasha** [comment]
Sure, more like annoyance, not as serious as rendering artefacts in coreelec 20.1-ng or missing sound on first boot in 20.1-ne  
>and unless you wrote an issue for Kodi nobody will care

I definitely will - I wanted to confirm the problem on different OS, but since you can reproduce it, I'll report it as soon as I grab a kodi.log just for the case somebody needs it :-)

P. S. I use Aeon Nox Sylvo Skin, there is literally no way to see, what is selected when the spinner is visible
