### ISSUE TITLE
Live TV Subtitles broken on Kodi 20

### ISSUE THREAD

**Issue by itprotj** [kodi-pvr/pvr.hts#617]
Came from Kodi 19.4 to Kodi 20 and use subtitles regularly as have trouble interpreting people talking and when enabling subtitles for Free to Air TV it doesn't show anything anymore.
Went back to 19.4 and no issues, once subtitles are enabled it works fine?

Something has changed between 19.4 and v20 I am thinking whether it is how Kodi interprets the subtitles or the tvheadend plugin..

If someone can guide me on how to provide logs from the two different versions I'd be happy to oblige.

**Comment by ksooo** [comment]
Please report this as an issue for Kodi. This is nothing that can be fixed in this add-on.
