### ISSUE TITLE
Cannot save settings on appletv

### ISSUE THREAD

**Issue by twhiston** [kodi-pvr/pvr.hts#618]
Hi,
I'm trying to use this with kodi on tvOS (installed with my developer licence via xcode), using the official Nexus build which includes Tvheadend HTSP 20.6.1 but it fails to correctly save any configs which I create. They will always be reverted back to 127.0.0.1 instead of the address of my TVheadend device, all other settings are also reset. It seems very inconsistent in creating and deleting configurations as well, removing them does not seem to work unless you do it twice, for example. Looking in the logs I don't see any issues, other than it saying repeatedly that it cannot connect to 127.0.0.1, but this is expected.
What information can i provide to help track down the issue here?

**Comment by ksooo** [comment]
> What information can i provide to help track down the issue here?

Please provide a debug log here, with PVR component logging activated.

**Comment by ksooo** [comment]
@twhiston please provide the requested information, otherwise we have no chance to help.

**Comment by twhiston** [comment]
Sorry for not getting back to you. I'm going to close this because Kodi on tvOS was just endless problems that are far more trouble to solve than they are worth, so I gave up and built a LibreElec kodi box instead.
