### ISSUE TITLE
Feature Request: Warn when creating an overlapping recording

### ISSUE THREAD

**Issue by calania** [kodi-pvr/pvr.hts#625]
Hello! I have used this plugin for a while now and have so far been very happy with it. I do a lot of recordings and one thing that however bothers me is that there is no warning when you create a recording that overlaps another one. It would be very nice if you would get a yes/no popup saying something like "There is already a recording during this time. Are you sure you want to create a recording?" Is this something that could be added?

**Comment by ksooo** [comment]
This is something that needs to be added to kodi pvr core, nothing the addon should do.

**Comment by phunkyfish** [comment]
Many PVRs these days allow multiple recordings at the same. For many PVRs they don’t tell you many simultaneous recordings are supported so this would be tricky to implement right.

**Comment by calania** [comment]
Okay I understand your point. Guess I will close this issue then
