### ISSUE TITLE
Disconnect from TVHeadend server while playing piped mpd-stream with "demux read no data for at least 10 secs"

### ISSUE THREAD

**Issue by tojo2503** [kodi-pvr/pvr.hts#637]
Hi,

it might be a little bit specific, but I'm trying to play a mpd-stream via TVHeadend in Kodi. TVHeadend receives the stream as a pipe from Streamlink.

Playing it from VLC through TVHeadend works perfectly fine. The Kodi addon also receives the stream and plays it but frequently quits and the plugin disconnects from the TVHeadend server.

Kodi.log then states:
`2023-12-01 14:34:37.190 T:12154    info <general>: CVideoPlayerAudio::Process - stream stalled
2023-12-01 14:34:40.144 T:11577 warning <general>: AddOnLog: pvr.hts: demux read no data for at least 10 secs; restarting connection`

TVHeadend log:
`2023-12-01 14:32:51.156 htsp: ::ffff:192.168.178.47 [ stream | Kodi Media Center ]: Disconnected
2023-12-01 14:32:51.156 subscription: 051B: "::ffff:192.168.178.47 [ stream | Kodi Media Center ]" unsubscribing from "Sky Sport Bundesliga HD", hostname="::ffff:192.168.178.47", username="stream", client="Kodi Media Center"
2023-12-01 14:32:51.159 htsp: Got connection from ::ffff:192.168.178.47
2023-12-01 14:32:51.159 htsp: ::ffff:192.168.178.47: Welcomed client software: Kodi Media Center (HTSPv35)
2023-12-01 14:32:51.160 htsp: ::ffff:192.168.178.47 [ Kodi Media Center ]: Identified as user 'stream'`

Since VLC works fine it doesn't seem to be a problem on the server side but rather on the Kodi plugin. Is it possible to raise the timeout time (10 secs). I can also compile by myself to test.

**Comment by ksooo** [comment]
Which pvr.hts version exactly?

**Comment by tojo2503** [comment]
Hi Kai,

sorry, forgot to add. I’m on Kodi 20 with pvr.hts version 20.6.5 running on NVIDIA shield.

**Comment by ksooo** [comment]
In case you want to patch the timeout, this would be the line to change:

https://github.com/kodi-pvr/pvr.hts/blob/Nexus/src/tvheadend/HTSPDemuxer.cpp#L152

**Comment by tojo2503** [comment]
Hi, thanks for the reply! Sorry but I tried and figured out it's really hard for me since it is a cross compile which I haven't done yet and seems very complicated. Do you see another easy possibility to create a test version addon for either PC or Android (NVidia Shield)?

**Comment by tojo2503** [comment]
Hi @ksooo , I managed to compile and test it with timeout set to 30 seconds.
This worked well and solved my problem. I suppose the problem is, that a DASH segment in my piped stream can be longer than 10 seconds which seems to lead to the timeout and the reconnect of the addon.
I have never worked with pull requests. Could you change the line and merge it? Thanks a lot!

**Comment by ksooo** [comment]
Thanks for testing. I think the way to go here is to introduce an addon instance setting for the timeout. I can do that once I find some free time.
