### ISSUE TITLE
Live TV HEVC streams not playing-Libreelec Intel generic

### ISSUE THREAD

**Issue by yamcenutzer** [kodi-pvr/pvr.hts#647]
This issue was previously reported as
Live TV HEVC streams not playing-Ubuntu 22.04 lts Kodi Nexus #619 and closed, imho somewhat unsatisfyingly.

I am seeing this in Libreelec 11/12 , but ONLY on Intel generic.
LE on Rpi4/5 talking to the same tvheadend server works as advertised (actual only 4, since rpi5 still does everything in SW)

Any ideas?

**Comment by ksooo** [comment]
The addon does not manipulate the stream it gets from tvheadend. It just hands the data over to kodi player. So nothing that can be fixed in the addon.

**Comment by Jalle19** [comment]
Perhaps we should use "Transfer issue" and move these to Kodi's issue tracker?

**Comment by Long-Man** [comment]
Had a similar problem with Pi4 and my NUCs. 
The fix for me was disabling 

-  Settings>Player>Video>_Use HEVC VAAPI_

Maybe it will work for you too.

**Comment by yamcenutzer** [comment]
It is an interesting issue, as no one has any idea how it can be. 
- it works on rpi
- it doesn't work on intel
- it works without VAAPI (i.e. SW) but that is NOT what anybody wants in the long term
- maybe it works as http instead of rtsp, but even then only as SW, and then you lose timeshift, which is what a TV-player is all about
- the recorded stream works perfectly in VAAPI i.e HW

- if the client is the same on rpi and intel , and it doesn't touch the stream , and the recorded stream (typcally mkv or mp4) works, 
 then what remains is that rtsp must be handled somehow different on intel and rpi.

What am I missing?

I am asking here, because, after trying in the LE forum, it seems that the kodi/media community is quickly losing interest and/or skills when it comes to intel, and is rather fixated on on the new class of throwaway arm devices or misusing the rpi for it.

**Comment by ksooo** [comment]
@yamcenutzer again, this is the wrong place to ask, because the issue cannot be fixed in pvr.hts. Go and open an issue for Kodi: https://github.com/xbmc/xbmc/issues

**Comment by yamcenutzer** [comment]
guess where I came from :-), But you're probably right I need to rephrase and try again over there
