### ISSUE TITLE
KODI with Tvheadend and WireGuard on Andriod TV

### ISSUE THREAD

**Issue by etofi** [kodi-pvr/pvr.hts#666]
I have a new Xiaomi TV Box S with Android TV.

I have installed KODI with the add-ons Tvheadend and IPTV Simple Client.
I have the IPTV Simple Client on it to test whether I can access my SatIP server directly.

As long as I have WireGuard off, everything works perfectly.
When I switch it on, only access via the IPTV Simple Client AddOn works - Tvheadend is dead.

On my Android phone with WireGuard on, however, I can access my Tvheadend server without any problems.

Is there a trick how I can get this to work under Android TV?

Greetings Eric

**Comment by etofi** [comment]
UPDATE:
With the "Dream Player for Tvheadend", access works even with WireGuard switched on, so it must be the KODI AddOn.

**Comment by Jalle19** [comment]
pvr.hts uses port 9982 while those other clients you mention use port 9981, that could be an issue if you have a firewall in between somewhere and only allow one but not the other.

**Comment by etofi** [comment]
> pvr.hts uses port 9982 while those other clients you mention use port 9981, that could be an issue if you have a firewall in between somewhere and only allow one but not the other.

I have no firewall.

**Comment by Jalle19** [comment]
Where is your WireGuard connecting?

**Comment by etofi** [comment]
> Where is your WireGuard connecting?

I use WireGuard on my FritzBox.
With all other devices I have full access. Also on my handy with the TVHClient app. The app also uses the port 9982

**Comment by Jalle19** [comment]
Not sure why it doesn't work for you, but I'm sure it's not something the addon can help with. Try restarting Kodi after you activate WireGuard, and if that doesn't work, try asking for help on the Kodi forums.
