### ISSUE TITLE
log's get spammed with "error <general>: CCurlFile::Open - <http://127.0.0.1:9981/imagecache/27> Failed with code 404:"

### ISSUE THREAD

**Issue by ghost** [kodi-pvr/pvr.hts#667]
On LE12 and now on LE13 (both nighties) each time kodi starts or a channel is switched I get the above entries in the kodi.log. and TVH's service.log too.
I see this since around pvr.hts was split into 2 instance or when the PVR client got a individual config instance. (long long ago)

I tried a lot to fix this, but without success, so far.
- freshen the picons in TVH
- cleaned the database for PVR (Settings => "PVR & Live TV")
- cleaned the DB's under Kodi
- cleaned under TVH the directory (/.kodi/userdata/addon_data/service.tvheadend43/imagecache), what wasn't empty.
- configured the PVR with/with out user and passwd
- de- and new-installed TVH and PVR and left the config defaults
- setup up a clean box since the issue first appeared serveral times and lastly today
- ...

nothing !
and I'm not alone:
https://forum.libreelec.tv/thread/26351-kodi-is-not-loading-channel-icons-from-tvheadend-server/?postID=174588&highlight=imagecache#post174588

this is a fresh/clean installed LE13 (last nightly) on an NUC13
I've read about the need of installing additional icons... . if so: I didn't.

kodi.log
[kodi.log](https://github.com/user-attachments/files/16338608/kodi.log)

TVH'S service.log
[service.log](https://github.com/user-attachments/files/16338610/service.log)

**Comment by ksooo** [comment]
`CCurlFile::Open` is an error logged by Kodi, because tvheadend claims that the requested image is not available (error 404). Nothing the addon can fix.

What happens if you enter one of the failing URLs from the log (e.g. `http://127.0.0.1:9981/imagecache/27` in the address bar of a browser? Do you see a channel logo image in the browser?

**Comment by ghost** [comment]
thanks for fast support !

I wasn't sure what produced the error (kodi, TVH, PVR).
Since errors are  generated via channel switching, my bet was PVR.
While they are in the TVH logs too, my last bet was kodi, cause kodi has it's own log. (why should kodi write errors to TVH's log ...)
and TVH log's were clean after TVH restart
anyway, Sorry !

====

I needed to adjust the IP to 192.168.100.22, where kodi is running
turned out:  a website with bold text "404 Not Found"
tried a file/number what is for sure under  ~/.kodi/userdata/addon_data/service.tvheadend43/imagecache/meta

====

I'll close this bug. 
I'll open one at kodi and best I could point to it here
Okay ?
