### ISSUE TITLE
Addon not available on Android 14 / Kodi 21.0

### ISSUE THREAD

**Issue by UweSauter** [kodi-pvr/pvr.hts#684]
It seems the latest version of this plugin is 20.7.2. At least that is shown on the plugin page within Kodi.

Trying to install it in Kodi 21.0 I get (translated from German): "Dependency of kodi.binary.instance.inputstream in version 3.2.0 could not be resolved".

I have Android 14 (LineageOS 21) and Kodi 21.0 (Git 20240406-60c4500054-dirty, compiled 2024-05-17) installed.

Would it be possible to release a compatible version?

**Comment by ksooo** [comment]
> It seems the latest version of this plugin is 20.7.2.

 Latest version of pvr.hts for kodi 21, available from the official kodi addon repo, is 21.5.2
