### ISSUE TITLE
Playback issues on Android

### ISSUE THREAD

**Issue by Shininess8816** [kodi-pvr/pvr.hts#686]
I get some weird playback issues  in Android.

Particularly with recordings in HD. Often in exactly the same point of recording

I captured debug logs: https://paste.kodi.tv/rayuquwace.kodi

In this example - The great british bakeoff - The recording stops playing at exactly the same point , when a commercial transitions into the news. Skipping past this past appears to allow playback (Although it can crash again, frequently). 

I have observed this behavior at other points - Another recording will not play past a certain point in 'Bluey' a CBBC show. 

I am able to play these recordings elsewhere without issue - Jellyfin will play no problem on the same machine (Although it has to attempt to start the file a few times and I do get an occasional white flash on the screen). Playing from laptop & PC - No issues 

I have attempted to load android on my raspberry pi 4 and get the same behavior, there.

On the same pi4 - Libre elec  - Kodi - I get flawless playback.

**Comment by ksooo** [comment]
Nothing this addon can fix. This is a kodi issue.
