### ISSUE TITLE
Guard against potential duplicate IDs from server

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.hts#69]
References: http://forum.kodi.tv/showthread.php?tid=232815, https://tvheadend.org/issues/3025

Should we try to detect and workaround such issues?

**Comment by Glenn-1990** [comment]
@Jalle19 
I was just preparing a PR to fix a similar issue:
https://github.com/Glenn-1990/xbmc/commit/30c1d64607eb3ca15dbbda13cbe656abe587474e

This issue was never resolved?

Responding here as it seems only affecting tvh users.
