### ISSUE TITLE
MacOS: ARM Version does not connect to tvheadend

### ISSUE THREAD

**Issue by Marty56** [kodi-pvr/pvr.hts#692]
Hi,

I am using Kodi both on a MacBook Air M1 and on a MacBookPro 16.
Using the identical configuration and being in the same network, the MacBookPro connects to the tvheadend server and works fine. The MacBook Air does not connect.

In the log it stated (translated from German) "server cannot be reached".

Any idea?

**Comment by ksooo** [comment]
Using it on a daily base with a MacBook Air M3. No problems at all.

**Comment by ksooo** [comment]
> "server cannot be reached"

Has your Mac permission to access resources in local network? Something new for Sequoia. Check OS settings.

**Comment by Marty56** [comment]
Thanks for the hint.
This advice resolved the issue.
