### ISSUE TITLE
Sponsoring packages to official Debian repository

### ISSUE THREAD

**Issue by rbalint** [kodi-pvr/pvr.hts#88]
Hi,

I'm maintaining the XBMC/Kodi packages in Debian and I am also maintaining xbmc-pvr-addons which is now split to separate upstream repositories here.
I intend keeping Kodi up-to-date in Debian and the PVR packages as well but seeing the most of packaging work done here, too makes me wonder if we could work together on the official Debian packages instead working independently and duplicating part of the effort.
I would happily sponsor the uploads to Debian if you would like to be the maintainer listed or we could co-maintain the packages.

https://packages.qa.debian.org/k/kodi.html
https://packages.qa.debian.org/x/xbmc-pvr-addons.html

**Comment by wsnipex** [comment]
If nobody else speaks up, I'd be fine with co-maintaining the addons, but only if it doesn't mean every obscure lintian error has to be fixed for every addon ;)
We'd also accept every sane packaging fix in case you want to continue to be the sole maintainer.

**Comment by rbalint** [comment]
Thank you. I'm packaging kodiplatform right now which needed a lot of changes, but I'll be back with the packaging changes.
I'm not a fan of some lintian warnings either. :-)

**Comment by e-tobi** [comment]
As the current maintainer of the Debian-VDR packages I would like to take care about the packaging of the VNSI addon.

**Comment by jcromero** [comment]
@rbalint Now that kodiplatform has been packaged by you for Debian, is it possible to build a debian package in sid/testing using this repo? Some pointer to instructions of how to do it?

**Comment by e-tobi** [comment]
Please see: http://anonscm.debian.org/cgit/pkg-multimedia/kodi-pvr-vdr-vnsi.git
kodi-pvr-vdr-vnsi is currently in the Debian-NEW queue awaiting approval by the FTP-Master team.

The packaging for other addons should be similar. It's pretty straight-forward. Just take care of the cec-platform references (which are named 'cec-platform' on Debian instead of just 'platform' (see [here](http://anonscm.debian.org/cgit/pkg-multimedia/kodi-pvr-vdr-vnsi.git/tree/debian/patches/libcec-platform.patch)) and take care of the multi-arch install target (see [here](http://anonscm.debian.org/cgit/pkg-multimedia/kodi-pvr-vdr-vnsi.git/tree/debian/rules#n20)).

What addon are you interested in? kodi-pvr-hts? I would maintain this in Debian as well, but I need someone to test this, because personally I only use kodi-pvr-vdr-vnsi with the VDR backend.

**Comment by jcromero** [comment]
@e-tobi Yes, I'm interested in kodi-pvr-hts. I can test the package if you tell me where I can get it.

**Comment by e-tobi** [comment]
I'll try to do the packaging today and will let you know when there's something to test,

**Comment by jcromero** [comment]
@e-tobi Nevertheless, it would be fine to have the package vdr-plugin-vnsiserver in jessie. That way I could also try vdr. Currently, my PVR (be it tvheadend or vdr) is in a dockstar (debian stable armel arch) and the clients (be they kodi or vlc) in other machines ...

**Comment by e-tobi** [comment]
Ok, I've done some quick packaging work on kodi-pvr-hts. If you want to test this, you can get the sources via:
dget http://www.e-tobi.net/.stuff/kodi-pvr-hts_2.1.18-1.dsc
or:
http://anonscm.debian.org/cgit/pkg-multimedia/kodi-pvr-hts.git
or the binary:
http://www.e-tobi.net/.stuff/kodi-pvr-hts_2.1.18-1_amd64.deb
Regarding vdr-plugin-vnsiserver for jessie - Maybe I will upload the latest vdr package and plugin to jessie-backports. but probably not very soon.
Meanwhile you can use the packages from my private repository:
    deb http://e-tobi.net/vdr-experimental jessie vdr-multipatch base backports addons

**Comment by wsnipex** [comment]
We'd appreciate a PR for non debian specific packaging fixes

**Comment by jcromero** [comment]
@e-tobi Sorry, but I can not build vdr-plugin-vnsiserver for jessie (it needs vdr 2.2.0) and I cannot use your binary packages either (armel arch in my dockstar)

**Comment by e-tobi** [comment]
You can include sid in apt-sources and possibly use pinning to get the current kodi version. Otherwise you have to wait a while for everything to migrate to testing.
I currently have no plans to provide vdr-armel packages for Jessie, I only have armhf at the moment.

**Comment by jackyohh** [comment]
kodi-pvr-hts_2.1.18-1_amd64.deb is working great with kodi 15.2~rc3+dfsg1-1. Only Timeshift is not working, but this shouldn't be a packaging problem.

**Comment by rbalint** [comment]
@e-tobi Now kodi and kodiplatform is present in jessie-backports if you would like to upload addons there

**Comment by e-tobi** [comment]
@jackyohh: The FTPMaster team was pretty fast (thanks!) and kodi-pvr-hts I've uploaded some days ago is now available in Sid. Packaging isn't very difficult for this package (besides a [complex copyright-file](http://anonscm.debian.org/cgit/pkg-multimedia/kodi-pvr-hts.git/tree/debian/copyright)). But it would be nice if you could test this and provide feedback.

@rbalint: I'll do so soon.

**Comment by jackyohh** [comment]
@e-tobi yes i see package on sid. Shall i post bugs here or at debian? btw addon works fine except timeshifting. i never got it working :(

**Comment by e-tobi** [comment]
Please post bugs regarding the Debian packaging at debian.
Right now I have no easy way to test the time shifting issue. I might buy a new TV soon with a Sat/IP server. This should make it easy to set up a TVHeadend for testing on my notebook.

**Comment by rbalint** [comment]
@wsnipex I have upstreamed the needed changes and packaged all the addons which were available for XBMC under the Multimedia Team's umbrella (except for the demo addon which has probably no use on Debian):
https://qa.debian.org/developer.php?login=pkg-multimedia-maintainers@lists.alioth.debian.org
The packages are waiting for FTP Masters' approval.

For addons still missing from Debian please ping me.

**Comment by e-tobi** [comment]
At least kodi-pvr-hts and kodi-pvr-vdr-vnsi are now also available in jessie-backports.

**Comment by Jalle19** [comment]
@rbalint can we close this issue?

**Comment by rbalint** [comment]
Sure, the package is available both in unstable and jessie-backports:
https://packages.qa.debian.org/k/kodi-pvr-hts.html

Please report packaging related issues to Debian, this way we can act on them faster.
Thanks!
