### ISSUE TITLE
Don't show "no free adapter" when pre-tuning fails

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.hts#91]
Consider this scenario:

1. User sets "use pretuners" to 2.
2. User starts recording something (basically hogging one tuner for some time).
3. User starts zapping through channels

What happens:

The "no free adapter" message is shown all the time. This shouldn't happen.

**Comment by Glenn-1990** [comment]
This should be fixed with: 
https://github.com/kodi-pvr/pvr.hts/pull/82

**Comment by Jalle19** [comment]
Yes.

**Comment by Jalle19** [comment]
I have to check if this message came from the pre-tuning subscription or from a recording that was about to start. The particular show has its priority set to "Unimportant" in tvheadend so that could be the issue. Pre/post-tuning priority should be lower than the lowest DVR priority, is that the case now?

**Comment by Glenn-1990** [comment]
Yes, it should be, pretuning uses weight 40 and that should be lower than unimportant.
