### ISSUE TITLE
Sddon version 2.2.6

### ISSUE THREAD

**Issue by jteeuw** [kodi-pvr/pvr.hts#93]
I have upgrade the addon to version 2.2.6 last night , but now i have the following problem , i cannot start a recording from kodi and all previous recordings show a date of 01-01-1970 2:00

In the kodi log I see the following :

13:53:12 T:140700803094592 WARNING: JSONRPC: Could not parse type "PVR.Details.Channel"
13:53:12 T:140700803094592 WARNING: JSONRPC: Could not parse type "PVR.Details.ChannelGroup.Extended"
13:53:12 T:140700803094592 WARNING: JSONRPC: Could not parse type "GUI.Property.Value"
13:53:12 T:140700803094592 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
13:53:12 T:140699227907840  NOTICE: Thread JobWorker start, auto delete: true
13:53:12 T:140699236300544  NOTICE: Thread LanguageInvoker start, auto delete: false
13:53:12 T:140700803094592  NOTICE: ActiveAE DSP - starting
13:53:12 T:140700803094592  NOTICE: initialize done
13:53:12 T:140700803094592  NOTICE: Running the application...
13:53:12 T:140699227907840  NOTICE: PVRManager - starting up
13:53:12 T:140699219515136  NOTICE: Thread PVRManager start, auto delete: false
13:53:12 T:140699211122432  NOTICE: Thread PVRClient start, auto delete: false
13:53:12 T:140699211122432   ERROR: PVR - invalid timer type supplied by add-on 'unknown'. Please contact the developer of this add-on: Adam Sutton, Sam Stenvall, Lars Op den Kamp, Kai Sommerfeld
13:53:12 T:140699236300544   ERROR: Previous line repeats 4 times.

I'm using HTS Tvheadend 4.1-373~gcb5f6a1 with Kodi 16.0-ALPHA2 Git:38c4b2a

**Comment by ksooo** [comment]
What's the latest add-on version that works for you? Btw, I only test with latest stable tvheadend version, which is 4.0.5 my experience is that things break quite often wortht tvh 4.1 unstable.

@metaron-uk perhaps something introduced by your API 3.0.0 changes? Could you please take a look? I'm not at home for the rest of the week, having only very limited internet access.

**Comment by jteeuw** [comment]
The version that is not working is : 2.2.6-1~vivid - kodi-pvr-tvheadend-hts, is there an easy way to revert back to an early version

**Comment by metaron-uk** [comment]
2.2.6 needs a kodi version newer than Git: 52832f42610a to work (i.e. with PVR API 3.0.0 changes)
2.2.5 needs a kodi version older than Git: 52832f42610a to work (i.e. PVR API 2.1.0)

The version of Kodi you say you're running (Kodi 16.0-ALPHA2 Git:38c4b2a) doesn't appear in the main kodi repository, so I'm guessing it's something created by the ~vivid package maintainer with local patches.

If you search your kodi.log file for XBMC_PVR_API_VERSION does it tell you anything interesting?

**Comment by metaron-uk** [comment]
just to confirm with the installation detailed below I get sensible time/date for recordings:
HTS Tvheadend 4.1-210~g4d5a4eb-dirty (gentoo emerge installation from git a month or two ago)
latest kodi Jarvis master (Git: f8be3c336639f2b7f0fd937153c9a6cac79c0f4d )
latest pvr.hts 2.2.6 master (Git: d2763613b050447b6eaaf7e11a4bcbcec2770314 )
```
09:35:52 T:2836097856  NOTICE: PVRManager - starting up
09:35:52 T:2818886464  NOTICE: Thread PVRManager start, auto delete: false
09:35:52 T:2810235712  NOTICE: Thread PVRClient start, auto delete: false
09:35:52 T:2810235712   DEBUG: RegisterClient - registering add-on 'Tvheadend HTSP Client'
09:35:52 T:2810235712   DEBUG: Previous line repeats 1 times.
09:35:52 T:2810235712   DEBUG: PVR - Create - creating PVR add-on instance 'Tvheadend HTSP Client'
09:35:52 T:2810235712   DEBUG: ADDON: Dll Initializing - Tvheadend HTSP Client
09:35:52 T:2810235712   DEBUG: SECTION:LoadDLL(/usr/local/lib/kodi/addons/pvr.hts/pvr.hts.so.2.2.6)
09:35:52 T:2810235712   DEBUG: Loading: /usr/local/lib/kodi/addons/pvr.hts/pvr.hts.so.2.2.6
09:35:52 T:2844486464   DEBUG: CPythonInvoker(0, /home/andrew/.kodi/addons/service.xbmc.versioncheck/service.py): start processing
09:35:52 T:2810235712    INFO: AddOnLog: Tvheadend HTSP Client: pvr.hts - starting PVR client
```

Don't worry if you can't find XBMC_PVR_API_VERSION - that seems to be something that pvr.mythtv puts out, I don't see it when using pvr.hts.

My guess is that you are running incompatible versions of kodi and the pvr.hts addon. If you haven't updated your kodi version recently this is definitely the problem as API3.0.0 was only merged last Thursday!

**Comment by metaron-uk** [comment]
Quick update: Also works fine here with 4.1-373~gcb5f6a1 tvheadend. Definitely something wrong with your kodi installation.

**Comment by jteeuw** [comment]
I reverted back to version kodi-pvr-hts_2.2.5-2-vivid_amd64.deb and everything is working again, will wait till the Kodi package has updated ( I’m using ppa:wsnipex/xbmc-fernetmenta-master)
